### ISSUE TITLE
Add google analytics to the application

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#1029]
Seems like GA tag is in the config, let's check prod how GA is implemented and what is tracked and re-implement it.

**Comment by eyosef** [comment]
- [X] integrate google analytics script tags #1044 
- [x] maintain GA unique ID dynamically #1044 
- [ ] send events to the GA dashboard

**Comment by vaidotasp** [comment]
moving this to deliverable 4.
