### ISSUE TITLE
WCAG/ Level A Accessibility Report

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#1035]
Assess if the map template, report, and widgets used to display analysis results are compliant with Level A and AA WCAG standards.

Evaluate:

1. What % of Mapbuilder is accessible and where can there be improvements
2. Provide a report with recommendations/enhancements for improvements.
3. LOE estimation

**Comment by eyosef** [comment]
Implement accessibility testing per feature/section of app

- [X] increase lighthouse accessibility score #1062 
- [x] header *
- [x] left panel *
- [x] map widgets *
- [x] left panel *

_* The report was created/shared on May 21st_

**Comment by eyosef** [comment]
Closing because this was implemented & the team was provided the accessibility report.
