### ISSUE TITLE
Layer panel is overlapping footer

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1082]
On smaller screens, layer panel is expanding overtop of the footer.

**Comment by vaidotasp** [comment]
Small screen size (laptop) notice that left panel overlaps with the footer a bit. We need to push left panel up, something like `top: 105px` may do it.
ALSO another issue with the left panel is on mobile view, panel overlaps HEADER. Both issues need to be fixed as part of 1 PR.

<img width="1077" alt="Screen Shot 2020-06-04 at 2 03 22 PM" src="https://user-images.githubusercontent.com/12076555/83794561-31c69c80-a66c-11ea-9147-371d2f311247.png">
<img width="394" alt="Screen Shot 2020-06-04 at 2 02 33 PM" src="https://user-images.githubusercontent.com/12076555/83794566-325f3300-a66c-11ea-9839-bde63967cdf9.png">
