### ISSUE TITLE
Report - Tree cover loss not showing up in report

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#1087]

**Comment by vaidotasp** [comment]
I was looking through TREE COVER LOSS in print map and report view, but it seems like it is showing up, could you try and reproduce @csphang ?

<img width="948" alt="Screen Shot 2020-06-04 at 3 34 39 PM" src="https://user-images.githubusercontent.com/12076555/83802620-0eeeb500-a679-11ea-913a-2c2833040531.png">
<img width="457" alt="Screen Shot 2020-06-04 at 3 34 07 PM" src="https://user-images.githubusercontent.com/12076555/83802624-101fe200-a679-11ea-8a78-8cb7290c3f10.png">
<img width="1051" alt="Screen Shot 2020-06-04 at 3 33 53 PM" src="https://user-images.githubusercontent.com/12076555/83802628-11e9a580-a679-11ea-981b-643eec03ae00.png">

**Comment by csphang** [comment]
@vaidotasp it is showing up for me as well. Marking this ticket as closed.
