### ISSUE TITLE
Documents tab shows "pulsing effect" even if there are no documents available

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#1088]
Currently "pulsing effect" shows on analysis and document tabs anytime users select a feature on the map. This is existing behavior in 3x mapbuilder: http://blueraster.teaches-yoga.com/DRC?l=fr

@csphang Do we have a confirmation that it is a bug in 3x and we should only show this effect when we have documents and no effect would be shown if there are no documents available?

**Comment by csphang** [comment]
@vaidotasp I see what you're saying. Putting this on hold.

**Comment by vaidotasp** [comment]
Note: Contract Deliverable 5, item 12.2
