### ISSUE TITLE
Recent Imagery - add percentages to bottom of slider; add metadata from Kai

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#1099]
- [x] Add percentages
- [x] metadata

**Comment by vaidotasp** [comment]
@csphang Flagship have these options for imagery range:
<img width="173" alt="Screen Shot 2020-06-08 at 2 34 44 PM" src="https://user-images.githubusercontent.com/12076555/84067372-56d14d00-a995-11ea-8179-845881780ac7.png">

Our app has these below because that is the translations we have. Do we need to get the translations or should we implement additional options of "1 week" and "4 weeks" in English only?
<img width="146" alt="Screen Shot 2020-06-08 at 2 34 29 PM" src="https://user-images.githubusercontent.com/12076555/84067392-5cc72e00-a995-11ea-9556-286431595e26.png">

**Comment by csphang** [comment]
@vaidotasp let's table the more dates for now since we don't have translations yet. I've updated the task title to remove this.

**Comment by k-kresek** [comment]
Hi! I have the metadata for this feature - I realized that I never sent this to you! It's in a document and I will send to Christina via slack. I'm also working on getting acquainted with the translations software that we use, so I'll keep track of which translations you need and hopefully get them processed soon.

**Comment by vaidotasp** [comment]
Updated the API endpoint with the one on the flagship. Changes should be reflected in our develop branch.
https://alpha.blueraster.io/gfw-mapbuilder/develop/
