### ISSUE TITLE
Styling - left panel expand/collapse layer caret

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1118]
**Windows: Chrome, FF, Edge**

**Tested on** https://alpha.blueraster.io/gfw-mapbuilder/test/deliverable1/

- [x] Reduce caret size to 1.0 rem
- [x] Standardize border-bottom thickness for Chrome & Edge
- [x] Add color: #555
- [x] Move caret up a bit to be more middle-aligned w/the layer title

## Chrome
![2020-06-13_10-47-58](https://user-images.githubusercontent.com/13664037/84573737-7939e080-ad70-11ea-8c7c-b9eb03cfab75.jpg)

## Firefox
![2020-06-13_12-30-11](https://user-images.githubusercontent.com/13664037/84574061-47c21480-ad72-11ea-9282-5b0341ac74d8.jpg)

## Edge
![2020-06-13_12-31-22](https://user-images.githubusercontent.com/13664037/84574013-ef8b1280-ad71-11ea-9774-5c8bc928e711.jpg)

**Comment by vaidotasp** [comment]
Bottom border issue may be solved already? Can you take a look again @csphang? Other items were done, but that one I had a hard time reproducing.

**Comment by csphang** [comment]
@vaidotasp it's still occurring for me in Edge. Chrome looks fixed now. I cleared cache before testing.

![2020-06-15_13-03-49](https://user-images.githubusercontent.com/13664037/84685730-bf29ac80-af08-11ea-815c-b99ab9060eb0.jpg)
