### ISSUE TITLE
Styling - right hand widgets

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1119]
**Windows: Chrome, Firefox, Edge**

**Tested on** https://alpha.blueraster.io/gfw-mapbuilder/test/deliverable1/

## Chrome
![2020-06-13_12-05-19](https://user-images.githubusercontent.com/13664037/84573830-e64d7600-ad70-11ea-92dc-43bfc07f566c.jpg)
![2020-06-13_12-24-34](https://user-images.githubusercontent.com/13664037/84573832-e8afd000-ad70-11ea-8ebf-7c5e325b01d9.jpg)

## Firefox
![2020-06-13_12-26-04](https://user-images.githubusercontent.com/13664037/84573896-43e1c280-ad71-11ea-8715-08f4a3c2103a.jpg)

## Edge
![2020-06-13_12-28-24](https://user-images.githubusercontent.com/13664037/84573934-7a1f4200-ad71-11ea-8793-9fcce2276f50.jpg)

**Comment by vaidotasp** [comment]
Firefox should be good! Can you do a fresh clear cache and try it again for the borders? I was having a hard time reproducing the issue.

**Comment by csphang** [comment]
@vaidotasp looks good in chrome and edge now after empty cache and hard reload

![2020-06-15_13-01-48](https://user-images.githubusercontent.com/13664037/84685491-6528e700-af08-11ea-8100-b0c96f7c0462.jpg)
