### ISSUE TITLE
Config out Footer privacy policy

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1121]
Add privacy policy as a configurable item. Will need ability to specify a label + link

![2020-06-13_12-51-24](https://user-images.githubusercontent.com/13664037/84574475-a7212400-ad74-11ea-8f21-5effa02819e3.jpg)

**Comment by vaidotasp** [comment]
Added WIKI section under PlainAttributes section
![image](https://user-images.githubusercontent.com/12076555/84682597-de720b00-af03-11ea-80d6-09cdc325c2e8.png)
