### ISSUE TITLE
[Share]: Turn on tree cover loss and apply a filter for time. After adjusting the filter, the correct dates are applied in share url but additional land use layers are turned on

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1156]
Steps to reproduce:

1. Turn off all layers
2. Turn on TCL and apply a date filter
3. Share > copy + paste url into browser tab
4. shared app shows correct date filter but also timer sales and community forests datasets are turned on

![2020-09-29_15-29-25](https://user-images.githubusercontent.com/13664037/94606609-b87d3600-0268-11eb-8cea-6e5ede7eea39.jpg)

**Comment by vaidotasp** [comment]
@csphang take a look at the latest build and see if you can reproduce this issue: 
https://alpha.blueraster.io/gfw-mapbuilder/develop/
