### ISSUE TITLE
Integrate Planet Imagery

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1181]
### MapBuilder Planet API Key: 
See pinned message in slack

### Description
In the Basemap section of MapBuilder, add in a Planet Imagery option. This should have a selector for the year as well as Image Type (choices are `Natural color` or `False color (NIR)`)

**Comment by vaidotasp** [comment]
UI done, waiting on proxy solution from WRI

**Comment by vaidotasp** [comment]
Test Link: https://my.gfw-mapbuilder.org/planet-test/index.html

**Comment by csphang** [comment]
@vaidotasp are we able to turn the background color grey when selecting the Landsat imagery? I noticed if i go from Open Street Map to Planet Imagery, the basemap changes appropriately but it still looks like OSM is actively selected in left-panel.

The date ranges order oldest to newest when looking at them top to bottom, which matches the ordering we have for Landsat years. It does look like Flagship orders the dates in the opposite direction (newest on top) but i don't think it's needed for MapBuilder.

**Comment by vaidotasp** [comment]
@csphang fixed the background selecting gray effect. Take a look, same link.

**Comment by vaidotasp** [comment]
completed
