### ISSUE TITLE
Tree Cover Loss 2019 Analysis

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1183]
Endpoint:
Example endpoint from flagship: https://data-api.globalforestwatch.org/analysis/zonal/531ec4177dc3cc4aa5b84f057b4a8e9d?geostore_origin=rw&sum=area__ha&filters=umd_tree_cover_density_2000__30&start_date=2001-01-01&end_date=2019-12-31

### Description
Swap analysis endpoint to include 2019 TCL tree cover loss.

**Comment by vaidotasp** [comment]
this is completed.
