### ISSUE TITLE
Social Logins on MapBuilder not working

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1209]
**Describe the bug**
Logging into MyGFW using MapBuilder with the social logins is not working. 

**To Reproduce**
1. Go to 'http://my.gfw-mapbuilder.org/v1.latest/' or another mapbuilder url
2. Click on 'Log in to my GFW'
3. Enter a social login to access MyGFW.
4. Logging in takes you to the RW API page, but does not enable access to your account.
5. Process take you off the map page and when you reload, you have to do the login process again (which still doesn't work.)
6. Tried this on several different MapBuilders with different social logins which yields the same issue.

**Expected behavior**
This process should log you into MyGFW and enable access to your account from MapBuilder.

**Screenshots**
Step One: ![social_login](https://user-images.githubusercontent.com/49986590/133473404-952882dc-df60-497a-92cf-8d29b0e55c0a.png)
Step Two: ![Capture](https://user-images.githubusercontent.com/49986590/133473477-a26c626d-5e39-47c7-8491-f8d5c8f1a0f3.JPG)
Step 3: ![Capture1](https://user-images.githubusercontent.com/49986590/133473505-b62b17eb-a7a9-4106-95be-ad26e34a34b8.JPG)

**Comment by vaidotasp** [comment]
this is fixed.
