### ISSUE TITLE
Unable to analyze custom shapefiles that are added to the MapBuilder application using a public account in v1.5

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1211]
Details:
-	Users that are implementing the public workflow are unable to analyze custom shapefiles that are added to their webmap via the file upload.  
-	Custom shapefiles were analyzeable for Public users in version 1.4.2 but arean’t available in version 1.5.
-	May have to do with data type ‘feature collection’ no longer being able to be analyzed.
-	If so, please restore the ‘feature collection’ data type to be analyzable.

Example Cases:
- PNG REDD and Forest Monitoring Web-Portal (v.1.5.)
https://my.gfw-mapbuilder.org/v1.latest/index.html?appid=c8e4162ef1dd4891aad9b560ac88e55b
- PNG REDD and Forest Monitoring Web-Portal (v.1.4.2)
https://www.arcgis.com/home/item.html?id=846b8de39eca44c1815cd0df729f040b

**Comment by k-kresek** [comment]
Testing URL now available: https://my.gfw-mapbuilder.org/v1.latest/index.html?appid=c8e4162ef1dd4891aad9b560ac88e55b

**Comment by vaidotasp** [comment]
this is done
