### ISSUE TITLE
Overlapping polygon analysis

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1228]
Testing URL: https://alpha.blueraster.io/gfw-mapbuilder/test/multiple-polygon/

**Comment by k-kresek** [comment]
https://user-images.githubusercontent.com/49986590/146836437-05799893-2be4-4706-90f2-224577956ac1.mp4

Issue with selecting polygon from map. When you click a polygon, it redirects to the attribute tab even when you are selecting the polygon for use in overlapping analysis. Polygon selection is unable to be added to overlapping analysis.

**Comment by davidlstarr** [comment]
@k-kresek We are trying to replicate the issue but are unable to view the layers coming from https://gis.forest-atlas.org/server/rest/services/. Do you know of any issues with the server that holds these layers? It looks like it is down at the moment. Here is the webmap link as well, https://blueraster.maps.arcgis.com/home/webmap/viewer.html?webmap=0c7952395699462cafe4427e0981cfe2, if needed.

![Screen Shot 2022-01-04 at 11 12 32 AM](https://user-images.githubusercontent.com/7062554/148089070-11fe2b8e-4981-4989-9bbe-5dca23efd854.png)

**Comment by davidlstarr** [comment]
@k-kresek It looks like when you select a polygon to analyze you need to select the 'Add to Analysis' button in the attribute tab. Please let me know if this addresses the issue. Thanks!

https://user-images.githubusercontent.com/7062554/148560912-acea00d8-06e6-4de0-81c9-41b2f6f2351d.mov

**Comment by k-kresek** [comment]
Yes! This definitely addresses the issue - thanks for pointing that out! Do you think it's confusing that a user has to go back and click 'add to analysis' after they indicated they want to add a selected polygon to an overlapping analysis? Currently, upon entering the map, they would have to:

1. Click on one shape
2. Navigate to analysis tab
3. Click analyze overlapping area
4. Go back to previous tab to view attributes of original shape
5. Click "add to analysis"

Is there a way to autopopulate the polygon that they originally selected into shape one?

Thank you!

**Comment by davidlstarr** [comment]
Is it valuable for the user to see the attributes of the polygon before adding to the analysis?

**Comment by k-kresek** [comment]
https://user-images.githubusercontent.com/49986590/148601840-9067c722-ef64-45d8-915e-5d5f533e78f1.mp4

Interesting behavior with highlighting of polygons. Issue happens when user:

1. Selects polygon
2. Goes to analysis and selects multi polygon analysis
3. Goes to analysis tab and selects add to analysis
4. Selects shape two and clicks on polygon of choice
5. Changes mind and selects a different polygon 

Issue is that previously clicked polygons do not become unhighlighted. Correct highlighting would remove the highlight from the previously clicked polygon and highlight only the most recently clicked polygon.

**Comment by davidlstarr** [comment]
@k-kresek I found a solution for the highlighting issue. 

I did the following:
- Highlighted selected polygons for analysis with a red outline
- If two polygons are selected for the analysis, it turns off the 'Add to Analysis' button
- Corrected issue when selecting a shape and adding an additional polygon to Add to Analysis. It will now remove the old selection.
- Corrected when a user deletes a shape in the polygon analysis tool

When you get an opportunity could you please do some more testing to see if the issues you were seeing are now corrected?

Here is the testing link: https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/multi-poly-work/

**Comment by k-kresek** [comment]
@davidlstarr Thank you! This looks good, I like the color distinction and after testing, this feature is working the way you described.

**Comment by k-kresek** [comment]
@davidlstarr - Just finished up with some additional testing. this feature looks good and I am ready to approve. Thank you for your work!

**Comment by davidlstarr** [comment]
@k-kresek Perfect! I will proceed and let you know once it is deployed to production.
