### ISSUE TITLE
Configuration file site feedback (Dec 2021)

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1229]
Feedback from MapBuilder team on most recent configuration file version. Please review and respond with any questions (https://gfw.jlxserver.com/configuration-form/). 

[MB_config_site_feedback_Dec2021.xlsx](https://github.com/wri/gfw-mapbuilder/files/7757472/MB_config_site_feedback_Dec2021.xlsx)

**Comment by davidlstarr** [comment]
@k-kresek Can this be closed out?
