### ISSUE TITLE
Loading problems with land cover data sets (IFLs, primary forests, aboveground woody biomass, and land cover) (6a)

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1230]
Hello! I noticed that there is an issue with multiple land cover data sets loading. I have confirmed that this is an issue on the forest atlas sites, as well as on the MapBuilder template (http://my.gfw-mapbuilder.org/v1.latest/).

Please see the attached screen recording for more details.

https://user-images.githubusercontent.com/49986590/148465370-c94412b6-4066-4113-b698-89dfab2ba87e.mp4

**Comment by davidlstarr** [comment]
@k-kresek Is there something I need to do on my end to correct the issue? You stated that this is occurring on the forest atlas sites. Do we need to reach out to them to correct the issue?

**Comment by davidlstarr** [comment]
Bug that could be impacting the land cover layers: https://gfw.atlassian.net/browse/GTC-1670

**Comment by davidlstarr** [comment]
@k-kresek It looks like Primary Forests and Land Cover is working now.

**Comment by davidlstarr** [comment]
@k-kresek I corrected the issues with the land cover layers not loading. When you get an opportunity could you please test,https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/land-cover-loading-issues/? Thanks!
