### ISSUE TITLE
Report feature timing out when report is generated for an area (6a)

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1231]
Report generation times out on the forest atlas sites, includes test sites Hay Natiora and the CMR Forest Atlas (please see screenshots). When a report is generated using a selected area, the report loads the map preview, but does not load any of the analyses.

![Screen Shot 2022-01-06 at 6 17 41 PM](https://user-images.githubusercontent.com/49986590/148466165-fab79d9b-8fb5-4e41-8182-a0a73e502303.png)
![image (1)](https://user-images.githubusercontent.com/49986590/148466206-e504cf76-a4ef-4ba4-9d66-b1b1d6666418.png)
![image](https://user-images.githubusercontent.com/49986590/148466208-a307e9b1-9cde-4ac1-a160-8f2857464ec9.png)

I tested this bug on the template (http://my.gfw-mapbuilder.org/v1.latest/) and cannot replicate it on this site. Most analyses load quickly.

**Comment by davidlstarr** [comment]
@k-kresek Is this related to the forest atlas issue with the land cover layers? Is there someone we can reach out to in order to at forest atlas to resolve the land cover layer issue?

**Comment by davidlstarr** [comment]
https://cmr.forest-atlas.org/map?l=fr
