### ISSUE TITLE
Push MyGFW Edit/Form Field to production

### ISSUE THREAD

**Issue by davidlstarr** [wri/gfw-mapbuilder#1237]
Test Link - https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/mygfw-edit/index.html

@k-kresek Let us know once you have a chance to review if this is good for us to push to production.

**Comment by davidlstarr** [comment]
@csphang MyGFW Edit/Form has been pushed to prod. When you get an opportunity could you please test and see if everything is working as intended? I appreciate it!

**Comment by davidlstarr** [comment]
@csphang I think I handled all of the edge cases. This should be good to go for final testing before we push to prod.

**Comment by csphang** [comment]
@davidlstarr confirmed with testing on incomplete account, brand new account, and an existing account. Good to push to prod.

**Comment by davidlstarr** [comment]
@csphang This is now pushed to prod. When you get chance could you do some final testing to make sure its working correctly on prod? I really appreciate it!
