### ISSUE TITLE
wip: adding rw layer datasets (config form deliverable)

### ISSUE THREAD

**Issue by davidlstarr** [wri/gfw-mapbuilder#1238]
Test Link: https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/rw-layers/

Adding RW layers to mapbuilder based on availability in here: https://docs.google.com/spreadsheets/d/176QOezPvQdWtJdi64nXqGaoHn_3bV6Muo12NdHn0UoY/edit#gid=0

This required architecting additional way to consume these layers as they dont fall into the category of existing process we are doing this for GFW API layers and custom layers in the config.

They are also opt-in layers. Meaning that users would have to enable them in their configuration file configs/resources.js enabledRWLayers array. Adding layer ids defined in the layer-config.js would do the trick and enable them in the app.

Status: need to figure out styling options.

@k-kresek Is this something you need to review to move forward with this PR?

**Comment by csphang** [comment]
@davidlstarr here is the feedback from Kai after testing these new RW layers.

- **Wind Speed Potential** - add (m/s) into legend, add selector to show wind speed potential at 50, 100 and 200 meter heights, make sure selected heights show up in legend (See RW: [https://resourcewatch.org/data/explore/ene030-Wind-Speed?section=Discover&selectedCol[…]2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1](https://resourcewatch.org/data/explore/ene030-Wind-Speed?section=Discover&selectedCollection=&zoom=3&lat=0&lng=0&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522baeaa2b1-96da-473e-86ea-2b6a9967dab9%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%25221ae1f58f-569d-4a21-9835-3e9bdd93759b%2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1))

- **NO2 data set** - Add (mol/m^2, millionths) to legend, make sure time range shows up in legend. (see RW: [https://resourcewatch.org/data/explore/Air-Quality-Measurements-TROPOMI-NO?section=Di[…]2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1](https://resourcewatch.org/data/explore/Air-Quality-Measurements-TROPOMI-NO?section=Discover&selectedCollection=&zoom=3&lat=0&lng=0&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522b75d8398-34f2-447d-832d-ea570451995a%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%252261989f1f-65af-40e7-bf45-49b27eb2b9da%2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1))

- **Dry Spells** - we wanted to have a date selector for 2020, 2050, and 2080 (dropdown), which year is currently showing, make sure year selected shows up in legend  (see RW: [https://resourcewatch.org/data/explore/cli058a-Projected-Change-in-Dry-Spells-RCP85?s[…]2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1](https://resourcewatch.org/data/explore/cli058a-Projected-Change-in-Dry-Spells-RCP85?section=Discover&selectedCollection=&zoom=3&lat=0&lng=0&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522d0f46576-411d-48aa-8df8-d89a3792cdce%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%252294529cb0-5650-453d-bcb3-b6727cf0b991%2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1))

**Comment by davidlstarr** [comment]
@k-kresek How do I go about switching between each wind speed potential? This is the url I'm using https://tiles.globalforestwatch.org/dtu_wb_wind_speed_potential_2001_2010/v20211015/default/3/1/1.png?_ts=1645550406193.

**Comment by davidlstarr** [comment]
From Kai via Slack .....

Hey David - for now we can just show the one wind speed that is showing on Resource Watch. Kristine mentioned that she will add the other two with our data engineer in the future.

**Comment by davidlstarr** [comment]
@k-kresek When you get an opportunity could you please review, https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/rw-layers/? Once approved, we can push these rw layer datasets to production! Thanks!

**Comment by davidlstarr** [comment]
Kai wanted to have the basemap layers over the rw layer dataset.

**Comment by davidlstarr** [comment]
@k-kresek This is now updated to show country labels over the rw layers. Please review https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/rw-layers/ when you get a chance. Thanks!

**Comment by k-kresek** [comment]
Thank you! This is looking good. One more note - we should add subtitles to the layers. Please see below for subtitles, and refer to other climate layers for style.

Dry Spells: (0.25°, global, 2000-2080, WRI/Vizzuality)
Air Quality: (3.5 x 5.5 km, global, 2018, TROPOMI/ESA/KNMI/DLR/SRON/BIRA-IASB/STFC/MPIC/S&T/Uni-Bremen)
Wind Speed: (1 km, global,DTU/World Bank Group/ESMAP)

*Let me know if the air quality data set subtitle is too long because of the citations. I can see if there's a way to shorten that.

**Comment by davidlstarr** [comment]
@k-kresek Do these need to be translated?

**Comment by k-kresek** [comment]
Yes, I will bundle in those translations with the next order. For now just English is okay.

**Comment by davidlstarr** [comment]
@k-kresek The sublabels have been added. Please review https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/rw-layers/ when you get a chance.
