### ISSUE TITLE
Add trees in mosaic landscapes to MapBuilder

### ISSUE THREAD

**Issue by k-kresek** [wri/gfw-mapbuilder#1242]
Here are the data URLs for the TML data set:

These are the endpoints currently used on [flagship](https://gfw.global/3sEaZCN):
tcd_0: [https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_0/{z}/{x}/{y}.png](https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_0/%7Bz%7D/%7Bx%7D/%7By%7D.png)
tcd_20: [https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_20/{z}/{x}/{y}.png](https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_20/%7Bz%7D/%7Bx%7D/%7By%7D.png)
tcd_40: [https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_40/{z}/{x}/{y}.png](https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_40/%7Bz%7D/%7Bx%7D/%7By%7D.png)
tcd_60: [https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_60/{z}/{x}/{y}.png](https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_60/%7Bz%7D/%7Bx%7D/%7By%7D.png) 
tcd_80: [https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_80/{z}/{x}/{y}.png](https://tiles.globalforestwatch.org/wri_trees_in_mosaic_landscapes/v20210930/tcd_80/%7Bz%7D/%7Bx%7D/%7By%7D.png)

For the metadata endpoint, we should use "wri_trees_in_mosaic_landscapes"

Thank you!

**Comment by davidlstarr** [comment]
Previous services that use {tcd} have a link out to an image service in the registered layer. Moving forward they are no longer using image services just the X,Y,Z tiles.  I will need to refactor the code to make this layer work as intended without the included image service.

**Comment by davidlstarr** [comment]
@k-kresek I think I have the tree mosaic layer in a good spot but I'm noticing that there are some differences in the population of the data...is there additional filtering happening? **THIS HAS BEEN CORRECTED**

![Screen Shot 2022-02-15 at 3 31 35 PM](https://user-images.githubusercontent.com/7062554/154144407-f7129d1b-87dc-48a1-a2ae-1c684eb50c44.png)

**Comment by davidlstarr** [comment]
@k-kresek Is looking into getting translations for the following:
 ['Displaying Trees in Mosaic Landscapes with', 'tree cover.']

**Comment by davidlstarr** [comment]
@k-kresek Do you think we can push this up to prod and do translations later?

**Comment by k-kresek** [comment]
@davidlstarr Yes that sounds okay to me thank you!
