### ISSUE TITLE
Ability to default set map center and zoom level through properties

### ISSUE THREAD

**Issue by palmernet** [wri/gfw-mapbuilder#196]
We have a map that we wish to embed in multiple pages on a website.  Each page represents a different region and so we want our map to be initialized to that region.  We can't use the URL parameters because we don't want to use an iframe and the underlying map gets edited (so we don't want to create multiple versions of the map, one for each web page).

**Comment by csphang** [comment]
This is planned for January/February Sprint Cycle

**Comment by richardbarad** [comment]
Hi @palmernet,

I just wanted to confirm that this feature is now available in mapbuilder!

I believe you are using the library build? If so, you will need to add the following to your configuration file:

```
  initialExtent: {
      x: null, // 
      y: null, //
      z: null, // 
    },
```
You will need to be using mapbuilder 1.3 or later to add this feature. Please feel to let us know if you need additional details!

Richard
