### ISSUE TITLE
Push code updates directly to library build

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#203]
Library build should be the default way to test and deploy  features.

**Comment by csphang** [comment]
We are going to accomplish this by updating production (the `gh-pages` branch in GitHub) via external library builds, rather than the classic `index.html`

**Comment by csphang** [comment]
Updates on the proposed deployment process: It would be good to continue to deploy new versions to the my.gfw-mapbuilder.org folder on S3. This way, users using standalone mapbuilders can point to a specific version. However, instead of adding the full code as we did in the past we would just add the index.html file and point to the appropriate version of the library build. Thomas set this up for the v1.2.2 index file which points to 1.2.2 library build. Could we replicate this for future releases?

**Comment by jenboyd** [comment]
`gh-pages` now points to library build of version 1.2.3
