### ISSUE TITLE
Confirm report fix is deployed for Monday's launch

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#205]
- [x] Report fix (cmr.forest-atlas.org/map 
http://eth.doesntexist.org/Atlas)

**Priorities for the report:**
1. Formatting - add extra margin around analyses
2. Order - analyses change depending on which one comes back first.
3. Refresh - ensure report re-loads upon browser refresh **(DONE)**
4. Sharing - permanent link so report re-hydrates when opening in new browser or sharing with someone

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/eth-exists-report/external.html

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/cameroon-report/external.html

**Comment by thomas-maschler** [comment]
@SwampGuzzler The ethiopia map uses custom analysis (none of the standard GFW analysis are activated). Please make sure the report shows the same analysis as those listed in the config file.

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/external-library-test/external.html

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/eth-report-analysis/external.html
