### ISSUE TITLE
Topographic Base Map is not showing up in some Map builders

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#210]
Hi,

We noticed that the Topographic map is not showing up in some mapbuilders. For instance, it is not showing up in Madagascar, DRC, or Cameroon.

DRC: https://cod.forest-atlas.org/map?l=fr
Madagascar: https://mdg.forest-atlas.org/map?l=fr
Cameroon: https://cmr.forest-atlas.org/map?l=fr

In the Madagascar case this is problematic because the topographic map is the default map in the ArcGIS Online web map.

Note that it is visible in the Georgia atlas. I think this might have something to do with using a different sharing host? The Georgia atlas uses a GIS Portal.

https://atlas.mepa.gov.ge/map?l=en

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad When I look at the specific Webmaps in Portal and ArcGIS Online for the Georgia Atlas and the Madagascar Atlas, respectively, I see that they simply have different basemaps. 

Our Georgia webmap data: https://gis.mepa.gov.ge/portal/sharing/rest/content/items/17656940ee284c09b65536593608a627/data

Our Madagascar webmap data:
https://www.arcgis.com/sharing/rest/content/items/190f6eb590914ad0971e0ed7456840d8/data

If you check out the `baseMap` section of each, you will see that Georgia has the proper 'Topographic' basemap, while the Madagascar has the 'WRI Contextual'

**Comment by richardbarad** [comment]
Hi @SwampGuzzler,

Thanks. However, I believe that there is still in a issue. If you change the basemap on Madagascar atlas to topographic then mapbuilder will load the topographic basemap and then switch to the WRI contextual one. I updated this on a Madagascar stage site to show you what it looks like.

http://mdg.doesntexist.org/map?l=fr

This does not happen on the Georgia site. Maybe because the Georgia map is hosted on portal? 

Also, it looks like the the Topographic basemap only shows up as an option in the Georgia mapbuilder. It is not available in the other atlases or in the base configuration. My understanding was that it should always be an available option?

http://my.gfw-mapbuilder.org/v1.3.0/
https://cod.forest-atlas.org/map
https://cmr.forest-atlas.org/map

Best,

Richard
