### ISSUE TITLE
Webmap menu and layers don't get translated when opening site in alternate language

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#214]
Translation works, when opening in primary language first and then switching to alternate language.
But when opening the alternate language via the URL hash, there is an error. Console logs "Uncaught TypeError: X.refresh is not a function"

URL for testing:
https://cmr.forest-atlas.org/map?l=en

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/cmr-updated/external.html

**Comment by richardbarad** [comment]
Thanks! It seems like the map is still not getting translated when I specify the language in the url. For example:

https://beta.blueraster.io/mapbuilder/cmr-updated/external.html?l=en

**Comment by SwampGuzzler** [comment]
@richardbarad Right you are! Apologies: check this one out instead and the update should be fine -->
https://beta.blueraster.io/mapbuilder/214-translate-layers/external.html vs https://beta.blueraster.io/mapbuilder/214-translate-layers/external.html?l=en

**Comment by richardbarad** [comment]
Hi @SwampGuzzler,

Thanks! This looks good now. I will mark it as reviewer approved.

Richard
