### ISSUE TITLE
Library build - embed all SVG and external resources in code / CSS

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#215]
Ensure that these are centrally managed

**Comment by jenboyd** [comment]
https://beta.blueraster.io/mapbuilder/215-cleanup-library-build/external.html

**Comment by csphang** [comment]
I think this may be unrelated, but I noticed running analysis on a selected polygon feature doesn't work in the English version, but does in the French

**Comment by csphang** [comment]
![2018-10-17_10-05-02](https://user-images.githubusercontent.com/13664037/47092200-7df16e80-d1f4-11e8-9681-9ab2a057acc8.png)

![2018-10-17_10-04-56](https://user-images.githubusercontent.com/13664037/47092203-83e74f80-d1f4-11e8-99ae-9493f3500917.png)
