### ISSUE TITLE
Update the url for the glad alerts in the base configuration

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#218]
We should update the url for GLAD alerts in the base configuration for mapbuilder. The updated url is copied below:

https://tiles.globalforestwatch.org/glad_prod/tiles/{z}/{x}/{y}.png

**Comment by SwampGuzzler** [comment]
http://beta.blueraster.io/mapbuilder/218-glad-url-update/external.html

**Comment by richardbarad** [comment]
Thanks! I moved this to current spring since it is being worked on. I just checked and the url looks correct in the link above.

Richard

**Comment by richardbarad** [comment]
Hi @csphang ,

Looks like this is not up to date. When I go to:

http://my.gfw-mapbuilder.org/v1.2.3/?appid=277b92455c6c49059a95c9129be7baf9

Click inspect source, and scroll down to the url for GLAD I still see the old url. This may because the version is not using the latest version of the base configuration?

Best,

Richard
