### ISSUE TITLE
GFW API: Save all layer configurations and metadata with the API

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#221]
Create new layer type which only needs a  reference to the layer’s UUID. Mapbuilder then fetches all configuration options from API and loads the layer. This will allow us to easier update layer settings for distributed applications.
Use the metadata feature from new API to retrieve metadata.

**Comment by richardbarad** [comment]
Hi @csphang and @nbumbarger 

Thomas and I reviewed the existing data-sets and layers in the API, and it looks some of the layer specs are very applications specific. However, we can have multiple layers referencing the same dataset. 

Attached is an Excel sheet indicating which datasets used in mapbuilder are already registered with the API. For the ones marked as yes, we thought we could reuse the existing the dataset and create our own layer with a mapbuilder config and register the layer to ` “app”:[”forest-atlas”] `. For the ones marked as no, we will need register a new dataset and also register a layer with a mapbuilder configuration to the dataset.

Also, we noticed that some of the layers include an analysis configuration. Do you think we could use this to centrally manage analysis and simplify the analysis module? Perhaps, the analysis module could pull the analysis configuration from the API using the same unique ID as the layer. The catch is that some layers have multiple related analysis as shown below. Happy to chat in further detail if needed.

[Mapbuilder_Layers_API_Final.xlsx](https://github.com/wri/gfw-mapbuilder/files/2563720/Mapbuilder_Layers_API_Final.xlsx)


**Tree Cover Loss:** 
- Tree Cover Loss / Gain Analysis
- Tree Cover Loss Analysis

**Above Ground Liver Woody Biomass Density:**
- Aboveground Live Woody Biomass Density Analysis

**Intact Forest Landscape:**
- Intact Forest Landscape Analysis

**Glad Alerts:**
- Glad Alert Analysis

**FORMA Alerts:**
- Forma Alert Analysis

**Terra-I Alerts**
Terra-I Alerts Analysis

**VIIRS Active Fires**
VIIRS Active Fires Analysis

**Land Cover Composition**
Land Cover Composition Analysis
Tree Cover Loss by Land Cover type (we will add this analysis when we switch to vega),
