### ISSUE TITLE
Metadata coming from ArcGIS Online web maps is not working

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#229]
The metadata coming from ArcGIS Online webmaps are not working in the latest version of mapbuilder. For examples, please see the forest atlases at the links below. 

https://cog.forest-atlas.org/map?l=fr
https://cod.forest-atlas.org/map?l=fr
https://www.tierrasindigenas.org/Mapa

I believe this issue may have been caused by the updates made to allow metadata from ArcGIS Portal as seen on assembla here: https://app.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=816

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/229-metadata/external.html
