### ISSUE TITLE
Report - land cover layers are rendering on top of the users' feature layers

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#231]
Tested on https://beta.blueraster.io/mapbuilder/215-cleanup-library-build/external.html

To recreate:
------
1. Turn on Aboveground Woody Biomass
2. Zoom into map, select a polygon
3. Print report > notice the report map renders layers differently than as seen on the app's map.

Screenshots:
------
![2018-10-17_12-05-52](https://user-images.githubusercontent.com/13664037/47100334-3f17e480-d205-11e8-8c4b-73ca9ddab220.png)

![2018-10-17_12-05-09](https://user-images.githubusercontent.com/13664037/47100340-4212d500-d205-11e8-8a18-70ed89af7f90.png)

**Comment by SwampGuzzler** [comment]
see https://beta.blueraster.io/mapbuilder/215-cleanup-library-build/external.html

**Comment by jenboyd** [comment]
New build to fix this can be tested at: http://beta.blueraster.io/mapbuilder/231-report-layer-order/external.html

**Comment by csphang** [comment]
Tested and verified as fixed on http://beta.blueraster.io/mapbuilder/231-report-layer-order/external.html

![2018-10-22_12-14-34](https://user-images.githubusercontent.com/13664037/47304363-651dfa00-d5f4-11e8-9b0a-dab8f1a556dc.png)
