### ISSUE TITLE
Check spelling for alternate languages - special characters - parsing

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#233]
Overview:
------
Special characters are not displaying as expected in the app (especially Spanish and French). May need to look into parsing the characters differently.

To recreate:
------

1. Load https://beta.blueraster.io/mapbuilder/215-cleanup-library-build/external.html
2. Look in the info menu tab > First sentence has special characters
3. View the page source > Note the special characters in here are not displaying as expected.

Screenshots:
------
![2018-10-17_12-14-27](https://user-images.githubusercontent.com/13664037/47100936-b601ad00-d206-11e8-9c92-68700ca8e848.png)

![2018-10-17_12-15-34](https://user-images.githubusercontent.com/13664037/47100939-b9953400-d206-11e8-88a2-176dcc95a849.png)

**Comment by richardbarad** [comment]
Hi @csphang,

Moving this to sprint 1. We should try to address it before we release the 1.2.3 version. It seems like this is only an issue when using the index. html file. Special characters on sites using the library build work as expected.

Best,

Richard

**Comment by csphang** [comment]
Tested and confirmed. @richardbarad This is ready for your final review at https://beta.blueraster.io/mapbuilder/233-alt-language-chars/external.html

**Comment by richardbarad** [comment]
Thanks @csphang. Looks good. Please go ahead an mer
