### ISSUE TITLE
Analysis -- Unable to select a shape after changing languages

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#234]
Occurring when loading the alternate language via URL hash, as well as when toggling in the app to alt lang.

To Recreate:
------

1. Load https://beta.blueraster.io/mapbuilder/215-cleanup-library-build/external.html
2. Switch language to **English**
3. Try to select a shape to run analysis > Note all polygons are unclickable!

Screenshots:
------
![2018-10-17_12-23-42](https://user-images.githubusercontent.com/13664037/47101358-d41bdd00-d207-11e8-8861-0020bfaf8297.png)

![2018-10-17_12-25-27](https://user-images.githubusercontent.com/13664037/47101362-d7af6400-d207-11e8-9b84-81d338684edf.png)

**Comment by jenboyd** [comment]
@csphang Looks like this is an issue with the english version of the webmap. The popups aren't enabled there when you load the webmap directly.
