### ISSUE TITLE
Hide the enlarged svg icons on page-load

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#238]
The external builds display their `svg` icons on page load or refresh for a split second before our css kicks in and they are normalized and put in their place.

We need to do one of these:

- have some inline css to keep their size down onLoad
- make their `display: none;` by default and change that on pageLoad

**Comment by richardbarad** [comment]
@SwampGuzzler & @csphang . I think this issue was already addressed? Can you confirm? If yes, lets close it.

**Comment by richardbarad** [comment]
This seems to be complete already! Closing it.
