### ISSUE TITLE
Update url for Mangrove Forest Layer

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#241]
Migrating this ticket from Assembla. Looks like it might have gotten overlooked when we switched to using github.

https://app.assembla.com/spaces/WRI_Forest_Atlas/tickets/realtime_list?ticket=823

The location of the mangrove layer has changed. Can we please update it?

Here is the json configuration for the new layer:

`{
					"order": 1,
					"id": "GLOB_MANGROVE",
					"type": "webtiled",
					"url":"https://cartocdn-gusc.global.ssl.fastly.net/wri-01/api/v1/map/d1567282c7f1c14771faf723c39d677a:1529255467465/0/{level}/{col}/{row}.png",
					"technicalName": "global_mangroves_gmw",
					"legendLayer": 11,
				"label": {
						"en": "Mangrove Forest",
						"fr": "Mangrove Forest",
						"es": "Mangrove Forest",
						"pt": "Mangrove Forest",
						"id": "Mangrove Forest",
						"zh": "Mangrove Forest"
					}
					}`

**Comment by richardbarad** [comment]
Hi @csphang and @SwampGuzzler,

Quick question on this!

I realized I think I might be able to update this myself, by updating the layer in the layer panel in the external and internal html files. Would this need to be updated anywhere else? We have already updated the layer in our CMS applications that use the mangrove layer.

Many thanks!

Best,

Richard

**Comment by richardbarad** [comment]
@csphang and @SwampGuzzler,

Can we work on this as part of Sprint 5? 

Here is the dataset/layer in the API used by GFW: 

https://production-api.globalforestwatch.org/dataset/bd5d7924-611e-4302-9185-8054acb0b44b

GFW has a toggle to switch between different layers. In mapbuilder I suggest we just use the most recent (2016) layer which is below.

https://production-api.globalforestwatch.org/dataset/bd5d7924-611e-4302-9185-8054acb0b44b/layer/90ca1154-72e1-4667-852b-03bad0a4c013

GFW hosts this data on Carto. Is this compatible with mapbuilder? If not let me know and I can get it hosted one of our ESRI servers.

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad This is not currently compatible with Mapbuilder, as we need a way to determine what URL suffixes go with each tile request. An example:

This [URL](https://cartocdn-gusc.global.ssl.fastly.net/wri-01/api/v1/map/d1567282c7f1c14771faf723c39d677a:1529255467465/0/4/9/8.png) works fine, but this [URL](https://cartocdn-gusc.global.ssl.fastly.net/wri-01/api/v1/map/d1567282c7f1c14771faf723c39d677a:1529255467465/0/4/9/9.png) (just one row to the west) somehow requires a different suffix. The 2nd url works with a different [suffix](https://cartocdn-gusc.global.ssl.fastly.net/wri-01/api/v1/map/4a726d576ff98af2cdfb94709a05be0f:1529255467465/0/4/9/9.png) which is not referenced in the ticket or issue. I need some way for the layer to know which suffix will be used for which request. This pattern is repeatable on the flagship site for this layer's requests.

**Comment by richardbarad** [comment]
@SwampGuzzler.

Thanks! I will pass this request along to the flagship / data team and let you know what I hear.

Richard

**Comment by richardbarad** [comment]
Hi @SwampGuzzler and @csphang,

Here are the notes from the Vizzuality team. I am also concurrently looking into getting this hosted on our ESRI GIS Server. I believe Ifeoma might have reached out to BR for support with this (not sure who). 

**From Vizz:**

Here is the dataset + layers controlling the mangrove data on the GFW flagship site:

https://production-api.globalforestwatch.org/dataset/bd5d7924-611e-4302-918…

You will see there are many layers attached to this dataset, as we have one layer for every year of absolute data, and one layer for every year of delta (change) data.

We are using this layer config data to call the Carto Maps API.

The settings for the user settings (year, and absolute/change) are also specified in the layer configs.

So for each layer you want to visualise you will need to take the cartocss and sql and send them to the Carto maps api and use the response to obtain the z/x/y web map tile url to pass to your map library.

Let me know if you have any doubts or further questions.

**Comment by richardbarad** [comment]
Hi @SwampGuzzler @csphang 

The latest mangrove data is now published as a map service: http://gis-gfw.wri.org/arcgis/rest/services/cached/mangroves_2016_cached/MapServer

I have added the new layer configuration to the API as well: http://production-api.globalforestwatch.org/layer/533cbe18-22a6-46ac-99ca-027c96f33ac3

I am adding the layer to the 1.3.3 Index HTML file.
