### ISSUE TITLE
Webmap hosted on portal pulls web map service metadata instead of layer metadata.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#244]
For webmaps hosted on Portal which contain webmap services, the metadata is getting pulled from the webmap service instead of the layer. For an example, see the two Georgia applications shown below. The first is our stage application and points to the 1.2.3 version of map builder. The 2nd is our live application and points to the 1.2 (1.2.2) version of mapbuilder.

When you click on the metadata for a layer in the land use tab you will see that the stage site shows the metadata for the webmap service, while the live site shows the metadata for the specific layer. I am also attaching screenshoots.

http://geo2.doesntexist.org/map (1.2.3 - stage site)
https://atlas.mepa.gov.ge/map (1.2 - live site)
![stagesite](https://user-images.githubusercontent.com/40440743/47376678-3f125b80-d6c1-11e8-8a6c-72aade7bfecc.png)
![livesite](https://user-images.githubusercontent.com/40440743/47376679-3f125b80-d6c1-11e8-9161-99dc51f23c51.png)

**Comment by SwampGuzzler** [comment]
@richardbarad  Gotcha, I just pushed that fix to this url: https://beta.blueraster.io/mapbuilder/219-portal-metadata/external.html?l=en

**Comment by richardbarad** [comment]
Looks good @SwampGuzzler! 

Please go ahead and merge into 1.2.3.
