### ISSUE TITLE
Enable users to embed a MapBuilder report inside their own website

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#246]
The idea here is that users would be able to open the report page inside their own websites. This task is tied to the CMS development. WRI is working to create a form to let users build mapbuilders in the CMS and allow them to embed mapbuilder reports in CMS sites. For instance, the report page could be opened up inside of the forest atlases. Maybe we could specify the appropriate url inside the configuration file?

**Comment by csphang** [comment]
CMS question for this:
1. How will the report live inside of the CMS? As its own seperate "Report" Type similar to the Map? As a static html file?
2. Can the report share the Map's "Map Settings" object somehow?
3. How can we deploy new versions of the report.html to other Sites handled by the CMS?
4. What will the URL of the report be? "SiteURL/map/report.html"? "SiteURL/report/"?

**Comment by csphang** [comment]
Answers from Vizz team:
1. The report will live as a separate page. We were thinking it could work as the map: there would be an URL from where we would load the JS (like //wri-sites.s3.amazonaws.com/gfw-mapbuilder.org/library.gfw-mapbuilder.org/xxx.js) and we would then instantiate this library. You could directly read the parameters the report page receives from the URL.

2. If you mean that the report page has access to the same map config the map builder does, that isn't a problem. The report "library" could receive a `config` param when it's instantiated (like MapBuilder).

3. The version of the library would be located in the URL so the admin of the CMS sites should be able to pick which version they want.

4. Maybe it could be a good idea to have another parameter to the `MapBuilder` library where we could specify the URL of the report page (relative or absolute, as you wish). This way the code stays flexible in case we want to change the URL of the report.

**Comment by csphang** [comment]
Versioning to be handled via the folder structure rather than the file name.

**Comment by jenboyd** [comment]
@csphang @SwampGuzzler Link below to new build with externalReport.html that points to versioned js file. This html still uses the url params and not the config. We can integrate this next week and test with the CMS once that page type has been added!

http://alpha.blueraster.io/gfw-mapbuilder/246-report-external-html/external.html

Report HTML: 
http://alpha.blueraster.io/gfw-mapbuilder/246-report-external-html/externalReport.html

JS file: 
http://alpha.blueraster.io/gfw-mapbuilder/246-report-external-build/reportLib.1.4.0.js

**Comment by richardbarad** [comment]
Hi @csphang and @jenboyd,

Could you confirm if this javascript file is available to the public? If so, can Vizz. start using it for testing and developing the report page in the CMS or should we wait till it is deployed to S3?

Best,

Richard

**Comment by jenboyd** [comment]
@richardbarad, sorry I am just getting back to you. I was hoping to get uploaded today, but we are still working on some internal testing to make sure the constructor params for the report are working as expected. We should be able to get it on S3 sometime tomorrow!

**Comment by jenboyd** [comment]
@richardbarad The updates are up on S3 in the following locations:

index.html & report.html files located here. Report.html now includes a new custom MapBuilderReport constructor which accepts the same config file as the map.
https://my.gfw-mapbuilder.org/v1.4.0_test/


The html files point to the js files located here:
https://library.gfw-mapbuilder.org/sprint2/1.4.0.js
https://library.gfw-mapbuilder.org/sprint2/reportLib.1.4.0.js

**Comment by richardbarad** [comment]
Thanks @jenboyd !

I'll pass this along to Vizzuality to use for testing!

**Comment by richardbarad** [comment]
@csphang Moving this to a sprint 4 (v1.4.0)

Sorry for the delay here! We are trying to get out a new version of the CMS and this did not make it into the current release. I plan to put it into the next CMS release so hopefully we can that release to allign with the mapbuilder release of 1.4.0.

Richard

**Comment by richardbarad** [comment]
As discussed, I am removing the hold. 

We should deploy a new version which this update in which the report pull request is merged in with a newer version of mapbuilder and the link to the report .js file is updated accordingly.

**Comment by csphang** [comment]
@richardbarad Where can we find this html file? http://blueraster.teaches-yoga.com/CMR/report.html

We're trying to trace the `Sprint2` in the URL issue, but we are having trouble identifying where this report.html from the CMS lives. The report.html file located in wri-sites/gfw-mapbuilder.org/my.gfw-mapbuilder.org/v1.4.0 doesn't reference Sprint2, so we are wondering if the source is elsewhere?

**Comment by richardbarad** [comment]
@csphang. Checking with Vizz! Maybe it is something they need to fix on their side to account for the re-organization of the file structure.

**Comment by richardbarad** [comment]
@csphang and @KaylaKremer and @SwampGuzzler,

The fix was deployed to the CMS staging site so the report should load now! 

For future reference here is where the CMS report lives: https://github.com/Vizzuality/forest-atlas-landscape-cms/blob/develop/app/views/site_page/map_report.html.erb

I am noticing that report seems to load default analysis instead of the user specified analysis in the configuration file. Something you need to fix on your side?

**Comment by csphang** [comment]
@richardbarad Can you point us to a CMS mapbuilder app that has the report embedded within the CMS? We were looking at a few examples but all of them had the report opening externally.

**Comment by richardbarad** [comment]
@csphang. Any app which points to `v1.4.0` of mapbuilder should work. 

Here is an example from the BR site which points to `v1.4.0`: http://blueraster.teaches-yoga.com/CMR?l=fr

Here is the report, it opens up inside the atlas but does not show the correct analysis. http://blueraster.teaches-yoga.com/CMR/report.html?title=Blue%20Raster%20Site&subtitle=Minist%C3%A8re%20des%20For%C3%AAts%20et%20de%20la%20Faune&logoUrl=https%3A%2F%2Fcmr.forest-atlas.org%2Fsystem%2Fsite_settings%2Fimages%2F000%2F000%2F094%2Foriginal%2FCAMEROON.png%3F1487267590&logoLinkUrl=http%3A%2F%2Fwww.minfof.cm%2F&activeSlopeClass=undefined&webmap=6142e76453354c0b83633370e6a6f006%20&idvalue=926ca5dda57087b7442834ef99ebc0f8&tcd=30&lang=fr&activeLayers=USER_FEATURES%2Catlas_forestier_fr_3504_73%2Catlas_forestier_fr_3504_70%2Catlas_forestier_fr_3504_69%2Catlas_forestier_fr_3504_68%2Catlas_forestier_fr_3504_65%2Catlas_forestier_fr_3504_67%2Catlas_forestier_fr_3504_66%2Catlas_forestier_fr_3504_61&tcLossFrom=0&tcLossTo=16&gladFrom=2015-01-01T05%3A00%3A00.000Z&gladTo=2019-05-14T18%3A08%3A36.423Z&terraIFrom=2004-01-01&terraITo=2016-08-12&viirsStartDate=2019-05-13%2014%3A08%3A36&viirsEndDate=2019-05-14%2014%3A08%3A36&modisStartDate=2019-05-13%2014%3A08%3A36&modisEndDate=2019-05-14%2014%3A08%3A36&customFeatureTitle=Custom%20Feature%20%231&atlas_forestier_fr_3504=63%2C59%2C61%2C66%2C67%2C65%2C68%2C69%2C70%2C71%2C73%2C74&cache=1.4.0&origin=http%3A%2F%2Fblueraster.teaches-yoga.com

**Comment by SwampGuzzler** [comment]
@SwampGuzzler The above `blueraster.teaches-yoga...` has some kind of `window` object attached to it that has those 8 generic (and incorrect) **analysisModules** attached to it! --> `gon.page.content.settings`

**Comment by SwampGuzzler** [comment]
@SwampGuzzler This may actually be fixed now --> Check out https://my.gfw-mapbuilder.org/v1.latest/ and let's confirm that the `report` page does have the proper `analysis` charts per what we'd expect from our default `analysisModules`!

**Comment by SwampGuzzler** [comment]
@richardbarad Is this actually fixed? I am seeing the same analysis charts in the report page generated by https://my.gfw-mapbuilder.org/v1.latest/ as I am in the Map's analysis dropdown options

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks like the issue with the wrong analysis charts showing up is not an issue v1.latest. However, it is still an issue when using the `v.1.4.js` report file. 

Can we integrate the report updates to use the `.js ` and see if that fixes the issue? I would like to try to close out this task in this sprint so that the report can open up inside the CMS starting at `v1.4`.

**Comment by SwampGuzzler** [comment]
@richardbarad I will look at doing just that this afternoon! Thanks for the direction!

**Comment by csphang** [comment]
See Cameroon for testing: http://blueraster.teaches-yoga.com/CMR?l=fr

**Comment by SwampGuzzler** [comment]
Awesome. Fixed and test-able at https://my.gfw-mapbuilder.org/v1.4.0/ and http://blueraster.teaches-yoga.com/CMR?l=en

**Comment by richardbarad** [comment]
@SwampGuzzler.

I tested this out in a few applications, and it looks like the report is now always showing **the default Vega analysis**, and not the analysis specified in the configuration file. 

For example, if I:
1) Load app: http://blueraster.teaches-yoga.com/CMR?l=fr
2) Draw a custom shape:
3) Analyze > Land Cover Composition > Print Report

The report will show VEGA analysis. However, the configuration has not been updated to use the new module so it should still show the old analysis.

Similarly, I updated the Ethiopia configuration on the Blue Raster site to point to 1.4 and it shows the default vega analysis and not the custom restoration analysis in the report: http://blueraster.teaches-yoga.com/ETH?l=en. 

Additionally, the report is not loading inside of the CMS like it did in the previous 1.4 build. Are we not yet using the `.js` file at `https://library.gfw-mapbuilder.org/reportLib.1.4.0.js` to load the report?

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad You are right of course - I finally updated the Latest `1.4.0` library to use the proper **reportLib.1.4.0.js** and the Ethiopia Forest Atlas is now showing its custom restoration atlas analyses _within_ the report in the CMS.

**Comment by richardbarad** [comment]
@SwampGuzzler. This is approved after testing in the CMS on several sites on http://blueraster.teaches-yoga.com
