### ISSUE TITLE
Re-locate `resources.js` and `report.html` into the 'version' folder of each new build

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#249]
Example: for an older version, `1.2.2`, we had a file structure of: 

index.html
report.html
resources.js

1.2.2.js
/1.2.2
--    /js
--    /css

But for this next release (either `1.2.3` or event `1.3.0`):

index.html

1.2.3.js
/1.2.3
--    report.html
--    resources.js
--    /js
--    /css

**Comment by jenboyd** [comment]
@csphang 

Test library build file locations and functionality here: http://beta.blueraster.io/mapbuilder/249-update-pathing/lib-build/external.html

Test and make sure regular build process still works as expected: http://beta.blueraster.io/mapbuilder/249-update-pathing/build/
