### ISSUE TITLE
ArcGIS Online items with full metadata only show description

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#253]
In the new version of mapbuilder (1.3.0), feature service layers which have full metadata do not show the full metadata. Only the description is visible. ArcGIS Online Feature Services should show full/extended metadata when it is available. 

For an example, click on the metadata button for the ArcGIS online items with full metadata to see the difference between how metadata in displayed for items with full metadata in 1.3.0 and 1.2.1 versions of mapbuilder.

http://my.gfw-mapbuilder.org/v1.3.0/?appid=277b92455c6c49059a95c9129be7baf9

http://my.gfw-mapbuilder.org/v1.2.1/?appid=277b92455c6c49059a95c9129be7baf9

Can we implement a fix for 1.3.1?

Richard

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/253-metadata/external.html?appid=277b92455c6c49059a95c9129be7baf9

**Comment by csphang** [comment]
![2018-11-06_14-20-49](https://user-images.githubusercontent.com/13664037/48088149-33e62200-e1cf-11e8-9745-c326deabb410.png)

**Comment by csphang** [comment]
Ready for review at: https://beta.blueraster.io/mapbuilder/253-metadata/external.html?appid=277b92455c6c49059a95c9129be7baf9
