### ISSUE TITLE
Show error message in case analysis fails

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#261]
Display a loading wheel in the analysis panel to let users know the analysis is running. If the analysis fails, display an error message so the user knows.

**Comment by jenboyd** [comment]
@csphang Looks like the main issue was with the Vega widgets. Fix can be tested here: http://alpha.blueraster.io/gfw-mapbuilder/261-analysis-error-handling/external.html

Two potential errors, let me know what we want the messaging to be

 - 500 error from the GFW API
<img width="1436" alt="screen shot 2018-12-05 at 3 16 35 pm" src="https://user-images.githubusercontent.com/19177290/49541590-322c7e80-f8a1-11e8-8464-fc0c67335196.png">

- No values returned, so chart would be empty
<img width="1438" alt="screen shot 2018-12-05 at 3 16 58 pm" src="https://user-images.githubusercontent.com/19177290/49541689-8d5e7100-f8a1-11e8-934d-32b4beff8a01.png">
