### ISSUE TITLE
Add primary forest layer

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#262]
Include the primary forest layer in the base configuration. Add a Boolean clause to the config file so users can choose to show or hide the layer.

**Comment by richardbarad** [comment]
Here is the primary forest dataset in the API:

http://api.resourcewatch.org/dataset/714339c1-c775-4303-aad4-16d975b2f023

**Comment by richardbarad** [comment]
@SwampGuzzler. Please include primary forest in the land cover section!

**Comment by SwampGuzzler** [comment]
@richardbarad Will do!

**Comment by SwampGuzzler** [comment]
@richardbarad Updated!

Also --> we'll get the proper legend symbol for this automatically once @nbumbarger 's new layer registration config gets added to the production `gfw-api`

**Comment by richardbarad** [comment]
Hi @SwampGuzzler,

Can we please put primary forest as 2nd in the layer order under intact forest landscape? Also, can we make sure we add a true/false parameter to turn the layer on and off? We noticed that this was missing for forma so it would be great if you could add it for forma as well.

Best,

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad Back to you with those changes!
