### ISSUE TITLE
GFW API: Pull legend information from API instead of legend service

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#265]
ETA for delivery end of week, Friday 11/9.

- Alternate Language Support (use same languages as currently supported in resources)
- Support for different types (gradient, chloropleth, points & polys, lines)

**Comment by csphang** [comment]
Waiting for examples of legend types: @thomas-maschler

**Comment by richardbarad** [comment]
Hi @csphang,

Below are the legend types/specs from @thomas-maschler 

There are only a couple of base types. I also found some other styles like cluster, rect and marks, but I think they are exotic and we won’t need them)

Polygon and Points (we could create a new “point” style if needed)
```
{
                "items": [{
                                                "dataMaxZoom": 12, //control zoom level
                                                "threshold": 30, // optional - loss specific tag to show TCD threshold 
                                                "color": "#DC6C9A",
                                                "name": "Tree cover loss",
                                                "source": "(annual, 30m, global, Hansen/UMD/Google/USGS/NASA)", // optional
                                                "notes": [                                                                                                             // optional
                                                                "Displaying loss with {thresh} canopy density.",
                                                                "Tree cover loss is not always deforestation."
                                                ]
                                }
                ],
                "type": "basic"
}
   {
                "type": "lines",
                "items": [{
                                                "name": "H5",
                                                "value": "H5", //not sure what this is good for
                                                "color": "#6A1ED2",
                                                "lineType": "dash"
                                }, {
                                                "name": "H4",
                                                "value": "H4",
                                                "color": "#DC14DC",
                                                "lineType": "dash"
                                },
{…}
                ]
   }
```

Gradient 
  ```
 {
                "items": [{
                                                "color": "#895122",
                                                "value": "0"
                                }, {
                                                "color": "#957F4F",
                                                "name": ""
                                }, {
                                                "color": "#9DB38A",
                                                "name": ""
                                }, {
                                                "color": "#39A401",
                                                "value": "480 Mg Ha⁻¹"
                                }
                ],
                "type": "gradient"
   }
```

Choropleth (distinct colors for values, but display like gradient)
  ```
{
                "items": [{
                                                "color": "#ffffb2",
                                                "name": "<300"
                                }, {
                                                "color": "#fecc5c",
                                                "name": "<325"
                                }, {
                                                "color": "#fd8d3c",
                                                "name": "<350"
                                }, {
                                                "color": "#f03b20",
                                                "name": "<375"
                                }, {
                                                "color": "#bd0026",
                                                "name": "<505"
                                }
                ],
                "type": "choropleth"
  }
```

Groups
```
  {
                "type": "group",
                "items": [{
                                                "name": "Cereals",
                                                "color": "#d95997",
                                                "items": [{
                                                                                "name": "Barley",
                                                                                "color": "#531332"
                                                                }, 
{…}
                                                ]
                                }, {
                                                "name": "Pulses and legumes",
                                                "color": "#1230a5",
                                                "items": [{…}]
                                }, {…}
                ]
    }
```

**Comment by csphang** [comment]
@thomas-maschler @richardbarad This is more involved than we initially anticipated. It requires rewriting more pieces of our legend logic than we initially thought, so we expect this feature to be ready closer to next Wednesday. Please let us know if you want to hold on the release until this is in.

**Comment by richardbarad** [comment]
Hi @csphang 

That is fine with me. Please go ahead an push back the release date.

**Comment by nbumbarger** [comment]
I deployed a preview build of the API-driven legends to http://alpha.blueraster.io/gfw-mapbuilder/api-legends-demo/. Each type is enumerated under the "API LEGEND TEST" layer dropdown.

The actual map data isn't related to the legends- this is just a test of the legendConfig API. You can take a look at the layers registered in the API to see exactly how they were configured:

- Basic: [1ec41dce-99be-4c6f-bbd3-aa37a2e28a42](http://api.resourcewatch.org/v1/dataset/098b33df-6871-4e53-a5ff-b56a7d989f9a/layer/1ec41dce-99be-4c6f-bbd3-aa37a2e28a42)
- Points: [946fd989-1678-41f8-91cc-dfdaac494507](http://api.resourcewatch.org/v1/dataset/098b33df-6871-4e53-a5ff-b56a7d989f9a/layer/946fd989-1678-41f8-91cc-dfdaac494507)
- Lines: [840cf0cd-c7db-42db-9bf0-a3a700c79255](http://api.resourcewatch.org/v1/dataset/098b33df-6871-4e53-a5ff-b56a7d989f9a/layer/840cf0cd-c7db-42db-9bf0-a3a700c79255)
- Choropleth: [67d742f7-e1a3-4d17-971d-29fe18b06cf5](http://api.resourcewatch.org/v1/dataset/098b33df-6871-4e53-a5ff-b56a7d989f9a/layer/67d742f7-e1a3-4d17-971d-29fe18b06cf5)
- Gradient: [ed76a7d1-50de-4f8d-8015-b20a65349292](http://api.resourcewatch.org/v1/dataset/098b33df-6871-4e53-a5ff-b56a7d989f9a/layer/ed76a7d1-50de-4f8d-8015-b20a65349292)
- Group: [7ac94f47-5541-4e89-83f7-8e566ab80a98](http://api.resourcewatch.org/v1/dataset/098b33df-6871-4e53-a5ff-b56a7d989f9a/layer/7ac94f47-5541-4e89-83f7-8e566ab80a98)

**Comment by richardbarad** [comment]
This looks great @nbumbarger! It will be great to manage legends through the API, and have support for multiple languages. For now, we can use the current English text for all mapbuilder languages. I'll follow up with our country teams to work on translating the legends and can update the API layers once we get the translations. 

I realize these are just test layers. When you register the final layers please register them to the forest-atlas app instead of gfw. Thanks!

Best,

Richard

**Comment by richardbarad** [comment]
Hi @csphang and @nbumbarger 

One small comment here. I suggest we match the width of the squares to the width of the square legends coming from ESRI Services so that the width and height match when we have mix of legends coming from the API and legends coming from ESRI Services.

Richard

**Comment by csphang** [comment]
@nbumbarger It looks like the Esri legend squares have a width and height of 15px. Can we reduce our current squares from 17px to 15px to match the legends from Esri Services?

![2018-11-14_11-16-15](https://user-images.githubusercontent.com/13664037/48495853-d5d4c280-e7fe-11e8-9b1b-622845de6af8.png)

**Comment by richardbarad** [comment]
Hi @csphang and @nbumbarger,

I did a little more digging on this and noted that the legends coming from the legend service as 15 x 15 px, while other ESRI legends are 20 x 20px. I suggest we match to the size of the larger ones since the API legends will replace the ones coming from the legend service.

Richard
