### ISSUE TITLE
Mobile: Confirm line of code is included in release to render the mobile design for devices

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#288]
![2018-12-11_13-39-21](https://user-images.githubusercontent.com/13664037/49822206-76f56100-fd4a-11e8-8d36-c1ef2fc013db.png)

![screenshot_20181211-133143](https://user-images.githubusercontent.com/13664037/49822219-84125000-fd4a-11e8-8764-ea7ac8f1b94b.png)

**Comment by jenboyd** [comment]
@csphang This should be fixed now on this link: http://alpha.blueraster.io/gfw-mapbuilder/255-satellite-imagery/external.html
