### ISSUE TITLE
Allow for hitting external API's for vega widgets

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#291]
Port functionality into core MapBuilder

Example API Call: 
https://measures.wcs.org/DesktopModules/WCSVega/API/Data/MapBuilderVegaSQL?geostore=19cbd20c0c5a6244a882b4fb88068968

Example constructor:
https://chilp.it/5313295

**Comment by jenboyd** [comment]
Reference changes made for WCS here: https://github.com/wri/gfw-mapbuilder/compare/chart-api...wcs-one-off

Make sure WCS functionality can be accommodated by the change so we can upgrade WCS to use next mapbuilder version.

**Comment by SwampGuzzler** [comment]
@KaylaKremer This one is all yours! Let's talk and get you some examples of some 3rd-party API calls to test this out on!

**Comment by KaylaKremer** [comment]
@csphang Can you list any 3rd-party API calls you have here so I can test them out?

**Comment by csphang** [comment]
@KaylaKremer Here's an example call that includes the geostore for the geometry:
https://measures.wcs.org/DesktopModules/WCSVega/API/Data/MapBuilderVegaSQL?geostore=19cbd20c0c5a6244a882b4fb88068968

**Comment by KaylaKremer** [comment]
@csphang Thank you!

**Comment by richardbarad** [comment]
@csphang, @SwampGuzzler, @KaylaKremer,

As discussed yesterday here are some examples of query API calls to some tabular datasets in our API which use SQL. The queries support querying feature services, Carto table, CSVs, and Json using SQL. For feature services, the API includes a service which converts the SQL to an ArcGIS Feature Service query.

- `https://production-api.globalforestwatch.org/query/edbecb09-2a06-4120-bcd3-a62d1c83b560?sql=SELECT Region, Loss, Year FROM table`

- `https://production-api.globalforestwatch.org/query/6abd5b26-68f5-4b93-9471-9722204569c7?sql=SELECT Region_KA as x, SUM(Area_pa_ha) as y FROM dashboardsPa_by_regionMapServer0  GROUP BY  x ORDER BY y`

I do not have a clear use case for this, but I guess the ideal situation would to be able to pass a Where clause to the query based on the shape selected in the mapbuilder. I am not sure how well this aligns with the structure of Johnathon's API but it would be great to accommodate if it is a low hanging fruit.

**Comment by csphang** [comment]
Hold on this until tickets #286 and #299 are completed.

@richardbarad The SQL queries are not exactly the same as WCS' use case, but we can support it if it's needed.

**Comment by richardbarad** [comment]
@csphang. Let's prioritize the WCS use case since we do not have a clear use case for the above right now and consider adding it in once we have a clearer use case.

**Comment by richardbarad** [comment]
Putting this on hold back into backlog, till we further flesh out the needs from the WCS API. BR working with Johnathon on a fork at this build: https://measures.wcs.org/beta/map

**Comment by vaidotasp** [comment]
was fixed during the recent work.
