### ISSUE TITLE
Layers are not rending in the correct order - feature service

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#294]
Hi Christina,

I am noticing a difference in behavior for how mapbuilder handles feature and map service layers coming from the webmap. Ideally, I think we should handle both layer service types in the same way if they are in the webmap. Feel free to let me know if these differences were intentional.

There appear to be two issues:

1) Map service layers coming from the web map do not default to 60% transparent, while feature service layers do.

2) If you have a feature layers there appears to be an error in the rending error. Specifically, the layers in the tree cover dynamics group are rendered below the layers coming from the webmap group. 

Here are links to two different applications where this difference is visible:

MapService: https://cod.forest-atlas.org/map
FeatureService: https://www.tierrasindigenas.org/Mapa

Below is a screenshot where we see that the feature services from the webmap are rendering on top of the tree cover loss data, as noted in issue 1. 

![featureservice](https://user-images.githubusercontent.com/40440743/50491608-26843180-09e1-11e9-9a93-db7b47c99794.png)

**Comment by vaidotasp** [comment]
was fixed during the recent work.
