### ISSUE TITLE
Vega Support multiple languages

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#299]
As part of the work to make [vega the default](https://github.com/wri/gfw-mapbuilder/issues/286) we should support rendering vega widgets in the different languages supported by mapbuilder. 

I see two options here:

1) We can maintain separate widgets for each language all registered to the same API layer, and specify the widgets for the different languages in the configuration. 

2) We can have one widget supporting multiple languages with a [signal](https://vega.github.io/vega/docs/signals/) that specifies the language. I tested this out and was able to created a signal with a toggle to specify the language. When you change the language the x axis label changes.

Here is a gist I put together: https://gist.github.com/richardbarad/eb8050ff12bcecd1bb1f5b793dc1129e

Do you think it would be possible for mapbuilder to pass a language value to the signal in the vega? If we go with the 2nd approach we would also need to figure out a way to hide the signal in the vega visualization (either on the mapbuilder side, or in the vega itself). The 2nd option is preferable since we would need to maintain only one widget in the API instead of one for each language. However, if it seems like it would require a high amount of LOE to implement we can stick with the 1st option.

Feel free to let me know if you have other idea or suggestions on how we might want to implement this! Happy to chat in more detail about this when we meet next week.

Richard

**Comment by richardbarad** [comment]
As discussed a few weeks back, I added a vega widget with a language signal to the API and integrated into mapbuilder. I am attaching an example HTML file and am also including a screenshoot below. [language_Test.zip](https://github.com/wri/gfw-mapbuilder/files/2963146/language_Test.zip)

I think there are two questions here:

1) Can we pass the language "signal" from mapbuilder to the API.

2) Can we hide the language signal from the vega widget so that the user does not control the language, and the language is controlled by the application. I guess we need to do this in the Vega itself or hide it in mapbuilder through HTML. I have seen examples of cases where Vizzuality seems has changed the HTML on the application side. 
![image](https://user-images.githubusercontent.com/40440743/54306631-2fc47980-45a0-11e9-9d9e-f523185dd0c2.png)

**Comment by richardbarad** [comment]
Hi @SwampGuzzler and @csphang,

Some more updates updates here! I was able to figure out how to hide the the bind signal and updated the Vega accordingly. I also posted a version of the land cover composition with a translation signal and added that to the attached configuration.

I structured them all so that just one signal needs to be passed from mapbuilder to the VEGA. The signal is called language and should have a value of en, sp, ka, id, zh, pt. Also here are the gists for the Vegas which I registered with the API and included in the attached configuration

**Land Cover:** https://gist.github.com/richardbarad/cf37084370a981521e951c7689a58440

**Tree Cover Loss** https://gist.github.com/richardbarad/eb8050ff12bcecd1bb1f5b793dc1129e

**Comment by KaylaKremer** [comment]
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/299-vega-support-multiple-languages/external.html

**Comment by richardbarad** [comment]
@KaylaKremer and @csphang 

Tested and works well in French for Land Cover Composition.

I am currently working on adding the translations signals to all the VEGA widgets. As soon as they are ready i'll post the updated widgets IDs on ticket https://github.com/wri/gfw-mapbuilder/issues/286 and share a revised configuration which includes translations for all the widgets. 

I should have that to you by Tuesday.

**Comment by csphang** [comment]
This is done except for the report. See this comment: https://github.com/wri/gfw-mapbuilder/issues/286#issuecomment-492335679
