### ISSUE TITLE
Layer panel - allow users to specify different service versions for a layer

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#303]
See example of toggling years in Greenpeace Indonesia application: http://www.greenpeace.org/seasia/id/Global/seasia/Indonesia/Code/Forest-Map/en/index.html

Also on GFW Flagship site.

![2019-01-22_16-22-40](https://user-images.githubusercontent.com/13664037/51566231-04f05b80-1e62-11e9-915a-16a7468f6cf5.jpg)

### Background
User specifies the URL for the service in the configuration file and also the names that should appear in a dropdown.

Support feature layers, dynamic map services

**Comment by richardbarad** [comment]
Hi @csphang,

As discussed I see two different use cases for this:

1) A user might want to let the map user pick between different version of a services (i.e: Different versions of a land cover layer).

2) A User might want to use it to show different versions of the same feature service, with each feature service having different filter SQL queries applied. For instance, to show different IUCN categories for an area.

Here are example services for both:

https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer
https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer

Richard

**Comment by richardbarad** [comment]
Hi @jenboyd, I do not think that is necessary. If they want to apply SQL/filter I think they can do it before publishing the services to use the filter feature we are also developing: https://github.com/wri/gfw-mapbuilder/issues/317

Also, did you plan to pull the names of the layers in dropdown come from the service or would it be specified in configuration file? I think it would be best to do it in the configuration so that we can be more flexible and also have capabilities to translate where needed.

**Comment by jenboyd** [comment]
@richardbarad Example of the layer config I am working with. It is a little lengthy, but I think all the pieces are necessary. Let me know if this is what you were thinking: 

`{
        order: 9,
         id: 'LANDCOVER_TEST',
         type: 'dynamic',
         layerIds: [0],
         url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer',
         visible: false,
         label: {
           en: 'Land Cover test - dynamic layer',
           fr: 'Land Cover test - dynamic layer',
           es: 'Land Cover test - dynamic layer',
           pt: 'Land Cover test - dynamic layer',
           id: 'Land Cover test - dynamic layer',
           zh: 'Land Cover test - dynamic layer',
           ka: 'Land Cover test - dynamic layer'
         },
         sublabel: {
           en: '(sublabel)',
           fr: '(sublabel)',
           es: '(sublabel)',
           pt: '(sublabel)',
           id: '(sublabel)',
           zh: '(sublabel)',
           ka: '(sublabel)'
         },
         versionLabel: {
           en: 'Select year',
           fr: 'Select year',
           es: 'Select year',
           pt: 'Select year',
           id: 'Select year',
           zh: 'Select year',
           ka: 'Select year'
         },
         versions: [
          {
            label: {
              en: '2008',
              fr: '2008',
              es: '2008',
              pt: '2008',
              id: '2008',
              zh: '2008',
              ka: '2008'
            },
            service: {
              en: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] },
              fr: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] },
              es: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] },
              pt: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] },
              id: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] },
              zh: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] },
              ka: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [0] }
            },
           },
           {
             label: {
               en: '2009',
               fr: '2009',
               es: '2009',
               pt: '2009',
               id: '2009',
               zh: '2009',
               ka: '2009'
             },
             service: {
               en: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] },
               fr: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] },
               es: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] },
               pt: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] },
               id: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] },
               zh: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] },
               ka: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [1] }
             },
            },
            {
              label: {
                en: '2010',
                fr: '2010',
                es: '2010',
                pt: '2010',
                id: '2010',
                zh: '2010',
                ka: '2010'
              },
              service: {
                en: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] },
                fr: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] },
                es: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] },
                pt: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] },
                id: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] },
                zh: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] },
                ka: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/', layerIds: [2] }
              },
             },
         ],
       }, {
         order: 10,
         id: 'NATIONAL_PARKS',
         type: 'feature',
         url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0',
         visible: false,
         label: {
           en: 'National Parks - feature layer',
           fr: 'National Parks - feature layer',
           es: 'National Parks - feature layer',
           pt: 'National Parks - feature layer',
           id: 'National Parks - feature layer',
           zh: 'National Parks - feature layer',
           ka: 'National Parks - feature layer'
         },
         sublabel: {
           en: '(sublabel)',
           fr: '(sublabel)',
           es: '(sublabel)',
           pt: '(sublabel)',
           id: '(sublabel)',
           zh: '(sublabel)',
           ka: '(sublabel)'
         },
         versionLabel: {
           en: 'Select version',
           fr: 'Select version',
           es: 'Select version',
           pt: 'Select version',
           id: 'Select version',
           zh: 'Select version',
           ka: 'Select version'
         },
         versions: [
           {
             label: {
               en: 'Protected Areas',
               fr: 'Protected Areas',
               es: 'Protected Areas',
               pt: 'Protected Areas',
               id: 'Protected Areas',
               zh: 'Protected Areas',
               ka: 'Protected Areas'
             },
             service: {
               en: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' },
               fr: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' },
               es: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' },
               pt: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' },
               id: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' },
               zh: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' },
               ka: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/0' }
             },
           }, {
              label: {
                en: 'National Parks',
                fr: 'National Parks',
                es: 'National Parks',
                pt: 'National Parks',
                id: 'National Parks',
                zh: 'National Parks',
                ka: 'National Parks'
              },
              service: {
                en: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' },
                fr: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' },
                es: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' },
                pt: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' },
                id: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' },
                zh: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' },
                ka: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/1' }
              },
            }, {
               label: {
                 en: 'Réserve naturelle intégrale',
                 fr: 'Réserve naturelle intégrale',
                 es: 'Réserve naturelle intégrale',
                 pt: 'Réserve naturelle intégrale',
                 id: 'Réserve naturelle intégrale',
                 zh: 'Réserve naturelle intégrale',
                 ka: 'Réserve naturelle intégrale'
               },
               service: {
                 en: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' },
                 fr: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' },
                 es: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' },
                 pt: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' },
                 id: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' },
                 zh: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' },
                 ka: { url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/DRC_NationalParks_test/MapServer/2' }
               },
             },
         ]
       }`

**Comment by richardbarad** [comment]
Thanks @jenboyd.

A few questions:

1) Could you clarify the distinction between the url at the top of the layer group and the subsequent three urls in the version section?

The first url in the service is: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer' and points to Layer 0. Does this indicate the default layer? 

Also, why is the first url not translated while the subsequent urls in the service section are translated?

**Comment by jenboyd** [comment]
@richardbarad @csphang @SwampGuzzler  Following from our conversation yesterday about the layer config. See below for an updated example of the config with the versions implemented. We will default to the first version on loading the layer and only include one url per version(not per language). Let me know if you have an comments.

```{
        order: 9,
         id: 'LANDCOVER_TEST',
         type: 'dynamic',
         visible: false,
         label: {
           en: 'Land Cover test - dynamic layer',
           fr: 'Land Cover test - dynamic layer',
           es: 'Land Cover test - dynamic layer',
           pt: 'Land Cover test - dynamic layer',
           id: 'Land Cover test - dynamic layer',
           zh: 'Land Cover test - dynamic layer',
           ka: 'Land Cover test - dynamic layer'
         },
         sublabel: {
           en: '(sublabel)',
           fr: '(sublabel)',
           es: '(sublabel)',
           pt: '(sublabel)',
           id: '(sublabel)',
           zh: '(sublabel)',
           ka: '(sublabel)'
         },
         versionHeaderText: {
           en: 'Select year',
           fr: 'Select year',
           es: 'Select year',
           pt: 'Select year',
           id: 'Select year',
           zh: 'Select year',
           ka: 'Select year'
         },
         versions: [
          {
            label: {
              en: '2008',
              fr: '2008',
              es: '2008',
              pt: '2008',
              id: '2008',
              zh: '2008',
              ka: '2008'
            },
            url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/',
            layerIds: [0]
           },
           {
             label: {
               en: '2009',
               fr: '2009',
               es: '2009',
               pt: '2009',
               id: '2009',
               zh: '2009',
               ka: '2009'
             },
             url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/',
             layerIds: [1]
            },
            {
              label: {
                en: '2010',
                fr: '2010',
                es: '2010',
                pt: '2010',
                id: '2010',
                zh: '2010',
                ka: '2010'
              },
              url: 'https://gis.forest-atlas.org/server/rest/services/Richard_test/LandCover/MapServer/',
              layerIds: [2]
             },
         ],
       }```

**Comment by richardbarad** [comment]
@jenboyd. Looks good to me!

I have the same regarding pop-ups. Can you configure a pop-up for this layer type if it is a vector dataset?

**Comment by jenboyd** [comment]
@richardbarad the popups would work the same as they do for the other layers..right now you can only configure one on the layer and it would be the same for each version. Is that what you had in mind?  

I added a popup to the National Parks feature layer if you want to test it out here:
http://alpha.blueraster.io/gfw-mapbuilder/303-layer-versions/

**Comment by richardbarad** [comment]
@jenboyd. Perfect!

**Comment by richardbarad** [comment]
Hi @csphang and @SwampGuzzler,

Could you confirm what layer types are supported here? I notice that the tickets indicates Support feature layers, dynamic map services. I think you had previously mentioned we might be able to support other layer types as well?

I am curious if we will be able to support any raster formats (tiled,webtiled, or/and image) since one of the use cases for this is to show different versions of land cover data which will typically be raster.

Best,

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad Right now this supports only those two layer types. We could support [ImageServiceLayers](https://developers.arcgis.com/javascript/3/jsapi/arcgisimageservicelayer-amd.html) relatively easily but have not plans to work in `tiled` layer types right now.

**Comment by csphang** [comment]
Potentially test using Biomass layer for supporting ImageServiceLayers
