### ISSUE TITLE
Provide application text which needs to be translated

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#306]
As part of sprint 5, could you provide any text from the application/code side which needs to be translated? 

I'll send it out to our relevant staff along with the text for the new vega widgets and updated base configuration.

**Comment by csphang** [comment]
[Translations February 9 2019.docx](https://github.com/wri/gfw-mapbuilder/files/2857147/Translations.February.9.2019.docx)

**Comment by richardbarad** [comment]
@csphang! Thanks this is great. 

I think I noticed that part of the subscription workflow still need to be translated. Could you confirm those translations are also managed through mapbuilder?

**Comment by richardbarad** [comment]
Hi @csphang,

Here is the document I mentioned. Let me know if you have any questions.
[Translations.docx](https://github.com/wri/gfw-mapbuilder/files/2882260/Translations.docx)

**Comment by richardbarad** [comment]
@csphang. Communications indicated that they already sent the text in the document I shared for translations. 

For the additional text, please use a separate document but copy the formatting from the document I shared.
