### ISSUE TITLE
Overwrite API configuration parameter in the library build

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#307]
Let users using the library build overwrite/add to the API configuration, by specifying a parameter in their configuration file. 

For example, a user could specify `"visible":true` to have a layer be visible by default even though the layer is not visible by default in the API configuration.

**Comment by SwampGuzzler** [comment]
@nbumbarger This one seems very related to #320 which is in [Sprint 2](https://github.com/wri/gfw-mapbuilder/projects/6) so I am assigning it over to you for now!

**Comment by SwampGuzzler** [comment]
@richardbarad [Here](http://alpha.blueraster.io/gfw-mapbuilder/307-overwrite-config-params/external.html) I configured certain layer settings right in the `layer` section of the library constructor. 

`{
          order: 1,
          type: 'remoteDataLayer',
          uuid: '0721f089-b887-4d49-bad3-4b19261de208',
          lucas: 'cotnaaa',
          visible: true,
          sublabel: {
            en: 'new sublabellll'
          },
          label: {
            en: 'Tree Cover Lost'
          }
        }`

**Comment by SwampGuzzler** [comment]
I overrode the parameters `visible`, `sublabel`, and `label`. I also added a fake parameter `lucas` to show that that will not affect our layer's creation.

**Comment by SwampGuzzler** [comment]
Code updates are in [PR 357](https://github.com/wri/gfw-mapbuilder/pull/357)

**Comment by csphang** [comment]
Noticed that the info window shows the older the older `label` and `sublabel` - per conversation with @SwampGuzzler, we will orvveride the `legendConfig` object to honor the new parameters from layer settings

![2019-03-21_14-41-21](https://user-images.githubusercontent.com/13664037/54777231-3e3a1300-4be8-11e9-8294-1b40dedbd2d6.jpg)

**Comment by richardbarad** [comment]
Thanks looks good @SwampGuzzler! 

@csphang. In the metadata window I think the text comes here the metadata endpoint so I am not sure if we can overwrite that? https://production-api.globalforestwatch.org/v1/gfw-metadata/tree_cover_loss

Anyways, I do not think we will be overwriting the label/sublabl so I am not too concerned about it!

Best,

Richard

**Comment by richardbarad** [comment]
Tested using a build on https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/merge-of-primary-forest-and-2018/1.3.4.js. Looks good!
