### ISSUE TITLE
Check why mapbuilder text is showing up in bold on some applications

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#308]
It looks like text is being bolded on some mapbuilder applications. These seems to be present in all of the library build/CMS applications:

- https://atlas.mepa.gov.ge/map?l=en
- https://cod.forest-atlas.org/map?l=en

I am also noticing it here: http://my.gfw-mapbuilder.org/

**Comment by jenboyd** [comment]
@richardbarad This looks like there are some CORS settings that need to be updated on the S3 bucket containing the fonts.

If looks like the request for this specific font weight is failing https://my.gfw-mapbuilder.org/fonts/firasans-regular-webfont.woff2

**Comment by jenboyd** [comment]
@richardbarad On second look, we already have a reference to google fonts in the code base. This is working correctly, so we can use this instead.

**Comment by richardbarad** [comment]
@jenboyd and @csphang,

This should be working correctly now. Thomas made some adjustments to the S3 bucket.
