### ISSUE TITLE
Layers in groups which are not in web map render in the wrong order after translation

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#315]
If you:

1. Open the application in the primary language
2. translate it to the secondary language

The layers within a layer group which are not coming from the webmap load in the wrong order. They are correct in the layer panel but are not correct in the map. As an example, I am attaching two screenshots of the Georgia atlas. One is in Georgian and the other is in English. You will notice that the points get hidden in the protected area group after the application is translated. 
 
![app_en](https://user-images.githubusercontent.com/40440743/51352700-6ab4a000-1a7c-11e9-855b-cc0a26b1c778.png)
![app_ka](https://user-images.githubusercontent.com/40440743/51352702-6be5cd00-1a7c-11e9-826e-dd87ae3f624a.png)

**Comment by richardbarad** [comment]
@csphang. Given that seems to be a reoccurring issue can we please add a test which checks for this? 

Richard

**Comment by csphang** [comment]
@SwampGuzzler Can you create a second build of this with Cameroon's config?

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/315-lang-reset-order/external-grg.html
http://alpha.blueraster.io/gfw-mapbuilder/315-lang-reset-order/external-drc.html
http://alpha.blueraster.io/gfw-mapbuilder/315-lang-reset-order/external-cmr.html

**Comment by SwampGuzzler** [comment]
@csphang Test different configurations here! @richardbarad I think that this process of testing the same issue/workflow across builds for multiple countries could make this process more efficient!

**Comment by csphang** [comment]
@richardbarad This is ready for you to test at:  
http://alpha.blueraster.io/gfw-mapbuilder/315-lang-reset-order/external-grg.html
http://alpha.blueraster.io/gfw-mapbuilder/315-lang-reset-order/external-drc.html
http://alpha.blueraster.io/gfw-mapbuilder/315-lang-reset-order/external-cmr.html

**Comment by richardbarad** [comment]
@csphang & @SwampGuzzler.

Looks good! 

I did notice that when you click on the links above and open in a new tab the webmap does not load in the correct position. Maybe unrelated?

**Comment by SwampGuzzler** [comment]
@richardbarad Cool. Just curious: could you send a screenshot of the Incorrect Position?

**Comment by richardbarad** [comment]
@SwampGuzzler.

Can not replicate it anymore :(

**Comment by richardbarad** [comment]
Tested using a build on https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/merge-of-primary-forest-and-2018/1.3.4.js. Looks good!
