### ISSUE TITLE
Analysis not working for shapes in map in some mapbuilders

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#316]
Hi all,

We noticed that the analysis for user defined shapes in the map is not working in some mapbuilders. It looks the call the geostore is not being made, and there is an error being returned in the console. To date, I have only noticed the issue in two mapbuilders:

https://lbr.forest-atlas.org/map
https://www.cfs-watch.com/interactive-map

In both cases, an error is returned in the console when you:

1. Click on a shape in the map
2. Click on the analyze tab.

I also do not notice any requests to the geostore endpoint in the network tab of the developer tools. Any ideas what might be going on? I am attaching an error from the console.

![geostore](https://user-images.githubusercontent.com/40440743/51551702-fe032200-1e3c-11e9-9655-fad4e619bcc9.png)

**Comment by richardbarad** [comment]
As mentioned on slack this does not seem to be working here:

https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/merge-of-primary-forest-and-2018/external.html?appid=0bdf18459d5544e881a06577805f2b8f

**Comment by SwampGuzzler** [comment]
Approved by @richardbarad after testing the latest fix from #369 on this [build](https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/316-geometry-catch/external.html?appid=0bdf18459d5544e881a06577805f2b8f)
