### ISSUE TITLE
SAD alerts layer not working API builder

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#319]
SAD alerts layer not working API builder. You can not turn on the SAD alerts layer in the new build.

**Comment by richardbarad** [comment]
This is due to an issue with the layer configuration. Assigning to myself to fix.

**Comment by richardbarad** [comment]
@nbumbarger I updated the SAD layer to include the legend configuration, but it still seems to be having issues as the layer is not loading in the 1.3.3 version. https://my.gfw-mapbuilder.org/v1.3.3/

https://production-api.globalforestwatch.org/v1/dataset/9cf2ad4e-4adb-40d6-b9b8-5b1287720bf0/layer/3e9e86ae-e38d-4c59-8484-c8214ca5186a

**Comment by nbumbarger** [comment]
@richardbarad- The data source appears to be down (layer 2 to corresponds to Imazon SAD layer in the MapServer's preview).

http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fgis-gfw.wri.org%2Farcgis%2Frest%2Fservices%2Fforest_change%2FMapServer&source=sd

**Comment by richardbarad** [comment]
Hi @nbumbarger. I believe it is the 3rd layer called "IMAZON SAD"? It seems to be loading on my end.

![2019-02-08 16_18_10-inbox - richard barad wri org - outlook](https://user-images.githubusercontent.com/40440743/52506646-3042ac80-2bbd-11e9-8f0f-5c8ea28cd05e.png)

It is also working in version 1.3: https://my.gfw-mapbuilder.org/v1.3/

**Comment by csphang** [comment]
Tested and verfied on https://my.gfw-mapbuilder.org/v1.3.3/

![2019-02-11_15-34-46](https://user-images.githubusercontent.com/13664037/52591731-a3912c00-2e12-11e9-8b61-fdf8e342c995.jpg)
