### ISSUE TITLE
Layers in 1.3.3 test are not rendering in the correct order.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#321]
In the new version, v1.3.3_test the layers which are not coming from the web map render in the wrong order. Please see the screenshots below:

**Version 1.3.3_test** The Land Cover / Tree Cover Density layers appear on top.

![v1 3 3 3_test](https://user-images.githubusercontent.com/40440743/51915462-20e78600-23a9-11e9-915f-d5cfd5fd06da.png)

**Version 1.3** The IFL layer is on top

![v1 3](https://user-images.githubusercontent.com/40440743/51915481-3197fc00-23a9-11e9-97a0-53a8abf18fd2.png)

**Comment by nbumbarger** [comment]
@richardbarad the issue is that I left the "order" attribute behind in the example resources (because at one point I thought it would be convenient), but the remote layers are actually completely overwritten by the API results.

Would you like to configure order through the API (which should currently be possible), or would you prefer it remained in the resources?

**Comment by richardbarad** [comment]
Hi @nbumbarger. 

Let's keep it in the resources file. I thought I updated all the layers in the API which had an "order" in the API layer settings but let me know if I missed something.

**Comment by richardbarad** [comment]
@nbumbarger. One more thought. Is it possible to implement this feature at the same time? If so, I can move that ticket to sprint 2. https://github.com/wri/gfw-mapbuilder/issues/307

**Comment by richardbarad** [comment]
Hi @csphang and @nbumbarger,

I noticed this ticket was marked as approved. It looks like layers from the API are still rendering in the wrong order in the map. If I turn on Both IFL and Tree Cover density in version 1.3.3 the IFL layer is hidden by the tree cover density layer. Please see the screenshots above.

Richard

**Comment by csphang** [comment]
Reverse order for layer rendering within groups

**Comment by richardbarad** [comment]
Hi @csphang,

Not sure if this a matter of just switching the layer rending within groups. It seems to be something specific to the new API layers. If you look at the Georgia map and turn on the IFL and Forest Cover layers, the IFL is correctly placed on top of the Forest Cover layer.

![image](https://user-images.githubusercontent.com/40440743/52669395-f4bd2080-2ee3-11e9-80c2-8fbe193ad5b4.png)

However, if I turn on land cover and IFL land cover appears on top of IFL even though it is below IFL in the list. It seems like non-API layers are showing up in the right spot but API layers are not. 

![image](https://user-images.githubusercontent.com/40440743/52669501-3057ea80-2ee4-11e9-9feb-0ca21ea2fb02.png)


http://geo2.doesntexist.org/map?l=en

**Comment by jenboyd** [comment]
Can be tested here: https://my.gfw-mapbuilder.org/v1.3.3/
