### ISSUE TITLE
Layers are not rendering in 1.3.3_test

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#324]
URL to test with: https://my.gfw-mapbuilder.org/v1.3.3_test/

Layers fail to load on map - may need to update config in 1.3.3_test html file?

**Comment by csphang** [comment]
@nbumbarger  made an adjustment for the app to still load if a layer is missing its ‘id’ and ‘layerIds’

**Comment by richardbarad** [comment]
Hi @csphang and @nbumbarger,

I made a few updates to the layer configurations in the API and the html. It is possible I might have broken something somewhere. If you notice something I changed that introduced this bug please let me know.
