### ISSUE TITLE
The legend is not visible in 1.3.3

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#327]
https://my.gfw-mapbuilder.org/v1.3.3/

**Comment by nbumbarger** [comment]
@richardbarad I looked into this, and the only difference between the last snapshot where legends were working and the current version is that I changed the API URL from
`https://api.resourcewatch.org/layer`
to
`https://production-api.globalforestwatch.org/v1/layer`
I can look into more on Monday, but can you think why that would be, off the top of your head?

**Comment by richardbarad** [comment]
@nbumbarger. Sorry, I do not know why this would have caused the legends to stop working. 

I just checked GFW and it makes layer calls using this url to call layers:

https://api.resourcewatch.org/v1/dataset?application=gfw&includes=metadata,vocabulary,layer&page[size]=9999&hash=7 

Looks like they make one call to call the datasets/layers that have the "GFW" tag. If changing it to resourcewatch solves the problems let's go ahead and change it!
