### ISSUE TITLE
The scroll bar on the information panel is no longer visible. 

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#331]
When the info. window panels extends beyond the available space there is no longer a scroll option available, and instead the info window content extends out of the side panel. I think this bugs was introduced in 1.3.1. See the screenshots below and links to the Ethiopia and India atlases. 

![image](https://user-images.githubusercontent.com/40440743/52722170-174d4900-2f79-11e9-86fa-91d435da51cd.png)

https://india.restorationatlas.org/atlas
http://eth.restorationatlas.org/atlas

**Comment by csphang** [comment]
@richardbarad I'm having trouble reproducing this for India, but I do see it happening on the Ethiopia Atlas. http://eth.restorationatlas.org/atlas

**Comment by richardbarad** [comment]
@csphang,

I reverted the India back to 1.3.0 as a temporary fix.

**Comment by jenboyd** [comment]
Fix can be tested for this here: http://alpha.blueraster.io/gfw-mapbuilder/331-info-panel-scroll/

**Comment by jenboyd** [comment]
Releasing fix with v1.3.3 instead of with Sprint 5 items.
