### ISSUE TITLE
In the data tab, we should show a scroll bar when the content is larger than the available space

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#332]
In the data tab, we should show a scroll bar when the pop up content is larger than the available space. As an example, In the Georgia atlas they have some fields with very long names, resulting in content which overuns the infowindow. There is currently no way to see the additional content. To replicate:

1) Go to the Georgia atlas https://atlas.mepa.gov.ge/map?l=ka
2) Set the language to Georgian
3) Turn on the the 2nd layer in the 2nd group in the webmap
4) Click on one of the stripped green shapes.

Here is a screenshoot of the issue.

![image](https://user-images.githubusercontent.com/40440743/52732975-8afa5080-2f8f-11e9-825a-f6d666e3c5b1.png)

**Comment by richardbarad** [comment]
@csphang. Added this to sprint 5. I think it should be an easy fix?

**Comment by jenboyd** [comment]
Fixed with issue #331

**Comment by jenboyd** [comment]
Releasing fix with v1.3.3 instead of with Sprint 5 items.
