### ISSUE TITLE
The share button is not working in ArcGIS Online apps which use 1.3.3

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#333]
It seems like the share button is broken when you use applications created through ArcGIS Online with version 1.3.3.

Here are some examples:

- https://my.gfw-mapbuilder.org/v1.3.3/?appid=277b92455c6c49059a95c9129be7baf9

- https://my.gfw-mapbuilder.org/v1.3.3/?appid=f369d487979b42ff9afec4c25a2962ed

The following error is returned in the console:

![image](https://user-images.githubusercontent.com/40440743/52739839-c3a22600-2f9f-11e9-873b-8fab8124a38e.png)

The share button works when using 1.3.

- https://my.gfw-mapbuilder.org/v1.3/?appid=277b92455c6c49059a95c9129be7baf9

- https://my.gfw-mapbuilder.org/v1.3/?appid=f369d487979b42ff9afec4c25a2962ed

The share button works correctly in the library build: 

http://blueraster.teaches-yoga.com/GEO

**Comment by SwampGuzzler** [comment]
Test this fix [here](http://alpha.blueraster.io/gfw-mapbuilder/333-share-break/external.html?appid=277b92455c6c49059a95c9129be7baf9) and see the code fix on PR #341

**Comment by csphang** [comment]
@SwampGuzzler I was digging into this more this morning and noticed two things with the build (they may be unrelated to the share - if they are, I can move them into separate tickets).

### To recreate

1. Load http://alpha.blueraster.io/gfw-mapbuilder/333-share-break/external.html?appid=277b92455c6c49059a95c9129be7baf9
2. Clear all layers, > Turn on Tree cover loss
3. Share > Copy URL + Paste in new tab
4. Notice that map loads correctly but legend doesn't populate. This is occurring for all` Land Cover Dynamics` and `Land Cover` datasets. legends load properly after sharing for webmap layers.

Second workflow
1. Load the app http://alpha.blueraster.io/gfw-mapbuilder/333-share-break/external.html?appid=277b92455c6c49059a95c9129be7baf9
2. Clear all layers > Turn on IFL > Zoom in 3 or 4 times
3. Share > Copy URL + Paste in new tab
4. Notice that map loads `Artisanal permits for annual timber cutting` and `Territories` layers. The share URL seems correct and only includes IFL in the hash.

![2019-02-20_10-56-57](https://user-images.githubusercontent.com/13664037/53105022-5e4db800-34fe-11e9-99ed-31921d79605a.jpg)
![2019-02-20_10-55-48](https://user-images.githubusercontent.com/13664037/53105026-5ee64e80-34fe-11e9-9e52-41c6505b34b3.jpg)
![2019-02-20_10-55-36](https://user-images.githubusercontent.com/13664037/53105027-5ee64e80-34fe-11e9-9543-552dcc0b0031.jpg)

**Comment by richardbarad** [comment]
Thanks for catching this @csphang.

@SwampGuzzler,

1) Looks like this was an issue introduced in 1.3.3. It works correctly in 1.3.

2) Number two is present in previous versions. I believe the issue is that the layers with a zoom dependency are getting turned on. 

Are these easy fixes? If so, should we wait to release 1.3.3 until these are fixed? I tested 1.3.3 this morning and everything else looks good.

Richard

**Comment by richardbarad** [comment]
Hi @SwampGuzzler and @csphang,

Could you provide an update on this tomorrow? 

I think we should address the first issue prior to release since it is a new bug, while the 2nd one seems to have already existed so may not be a release blocker. However, it it easy to fix we can fix it as well prior to releasing 1.3.3. 

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad Hey! We tackled the first issue, and it can be tested [here](http://alpha.blueraster.io/gfw-mapbuilder/333-share-update/external.html?appid=277b92455c6c49059a95c9129be7baf9) !

**Comment by SwampGuzzler** [comment]
If we are ready to release after the one above looks good (@csphang already tested and approved), we will address the 2nd one in the next release!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good! I think we can go ahead and merge into 1.3.3. Noticing that the scroll bar issue https://github.com/wri/gfw-mapbuilder/issues/331 is also addressed here. Is that part of 1.3.3 as well? Or will it be 1.3.4?

**Comment by richardbarad** [comment]
Making a new ticket for the 2nd bug Christina notice above. The ticket here:

https://github.com/wri/gfw-mapbuilder/issues/348
