### ISSUE TITLE
Edge Browser - Loading Error "MapBuilder is not defined"

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#337]
### To Test
http://blueraster.teaches-yoga.com/CMR?l=en

1. Load URL above in **Edge browser**
2. You'll see a blank white screen and the console error `SCRIPT5009: 'MapBuilder' is not defined`

![2019-02-15_12-14-43](https://user-images.githubusercontent.com/13664037/52872835-7945b400-311b-11e9-8fd5-cead09e58a67.jpg)

**Comment by jenboyd** [comment]
@csphang You can test a fix for this here: http://alpha.blueraster.io/gfw-mapbuilder/337-edge-mapbuilder-undefined/
