### ISSUE TITLE
Share button formatting in CMS - remove extra white space

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#338]
Test with: http://blueraster.teaches-yoga.com/CMR

![2019-02-15_11-51-59](https://user-images.githubusercontent.com/13664037/52871501-30d8c700-3118-11e9-9f51-dcd28ce1244c.jpg)

**Comment by richardbarad** [comment]
Hi @csphang,

One thing I am noticing here is that this white space shows up in this map: http://cod.doesntexist.org/map?l=fr

But it does not show up in this map: http://richard.teaches-yoga.com/map2

The difference is that the 1st one includes some custom HTML/CSS that Thomas added on the CMS side to address an issue with the formatting of the metadata window. It seems like this extra white space must be a side effect of the additional custom CSS/HTML.

This is explained in more detail in this ticket: https://github.com/wri/gfw-mapbuilder/issues/339

Ideally, I think all the CSS/HTML for the map should be managed through mapbuilder so maybe the solution is that we should remove all the CSS/HTML from the CMS and make the necessary changes directly in mapbuilder?

**Comment by csphang** [comment]
We'll add a custom class for the info window modal

**Comment by richardbarad** [comment]
Hi @csphang & @KaylaKremer,

As discussed, I updated several maps on the Blue Raster site to point to a version without the custom HTML. Here are the maps:

http://blueraster.teaches-yoga.com/ETH?
http://blueraster.teaches-yoga.com/DRC?

You will notice the styling for the metadata pop-ups, both for metadata coming from the GFW metadata and metadata coming from ArcGIS Online is off. See the screenshots below:

![2019-03-12 16_28_03-Forest Atlas of DRC](https://user-images.githubusercontent.com/40440743/54233727-eca4d080-44e3-11e9-9d6a-ff1cbabeaf68.png)

![Eth_Metadata](https://user-images.githubusercontent.com/40440743/54233731-ef9fc100-44e3-11e9-841e-ac89dd6cdfa6.png)

**Comment by csphang** [comment]
Hi @rbarad, we were able to resolve the issue directly in the CMS. 

###  Steps
1. In the HTML snippet for the map version, replace this line `.modal-wrapper .modal {width: 550px; max-height: unset;}` with this new line of css `.layer-modal-container .modal {width: 550px;}`

This targets a specific modal rather than all the modals.

![2019-03-21_11-56-16](https://user-images.githubusercontent.com/13664037/54766004-e47a1e80-4bd0-11e9-8d4f-de31f6523f01.jpg)

**Comment by richardbarad** [comment]
Thanks! Looks good! I just updated the CSS/HTML accordingly on the staging and live sites.

**Comment by richardbarad** [comment]
@csphang,

After implementing the steps above the issue with the share button is fixed but we still seem to have an issue with the metadata window coming from ARcGIS (shown below). This is replicable using 1.3.4 on staging CMS. (eg:http://blueraster.teaches-yoga.com/CMR?l=fr)

![image](https://user-images.githubusercontent.com/40440743/57150886-7adb5b80-6d9d-11e9-90e2-28aad454d968.png)

I am moving this back to the backlog since I do not think this an urgent fix. On live, I left it so that the metadata window looks correct but the share button has the extra white space.

**Comment by richardbarad** [comment]
Closing this ticket since this was addressed here: https://github.com/wri/gfw-mapbuilder/issues/552
