### ISSUE TITLE
The timeslider for the loss layer is not working.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#344]
When you click the play button on the loss time slider the animation does not work. Please see the attached video.
[Loss_Animation_Broken.zip](https://github.com/wri/gfw-mapbuilder/files/2889551/Loss_Animation_Broken.zip)

**Comment by richardbarad** [comment]
@csphang. Adding this bug fix to 1.3.4.

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/344-loss-slider/external.html

**Comment by SwampGuzzler** [comment]
https://github.com/wri/gfw-mapbuilder/pull/349 is the fix!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good!
