### ISSUE TITLE
The legend breaks when you specify multiple LayerIDs for a dynamic layer

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#345]
If you specify multiple layers for a Dynamic webmap service the legend will break. 

Here is an example: http://ind2.doesntexist.org/atlas

If you turn on the Landscape Restoration Opportunities layer which includes two different LayerIDs (0,1) for the same dynamic layer the legend for that layer is broken. See the screenshot below.

![brokenlegend](https://user-images.githubusercontent.com/40440743/53175490-0eccc200-35ba-11e9-82ed-201bca6ef828.png)

**Comment by csphang** [comment]
@richardbarad Quick clarification question! Is the goal to display both the state boundary **and** the restoration opportunities within the same layer? If it is, could we try creating a Group layer within the service and reference the ID within the config?

![2019-03-26_13-37-16](https://user-images.githubusercontent.com/13664037/55020129-98621c00-4fcc-11e9-85f0-25d34ad6906b.png)

**Comment by richardbarad** [comment]
@csphang Yes, the goal is to show both in the same layer in mapbuilder. I can test this setup and see if it works.

Richard

**Comment by richardbarad** [comment]
Hi Christina,

I tested it out in a different configuration on staging: http://geo2.doesntexist.org/map?l=en. Please see the EUNIS habitat group in the biodiversity group which includes two layers named points and polygons. 

![2019-03-29 09_21_04-Window](https://user-images.githubusercontent.com/40440743/55235481-080e1c00-5204-11e9-8996-593b216f8070.png)

Here is the service: https://gis.mepa.gov.ge/server/rest/services/Richard_Testing/Bio_test/MapServer

Unfortunately, this solution also seems to have issues.

1) You can not configure a pop-up on the group layer
2) The group layer does not seem to have a legend connected to it. 

Please see the screenshot below.
![2019-03-29 09_22_46-Window](https://user-images.githubusercontent.com/40440743/55235691-85399100-5204-11e9-8537-abbf0c35fe67.png)

Also, I realize this is a specific issue which is only relevant for 1 or 2 configurations I think we could put it on hold till a latter sprint if that would help us prioritize some other items.

**Comment by richardbarad** [comment]
Moving this back to backlog. https://github.com/wri/gfw-mapbuilder/projects/9#card-20086260 is a higher priority.

**Comment by vaidotasp** [comment]
was fixed during the recent work.
