### ISSUE TITLE
Issue with translation pop-ups.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#347]
https://atlas.mepa.gov.ge/map?l=en

In our Georgia atlas if you:

1) Open the application in Georgian
2) Translate the application to English
3) Click on a shape in the protected layer which is visible by default.
4) The resulting pop-up will show up in Georgian even though pop-ups are configured for both languages

If you open the pop-up directly in the Georgian atlas it works.

See screenshoot below:

![image](https://user-images.githubusercontent.com/40440743/53371030-3eaef900-391d-11e9-8c7a-072641a52858.png)

**Comment by richardbarad** [comment]
@csphang. Adding this ticket to Sprint 5 (v1.3.4).

Let me know if you see any issues with this.

Best,

Richard

**Comment by SwampGuzzler** [comment]
Updated! Check out the fix on [alpha](http://alpha.blueraster.io/gfw-mapbuilder/347-popup-translations/external.html)

**Comment by csphang** [comment]
@SwampGuzzler Tested and confirmed on http://alpha.blueraster.io/gfw-mapbuilder/347-popup-translations/external.html

**Comment by richardbarad** [comment]
Tested using a build on https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/merge-of-primary-forest-and-2018/1.3.4.js. Looks good!
