### ISSUE TITLE
Zoom dependent layers show up when you share the atlas

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#348]
Zoom dependent layers show up in the atlas maps when you share the atlas even if they are turned of.
This bug was noted here: https://github.com/wri/gfw-mapbuilder/issues/333

1. Load the app https://my.gfw-mapbuilder.org/v1.3/?appid=277b92455c6c49059a95c9129be7baf9
2. Clear all layers > Turn on IFL > Zoom in 3 or 4 times
3. Share > Copy URL + Paste in new tab
4. Notice that map loads `Artisanal permits for annual timber cutting` and `Territories` layers. The share URL seems correct and only includes IFL in the hash.

![2019-02-20_10-56-57](https://user-images.githubusercontent.com/13664037/53105178-a40a8080-34fe-11e9-84cd-2d1563ba9fe8.jpg)
![2019-02-20_10-55-48](https://user-images.githubusercontent.com/13664037/53105179-a40a8080-34fe-11e9-96d5-85502dc00e6e.jpg)
![2019-02-20_10-55-36](https://user-images.githubusercontent.com/13664037/53105180-a40a8080-34fe-11e9-9855-483acb1486ce.jpg)

**Comment by SwampGuzzler** [comment]
@csphang http://alpha.blueraster.io/gfw-mapbuilder/348-zoom-dependent-share/?appid=277b92455c6c49059a95c9129be7baf9 Let's check this out together!

**Comment by SwampGuzzler** [comment]
@richardbarad Can you begin testing this while @csphang does as well?

**Comment by richardbarad** [comment]
@SwampGuzzler. Just tested! This bug is addressed but we seem to have a new issue:

In my testing workflow I:

1) Clicked clear all
2) Turned on just the shape as graphic & Feature layer with metadata layers
3) Clicked share, and copied the url into a new tab

In my result, the tiled layer & AGOL item with limited metadata still load in the map even though they are not turned on. Here is the url which was generated by the workflow above: http://alpha.blueraster.io/gfw-mapbuilder/348-zoom-dependent-share/?appid=277b92455c6c49059a95c9129be7baf9&x=24.42&y=-3.75&z=5&l=en&b=null&t=LAYERS&a=Cherangany_WGS_shapefile_4406_0%2CAffectation_des_terres_fr_8473&o=0.6%2C0.6

**Comment by richardbarad** [comment]
[sharing.zip](https://github.com/wri/gfw-mapbuilder/files/3691164/sharing.zip)

**Comment by SwampGuzzler** [comment]
@richardbarad Thanks for the catch - I got a fix for that issue back up at the same [url](http://alpha.blueraster.io/gfw-mapbuilder/348-zoom-dependent-share/?appid=277b92455c6c49059a95c9129be7baf9&x=19.98&y=-3.41&z=6&l=en&b=null&t=LAYERS&a=Cherangany_WGS_shapefile_4406_0%2CAffectation_des_terres_fr_8473&o=0.6%2C0.6)!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good!
