### ISSUE TITLE
Add support for 2018 loss Layer

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#351]
As mentioned to @csphang today we now have 2018 loss data! We have set up a mapbuilder layer configuration for the data in the API: http://production-api.globalforestwatch.org/layer/2aed67b3-3643-40d3-9c1e-8af9afb5d9e2. I am attaching a version of v1.3 app which uses the new layer. 

However, it looks like the slider functionality is not working and 2018 is not showing up in the slider. Can you take a look and makes any necessary updates? Note that we will keep using the 2017 layer for now but just want to make sure we are ready to release the 2018 data on mapbuilder at the same time as flagship. The tiles are still being generated so you may need to lower the canopy density to below 20% and zoom in below zoom level 7 to see the data.

Let me know if you need any additional information. 

[2018_test.zip](https://github.com/wri/gfw-mapbuilder/files/2968496/2018_test.zip)

**Comment by KaylaKremer** [comment]
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/351-add-2018-loss-layer/external.html

**Comment by KaylaKremer** [comment]
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/351-add-2018-loss-layer/external.html

**Comment by richardbarad** [comment]
@SwampGuzzler & @csphang Looks good! Noticing that the time slider does not work, but guessing that will be fixed when everything is merged together?

**Comment by csphang** [comment]
@richardbarad Yes, this will be in when everything is merged!

**Comment by richardbarad** [comment]
Hi @csphang, @SwampGuzzler, and @KaylaKremer 

Just wanted to follow up to confirm that this being merged into 1.3.4? The release of the 2018 TCL data is scheduled for Thursday this week and I would like to try to time our 1.3.4 release with the release of the TCL data. Is it possible to get this merged in today so that we can leave time for testing before a release? 

This is a priority! Many thanks!

**Comment by richardbarad** [comment]
Tested here: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/merge-of-primary-forest-and-2018/external.html

As discussed on slack we need to check to make the loss slider works with the 2018 data.
