### ISSUE TITLE
Analysis panel: Add loading icon while graphs are loading

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#355]
Add in a loading icon to indicate the graph is still loading

### To Test
Run analysis on Glad Alerts (Vega)

![2019-03-26_13-18-13](https://user-images.githubusercontent.com/13664037/55018659-b7ab7a00-4fc9-11e9-9e01-cd378e00bd49.png)

**Comment by KaylaKremer** [comment]
@csphang Do you have a config I can use that has the Glad Alerts (Vega)?

**Comment by KaylaKremer** [comment]
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/355-add-loading-icon/external.html

**Comment by csphang** [comment]
This is ready to be merged
