### ISSUE TITLE
Pull fires layers from the new services used in GFW Fires

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#360]
Use same UI/filter setup as GFW Fires.

Christian worked on re-working UI/layer endpoints for Fires

**Comment by SwampGuzzler** [comment]
https://fires.globalforestwatch.org/map/#activeLayers=viirsFires&activeBasemap=topo&activeImagery=&planetCategory=PLANET-MONTHLY&planetPeriod=Jan%200000&x=-2.285156&y=44.360919&z=3 --> see the different underlying services and layerDefinitions that each dropdown selection gives us in the exportImage calls! @KaylaKremer

**Comment by SwampGuzzler** [comment]
This is the ArcGIS Server which holds the services we want to access: https://gis-gfw.wri.org/arcgis/rest/services/Fires: we care about the `...24hrs`, `...48hrs`, `...7d`, and `...1yr` (for both VIIRS and MODIS). Talk to Christian about the change in GFW Fires!

**Comment by KaylaKremer** [comment]
For reference: 
-https://github.com/wri/gfw-fires-app/blob/master/src/map/js/helpers/LayersHelper.js
-https://github.com/wri/gfw-fires-app/blob/master/src/map/js/config.js#L267

**Comment by KaylaKremer** [comment]
Test Build: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/360-gfw-fires/external.html

**Comment by richardbarad** [comment]
@KaylaKremer. Looking good! The data loads so much faster than the old services. 

Let me know once you are done with the configuration. I'd be happy to help post an updated layer configuration to the API.

**Comment by KaylaKremer** [comment]
Test Build: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/360-gfw-fires/external.html

**Comment by richardbarad** [comment]
This is approved for release!

**Comment by richardbarad** [comment]
@KaylaKremer and @SwampGuzzler,

We should pull the layer configurations from the API. Let me know if I should move forward with adding the new layer configurations to the API

**Comment by richardbarad** [comment]
@KaylaKremer.

Here are the configurations in the API:

**VIIRS:** `15cb32c9-874f-4552-afdc-8a35ef70682f`

**MODIS:** `8ae39d34-a5e5-4742-b06e-6e913a8f1eb8`

I tested it out locally using the latest version of the code any eveything looked good! Let's update our default configuration which is what we use at the link below to use these layers!

https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/test-build-with-new-config-no-restoration/external.html

**Comment by KaylaKremer** [comment]
@richardbarad I updated the build at the same link with the new VIIRS & MODIS configs in case you would like to test it further!
Also I made a PR of this branch to update our default config. I'll have Lucas review it later today.

**Comment by richardbarad** [comment]
@KaylaKremer.

Thanks! There seems to be one small bug. When you turn on the fire layer for the first time the app does not load  all the points from the last 24 hours. 

However, if you switch to the past 48 hours and then switch back to the past 24 hours it correctly loads all the points. I am attaching a video which should help you see what is happening. I checked the build which did not use the API layer and it seems to be present there as well so I do not think it is related to the API update. 

[Firesbug.zip](https://github.com/wri/gfw-mapbuilder/files/3266908/Firesbug.zip)


Richard

**Comment by richardbarad** [comment]
@KaylaKremer. Regarding the point above, I think i found the issue. It looks like the call to the fires service includes some filters the first time it is made which might not be necessary? 

Here are the filters I am seeing: &layerDefs={"21":"ACQ_DATE > date'2019-06-06'"}&f=image

**Comment by KaylaKremer** [comment]
Hi @richardbarad! I actually noticed this issue before with the layer definitions and fixed it, but I forgot to update the original build for this ticket. I've now updated it for you to check out here: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/360-gfw-fires/external.html

**Comment by richardbarad** [comment]
@KaylaKremer.

I am still seeing this issue at both the links below:

https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/360-gfw-fires/external.html

https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/test-build-with-new-config-no-restoration/external.html

**Comment by richardbarad** [comment]
@KaylaKremer.

Looks like the issue above is fixed now, but I did seem to find one more small issue which we should fix if possible. It looks like pop-ups only work for fires from the past 24 hours. 

If you switch to another time period and click on a fire point which older than the past 24 hours the pop-up does not show up. I am attaching a video in which I switch the time period to the past week and once I do this some of the pop-ups stop working. 
[firepopups.zip](https://github.com/wri/gfw-mapbuilder/files/3273906/firepopups.zip)
