### ISSUE TITLE
When you have a feature service, set to visible true it is not visible in the legend by default. 

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#363]
Hoping this should be a quick fix! 

We are working with RSPO to make a mapbuilder which uses a more complex configuration. I noticed that when we set a feature layer to `visible:true` the associated legend is not visible. I am attaching a configuration which demonstrates this bug. Also attaching a video of the bug. 

[testrspo_20190410.zip](https://github.com/wri/gfw-mapbuilder/files/3064547/testrspo_20190410.zip)

![2019-04-10 11_34_22-Icecream screen recorder](https://user-images.githubusercontent.com/40440743/55892701-cb87dc00-5b84-11e9-8955-99510e6d154c.png)

**Comment by SwampGuzzler** [comment]
[Here](http://alpha.blueraster.io/gfw-mapbuilder/363-legend-fix/external.html) to test! (I removed the `RSPO Certified Mills` layer because its pointing at an endpoint that no longer exists)

**Comment by csphang** [comment]
@SwampGuzzler Tested and confirmed this is fixed! @richardbarad This is ready for your review at:

http://alpha.blueraster.io/gfw-mapbuilder/363-legend-fix/external.html

![2019-04-19_15-09-27](https://user-images.githubusercontent.com/13664037/56439723-27eda880-62b5-11e9-9ea5-977d98523012.png)

**Comment by richardbarad** [comment]
@SwampGuzzler @csphang. Tested and confirmed that this looks good!
