### ISSUE TITLE
Update mapbuilder 1.3.4 to use new primary forest layer

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#364]
As discussed, we should update mapbuilder in 1.3.4 to use the new pan-tropical primary forest layer!

Here is the layer in the API. This layer can replace the previous primary forest layer in the base configuration. Let me know if you notice any issues! 

http://production-api.globalforestwatch.org/layer/edffb745-e523-462d-ad1e-3052006a3dbc

**Comment by KaylaKremer** [comment]
https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/364-new-primary-forest-layer/external.html

**Comment by richardbarad** [comment]
Looks good! Only comment is we should make sure we keep the same layer order when we deploy the layer to the my gfw build. It should be right above the biomass layer and below IFL.

**Comment by csphang** [comment]
Hi @richardbarad. The order has been updated & is available to test:

https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/364-new-primary-forest-layer/external.html

**Comment by richardbarad** [comment]
Looks good. Thanks! Please go ahead and merge into 1.3.4.
