### ISSUE TITLE
When you translate a mapbuilder application the filter by attribute fields do not work in secondary language.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#372]
As example, try translating this application http://geo2.doesntexist.org/map?l=ka.

The emerald network layer in the third group has a filter on it, when you change languages to English the filters are still in Georgian. It also seems like the filters do not work in English (the secondary language).

![Filter_Bug](https://user-images.githubusercontent.com/40440743/56836234-96e27880-6844-11e9-8093-4a5a22d2efb6.png)

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/372-translate-dropdown/external.html

**Comment by csphang** [comment]
@richardbarad this is ready for your review at http://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/372-translate-dropdown/external.html

![2019-04-30_13-25-19](https://user-images.githubusercontent.com/13664037/56980862-74ee3c00-6b4b-11e9-9faa-b1f1b553b74e.png)

**Comment by richardbarad** [comment]
@csphang and @SwampGuzzler.

Tested and confirmed as working.

**Comment by richardbarad** [comment]
@csphang & @SwampGuzzler.

Please let me know once you post this to S3. I will need to update 1.3 in order for the updates to apply to the atlas and will also need to clear the cloudfront cache.

**Comment by richardbarad** [comment]
@csphang and @SwampGuzzler,

I updated the Georgia atlas to add filters on all the layers they wanted to filter. Unfortunatly, we still seem to be running into this issue for one of the layers. 

It is the Touristic Routes of Protected Areas which is 2nd in protected areas group:

https://atlas.mepa.gov.ge/map?l=en
![PA_Bug](https://user-images.githubusercontent.com/40440743/57033058-e0064400-6c19-11e9-894d-ae1ba1c474ce.png)
