### ISSUE TITLE
Loss, Gain, and GLAD Alert do not print.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#373]
**If you:**

1) Turn on the loss, gain, or GLAD Alert layers, 
2) Click the print button

The layers do not print to the output PDF. It looks like the issue is that the GEE tiles are not being passed to the ESRI print service. Possible to address?

**Comment by vaidotasp** [comment]
limitations of this is known, at this time, the only solution is to implement completely custom PDF generation.
