### ISSUE TITLE
Report does not work when you turn on API Layers in map

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#374]
In v1.3.4 if you:

1) Turn on any API layer (loss,gain, SAD, etc).

2)  Try to run an analysis report

An error is returned in the console. It looks like the issue is that the report can not load the API layers. I just checked and it seemed to work correctly in v1.3.3

Testable here in CMS: http://blueraster.teaches-yoga.com/CMR?l=en

Also testable here: https://my.gfw-mapbuilder.org/v1.3.4/?appid=277b92455c6c49059a95c9129be7baf9

![Console_error](https://user-images.githubusercontent.com/40440743/56924237-685ddb00-6a9a-11e9-9bee-52201b946129.png)

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/134-report/external.html?appid=277b92455c6c49059a95c9129be7baf9

**Comment by csphang** [comment]
@richardbarad This is ready for your review at http://alpha.blueraster.io/gfw-mapbuilder/134-report/external.html?appid=277b92455c6c49059a95c9129be7baf9

**Comment by richardbarad** [comment]
@csphang. Look good! We can merge into `v1.3.4`

**Comment by SwampGuzzler** [comment]
Awesome!

**Comment by richardbarad** [comment]
Actually @SwampGuzzler. It looks like the layers are rendering in the wrong order. The loss / gain layers are not on top of the webmap layers. Possible to fix before merging?

**Comment by richardbarad** [comment]
@SwampGuzzler. Approved and tested on production. Opening a new ticket for the layer order issue above and putting into the blacklog.
