### ISSUE TITLE
Filter by attribute not working on one layer in Georgia Atlas

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#375]
@csphang and @SwampGuzzler,

I updated the Georgia atlas to add filters on all the layers they wanted to filter. Unfortunately, we still seem to be running into this issue for one of the layers. Going to add a new ticket for this in the next sprint. Seems like it might have something to do with the layer type since this one is a line?

It is the Touristic Routes of Protected Areas which is 2nd layer in protected areas group:

https://atlas.mepa.gov.ge/map?l=en
![PA_Bug](https://user-images.githubusercontent.com/40440743/57033058-e0064400-6c19-11e9-894d-ae1ba1c474ce.png)

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/375-filter-by-attribute/external.html?l=en

**Comment by csphang** [comment]
@richardbarad You can test this here http://alpha.blueraster.io/gfw-mapbuilder/375-filter-by-attribute/external.html?l=en

One thing to note is that we are excluding "null" values from appearing in the dropdown. BUT we are not currently excluding empty values. You can see these two scenarios in the screenshots below.

![2019-05-06_12-19-57](https://user-images.githubusercontent.com/13664037/57239351-a5295500-6ff9-11e9-95a0-8407286dd9a9.png)

![2019-05-06_12-17-47](https://user-images.githubusercontent.com/13664037/57239358-a8bcdc00-6ff9-11e9-9ab9-ad8c71afdce6.png)

**Comment by richardbarad** [comment]
@csphang & @SwampGuzzler . Fix looks good!

I'll communicate this to the team and advise that they update them to all be null.

**Comment by mapsgeek** [comment]
@richardbarad  how do you enable that filter by attribute list ?
