### ISSUE TITLE
Design Specification for Drawing Features using Cordinates

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#376]
Develop Design specifications for drawing features by entering coordinates.

I sent an e-mail to the team who provided this feature request to see if they have any specific specifications in mind. Will post here if I hear a response!

Richard

**Comment by richardbarad** [comment]
@csphang. Please see responses to our questions from the Central Africa team which requested this feature.


1.	**How many coordinates should the user be able to add? How complex are the geometries users want to create using coordinates?**

Based on various land use allocations in Official Gazettes,95 % of the permits(mining, hydrocarbures,.) have between 4- 10 coordinates ,which means that we might design something which can take from 4 to 10 coordinates in the beginning . Complex shapes of more than 10 coordinates will be uploaded using the second option of shapefile upload.
 
2.	**Should users be able to edit a coordinate after they have typed it? If yes, would they edit the coordinate by entering a new coordinate value or would they drag the coordinate?**

Yes, in order to prevent that in case of error typing user should retake the whole process. These two options seems interesting if not complicated in terms of designing. The second of dragging would even be helpful in case of superposition whereby someone is interested in reducing/reshaping  the request in no overlapping area.
 
**3.	What coordinate system do we need to support? Are you both UTM and lat/long important to include?**

Actually 80% of coordinates are given in Lat/Long(DMS) which means its priorisation in terms of designing. However in order to make it more user friendly the UTM option would definitely be more an added value.

**Comment by csphang** [comment]
For coordinates design:
- Default to DMS
- @richardbarad to check back on importance of UTM
- Support DD
- Account for editing coordinates via drag and also popup to re-edit values

Create two PDFs w/some annotations for Richard to share with the team.

**Comment by csphang** [comment]
[Create_Shape_Coordinates.pdf](https://github.com/wri/gfw-mapbuilder/files/3278357/Create_Shape_Coordinates.pdf)

**Comment by richardbarad** [comment]
@csphang.

This design is approved! 

Let's support DMS and DD for now.
