### ISSUE TITLE
Provide documentation/details on date fields in alert layer configurations

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#381]
Could you clarify how the the `maxDateValue` & `minDateValue` fields in our alert layer configurations work? For instance, if I wanted to change GLAD to start on 01/01/2018 what would I need to change the `minDateValue` value to. Here is the layer in the API: http://production-api.globalforestwatch.org/layer/356f862b-3e70-493a-997b-dc2a193410e9

The use case is that in some countries, GLAD alerts are not available for prior to 01/01/2018 so we would want to update the minimum filter value to start on 01/01/2018. Currently, the values read `"maxDateValue": 999999`, & `"minDateValue": 15000` I think should be able to do this via API overwrite but I am sure if I understand the date format. (edited)

**Comment by KaylaKremer** [comment]
@richardbarad Test Build with GLAD config changed to start on 2018: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/glad-2018-config/external.html

We will be providing the documentation for this later today.

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! Awesome! Noticing that the build we are using is from before we had the layer configurations in the API.

 We should be able to overwrite this parameter when using the new API layers? @SwampGuzzler

Richard

**Comment by KaylaKremer** [comment]
@richardbarad Here is the documentation explaining `maxDateValue` & `minDateValue`:
https://github.com/wri/gfw-mapbuilder/wiki/Julian-Calendar-Conversion

**Comment by csphang** [comment]
Investigate min/max values within API endpoint. Add to documentation when a user would update the API vs. the JavaScript code.

http://production-api.globalforestwatch.org/layer/356f862b-3e70-493a-997b-dc2a193410e9
https://production-api.globalforestwatch.org/layer/1fc7b0c5-259a-4685-8665-b2f1ed3f808f

**Comment by csphang** [comment]
Currently we are going to open a new ticket to update the maxDateValue and minDateValue for Terra-I
