### ISSUE TITLE
Design specifications for selecting multiple features in the attribute window

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#382]
Design specifications for selecting multiple features in the attribute window

MapBuilder link: https://cod.forest-atlas.org//map?l=en

GFW Flagship Site Link: https://www.globalforestwatch.org/map

![2019-05-29_16-55-24](https://user-images.githubusercontent.com/13664037/58590717-ae8d9200-8232-11e9-8cbc-f2669e994e86.jpg)
![2019-05-29_16-55-11](https://user-images.githubusercontent.com/13664037/58590718-af262880-8232-11e9-9a4a-cf05f6f66682.jpg)
![2019-05-29_16-55-01](https://user-images.githubusercontent.com/13664037/58590719-af262880-8232-11e9-8ca5-42fcb8b6679d.jpg)

**Comment by csphang** [comment]
[Layer_Navigation.pdf](https://github.com/wri/gfw-mapbuilder/files/3278356/Layer_Navigation.pdf)

**Comment by richardbarad** [comment]
@csphang This is approved! Let's plan to work on this feature for 1.4.2 release.
