### ISSUE TITLE
Report Chart Titles: pull from configuration file rather than widget

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#390]
Pull in the titles directly from config file, instead of displaying from the widget:

When we start working on the report configuration will will need to switch to use these widgets instead which do not have titles in the widget. They all still include the language signal.

- [] Total Tree Cover Loss/Gain - `95c2c559-ca78-4b7a-b18b-7b2bca14ce83`

- [] Annual Tree Cover Loss - `e53e541c-92cd-4b00-9aa7-2c7bb36d4697`

- [] CO2 Emissions from biomass loss -`ac38fdbd-fdb1-4d8e-9109-674013fb51a2`

- [] Annual Tree Cover Loss in IFL - `2083a1bc-440d-43fe-8b50-ff9918a37c57`

- [] Annual Tree Cover Loss by Land Cover Class - `31f78466-fc0b-42f9-a7ae-bea8559740d8` 

- [] GLAD Alerts Per Month - `0734ba0a-3a6c-4388-aa4a-5871791b1d1f`

- [] Total GLAD Alerts - `16ff6282-8ceb-4055-938a-43726a62b205` 

- [] VIIRS Active Fires - `5d696f96-e6c7-4323-8bda-4c99cd6b0cb4`

- [] Land Cover Composition - `1b84364d-0efd-4d60-81ef-870f7d13ee7b`

**Comment by richardbarad** [comment]
Richard to fork widgets and create version without the titles.
