### ISSUE TITLE
Resizing widgets between analysis panel and the analysis report

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#396]
Confirm we are able to modify the width and height of the widgets dynamically so we can leverage one widget for both the analysis panel in the app and the report.

### See Vega Documentation: https://vega.github.io/vega/docs/api/view/ 
 
![2019-06-04_16-58-01](https://user-images.githubusercontent.com/13664037/58913357-040de700-86ea-11e9-9576-2b435cc7edfa.jpg)

**Comment by richardbarad** [comment]
Here are some links to pages in the CMS where the VEGA widgets resize dynamically:

Liberia: https://lbr.forest-atlas.org/tree-cover-loss/tcl-fmc

Georgia: https://atlas.mepa.gov.ge/dashboard?l=en

**Comment by KaylaKremer** [comment]
@richardbarad @SwampGuzzler I researched this morning how we can make the VEGA widgets resize dynamically and found some examples. It looks like we could resize by adding a signal and using VEGA's `containerSize()` function. Also, we might need to add VEGA's `autosize`spec property.

Examples:
https://groups.google.com/forum/#!topic/vega-js/YovF3RvlnRg
https://codepen.io/anon/pen/BPwJgN

VEGA Docs:
https://vega.github.io/vega/docs/expressions/#containerSize
https://vega.github.io/vega/docs/specification/#autosize

**Comment by richardbarad** [comment]
Great @KaylaKremer! Do you still want me to reach out to Vizzuality?

**Comment by KaylaKremer** [comment]
@richardbarad Yes, please still reach out to Vizzuality! I just spoke with @SwampGuzzler  and he said maybe we should try to arrange a meeting with them to go over it. And from the two examples I found, it seems they both have added signals for an `on` event listener for both `width` and `height`. Something like this:

```
"signals": [
      {
      "name": "width",
      "value": "",
      "on": [
        {
          "events": {
            "source": "window",
            "type": "resize"
          },
          "update": "containerSize()[0]*0.95"
        }
      ]
    },
    {
      "name": "height",
      "value": "",
      "on": [
        {
          "events": {
            "source": "window",
            "type": "resize"
          },
          "update": "containerSize()[1]*0.95"
        }
      ]
    }
  ]
```

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! Do you mind sharing the link to your latest build so that I can show them what we are aiming to achieve.

**Comment by KaylaKremer** [comment]
@richardbarad Sure, here it is: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/new-report-styles/external.html

**Comment by csphang** [comment]
Verified we are resizing between the map analysis panel and the report. Viewable in consolidated builds: 
http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/ethiopia/

![2019-08-20_15-23-12](https://user-images.githubusercontent.com/13664037/63377617-75128180-c35e-11e9-9348-701261de6d8f.png)
![2019-08-20_15-22-28](https://user-images.githubusercontent.com/13664037/63377618-75128180-c35e-11e9-8a99-98e848d6ef15.png)
