### ISSUE TITLE
Share feature

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#397]

**Comment by KaylaKremer** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/397-share-feature/

**Comment by richardbarad** [comment]
@KaylaKremer. Please remove Google+ as an option since it no longer online! We should also removed Google+ from the share tools in the map if that is an easy/quick update.

Richard

**Comment by KaylaKremer** [comment]
@richardbarad I just updated the build at the same URL and removed Google+ from the report and in the map

**Comment by csphang** [comment]
Verified on http://alpha.blueraster.io/gfw-mapbuilder/493-share-modal/

![2019-08-20_14-51-46](https://user-images.githubusercontent.com/13664037/63375631-282cac00-c35a-11e9-85a3-d5ce772ab680.png)
![2019-08-20_14-52-22](https://user-images.githubusercontent.com/13664037/63375632-282cac00-c35a-11e9-94ff-c5e875afddc8.png)
