### ISSUE TITLE
Analysis report does not work in 1.4.0 application template configuration.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#413]
If I:

1) Click on a shape in https://my.gfw-mapbuilder.org/v1.4.0/?appid=277b92455c6c49059a95c9129be7baf9&l=en

2) Click the print report button

My report does not load! I think the link to the .js file is not correct as I believe we need to link to the  `report.js` file instead of the `https://library.gfw-mapbuilder.org/1.4.0.js` file.

**Comment by richardbarad** [comment]
@SwampGuzzler. It looks like the report .js file used in `https://my.gfw-mapbuilder.org/v1.4.0/` is pointing to the wrong source again. It is pointing to: `http://alpha.blueraster.io/gfw-mapbuilder/246-report-external-build/reportLib.1.4.0.js` and also showing the wrong analysis modules in the report.

**Comment by SwampGuzzler** [comment]
@richardbarad This has been updated at the above URL!
