### ISSUE TITLE
VIIRS 24 hours Fire Layer is not loading data.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#416]
Currently, the VIIRS 24 hour layer is not loading any fires point.

If you:

1) Open a configuration in the CMS or outside which uses v1.4.0:

https://my.gfw-mapbuilder.org/v1.4.0/
http://blueraster.teaches-yoga.com/DRC?l=en

2) Turn on the VIIRS Fires layer the fires points do not load in the map. If you switch the layer to use past 48 hours, or 72 hours the points load as expected.

It looks like the issue is not present for MODIS.

**Comment by SwampGuzzler** [comment]
Per @csphang, this issue was resolved on the ArcGIS Server and the VIIRS 24 hours layer is rendering again!
