### ISSUE TITLE
(Dynamic Resize): Keep original signals

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#435]
- Keep original signals
- Keep max height same as you resize, and adjust the width (see https://lbr.forest-atlas.org/dashboard/protected-area-statistics)

**Comment by richardbarad** [comment]
@KaylaKremer and @csphang. Just for clarification, what do we mean here we say keep original signals?

**Comment by SwampGuzzler** [comment]
@KaylaKremer Looking good, but let's also try the workflow we talked about during our code review! --> https://github.com/wri/gfw-mapbuilder/pull/449#pullrequestreview-266683590
