### ISSUE TITLE
Widgets are not the right size in the layer panel

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#438]

**Comment by richardbarad** [comment]
Widgets are not the right size in the layer panel in this build: http://alpha.blueraster.io/gfw-mapbuilder/396-resizing-widgets/

![image](https://user-images.githubusercontent.com/40440743/61720982-c155ac00-ad35-11e9-9a06-5dad492edaac.png)

**Comment by csphang** [comment]
Verified on consolidated builds and coordinates build. View this updated on  http://alpha.blueraster.io/gfw-mapbuilder/454-coordinates/

![2019-08-20_15-36-44](https://user-images.githubusercontent.com/13664037/63378517-63ca7480-c360-11e9-82cc-4e40de23532f.png)
