### ISSUE TITLE
Provide updated design specifications for the report.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#439]
Provide updated design specifications for new report without the grey space next to the map.

![2019-07-23_12-21-20](https://user-images.githubusercontent.com/13664037/61729077-7db66e80-ad44-11e9-92de-f9e8b856a00b.png)

**Comment by richardbarad** [comment]
@csphang. Do you think we need to include the grey box which includes the text **"Area of Analysis feature analysis"** ? I think we could remove the grey box and do the following:

1. If it is a custom area show the text "Custom Feature" under Area of Analysis. 

2. If it is an area from the map display the name of the layer that the users clicked on. For example, if analyzed a mining concession. I would see the text "Mining Concession" above the table instead of "Feature Analysis".

I suggest we center the text above the table.

**Comment by csphang** [comment]
![updated-report-header](https://user-images.githubusercontent.com/13664037/61743560-8d917b00-ad63-11e9-8ae3-da9628d1d818.png)

**Comment by richardbarad** [comment]
Thanks @csphang.

Do you think we need to include the grey box as shown below? I thought we could center the text and make it larger to eliminate some of the empty space. 

![2019-07-24 05_51_30-Window](https://user-images.githubusercontent.com/40440743/61784435-b05d7700-add7-11e9-89ab-3ccd9742a336.png)


Also, since this was a feature of the map which the user clicked on I think should show the name of the map layer which contained the analyzed feature instead of **"custom feature"**. For example, it looks like the shape above is a Mining Concessions. Let me know if that is not clear!

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

I can go ahead and make the style changes you want for this! I'll remove the gray box and center align and enlarge the text. Also, I believe how I have it set up now, it will grab the name of the map layer if there is one. But I can add this in if it's not.

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! Please proceed.
