### ISSUE TITLE
Once new report builds are consolidated put up builds for testing different configurations.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#440]
Test both appids & atlas CMS configurations. Richard to post list of builds to test.

**Comment by richardbarad** [comment]
Let's test the following configurations:

1. Georgia
2. Liberia
3. DRC
4. Paraguay (Tierra Indigenous)
5. Ethiopia
6. Appid test app: `https://my.gfw-mapbuilder.org/v1.4.0/?appid=277b92455c6c49059a95c9129be7baf9`

I am attaching the configurations for Georgia, Liberia, DRC, Paraguay, Ethiopia. 

For Georgia and Liberia there are some custom analysis which are pie charts so I will need to update the VEGA to allow for resizing in the report. We probably also need to update the analysis panel based on how we decide to identify which analysis get a `max-width `in the report https://github.com/wri/gfw-mapbuilder/issues/452.

**Comment by richardbarad** [comment]
Hi @SwampGuzzler,

When we put up these new builds we will need to update the WidgetIds for some of the custom country widgets as well as the global anlysis. Please use the IDs listed below for the custom analysis in Liberia and Georgia. 

These are the only ones with custom analysis:

**Georgia:**
•	Hazards Risk: f42aa3d7-d33b-4067-b2a6-5554e15092b1
•	Slope: 814e4fd9-6b82-4482-95a2-ffb30935b577
•	Aspect: dc01a94a-58d5-4835-9277-7244399bece3
•	Elevation: e776d408-73a8-4674-b578-c3fbd479a3c9

**Liberia:**
•	**Land Cover Composition:** f870684d-e59f-413e-b4e6-21dd52937244

We also created new versions of all the widgets for the global analysis so those will need to be updated as well. Here are the new widgets ID for the global analysis which should match up with the ones we have been using for testing.

- Total Tree Cover Loss: `95c2c559-ca78-4b7a-b18b-7b2bca14ce83`
- Annual Tree Cover Loss: `e53e541c-92cd-4b00-9aa7-2c7bb36d4697`
- Annual Tree Cover Loss in IFL: `2083a1bc-440d-43fe-8b50-ff9918a37c57`
- Annual Tree Cover Loss by Land Cover Class: `31f78466-fc0b-42f9-a7ae-bea8559740d8`
- CO2 Emissions from biomass loss: `ac38fdbd-fdb1-4d8e-9109-674013fb51a2`
- GLAD Alert monthly Average: `b5e43ea3-2812-484e-bc31-1bf5d2fe8aa0` (this one is used for countries with a longer GLAD time series (from the countries listed above just DRC)
- GLAD Alerts per month (use for all countries with GLAD analysis except DRC, Ethiopia & Georgia do not have GLAD analysis): `0734ba0a-3a6c-4388-aa4a-5871791b1d1f`
- Total GLAD Alerts: `16ff6282-8ceb-4055-938a-43726a62b205`
- VIIRS Active Fires: `5d696f96-e6c7-4323-8bda-4c99cd6b0cb4`
- Land Cover Composition: `1b84364d-0efd-4d60-81ef-870f7d13ee7b`

I think the Ethiopia should still work, but once you test let me know if you see any issues in the report! I will also take a look once you have the new build up.

Richard

**Comment by richardbarad** [comment]
@SwampGuzzler. 

I had forked the widgets and made new versions with the titles removed and adjusted some of the settings to allow for better resizing. I went ahead and updated the test configuration to use the latest version of the widgetIDs so that work is already done! Here are the revised versions:

[test_builds.zip](https://github.com/wri/gfw-mapbuilder/files/3477773/test_builds.zip)

I did not update the Ethiopia widgets but I think they should already work with the new report and should resize nicely. I believe you will just need to update the configurations to include the type of vega chart.

Let me know if you have any questions!

Richard

**Comment by KaylaKremer** [comment]
Hi @richardbarad,

I think we're now ready for you to test the reports! I've made a build of the default config as well as builds of the other configs you provided:

- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/tierras-indigenas/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/liberia-forest-atlas/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/fluids-georgia/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/ethiopia/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/atlas-forestier-rdc/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/atlas-forestier-cameroun/

**Comment by richardbarad** [comment]
@KaylaKremer. It looks like the chart types still need to be added to the configuration so that they resize properly.

**Comment by KaylaKremer** [comment]
@richardbarad ,

All configs have been updated with `chartType` and a new build has been made for each. As you requested in the Slack channel, the Ethiopia build has every `chartType` set to as `badge`. You'll still notice that the Ethiopia charts' heights appear short, which I expected. Please see my comment on #495 which explains this behavior!

**Comment by csphang** [comment]
Updated Ethiopia Rainfall analysis WidgetId: `a329302f-a6a8-4f83-9258-802a0f0be401`
