### ISSUE TITLE
If we add a custom analysis how would we tell MapBuilder to apply a maxwidth

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#452]
We could apply a standard max-width to use for badges and pie charts and specify in the configuration file if the chart is a pie or badge.

**Comment by SwampGuzzler** [comment]
@KaylaKremer @richardbarad After we decide on how to do this, let's update the documentation in this repo to reflect our new **Analysis Module** properties: https://github.com/wri/gfw-mapbuilder/wiki/Analysis-Module-Configuration

then we can write tests on that to ensure we have legit configurations ((((:

**Comment by richardbarad** [comment]
@SwampGuzzler. Yes, for sure! Should we store VEGAs somewhere in the MapBuilder github? At least for the VEGA configuration which are part of the base configuration? 

Right now I have them in gists which I am guessing is not the best place to keep them!
