### ISSUE TITLE
(Draw Tool): Support drawing features by entering coordinates

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#454]
### Updates from 8/27 meeting
Use esri popup to show small modal of the lat/long in DD.

### Design Specs
Download at https://chilp.it/079cece

### Design PDF
https://github.com/wri/gfw-mapbuilder/files/3278357/Create_Shape_Coordinates.pdf

**Comment by csphang** [comment]
![2019-08-19_14-04-08](https://user-images.githubusercontent.com/13664037/63288635-2f38b900-c28b-11e9-976d-53fff1430df4.png)

**Comment by KaylaKremer** [comment]
@csphang , Thanks for pointing out these style issues out! I think I have it now fixed in Firefox:

<img width="1279" alt="Screen Shot 2019-08-19 at 5 27 38 PM" src="https://user-images.githubusercontent.com/22095244/63300709-d8d97380-c2a6-11e9-9ab2-64538bf10f71.png">

Lucas & I are still working on the coordinate functionality. Should be done tomorrow!

**Comment by KaylaKremer** [comment]
@csphang @richardbarad 

Build: http://alpha.blueraster.io/gfw-mapbuilder/454-coordinates/

I've added in error handling for when the user forgets to enter in coordinates or if they enter an inappropriate numerical value. This wasn't in the original design, but I figured it would be good to have.

The only thing that still needs to be done is adding the popup edit coordinate modal when editing a shape. Not sure if I will finish this part today before our meeting, but wanted to get a build up of what I've completed for everyone to review!

**Comment by csphang** [comment]
@KaylaKremer Error handling looks good 👍 

![2019-08-20_14-24-45](https://user-images.githubusercontent.com/13664037/63373651-498b9900-c356-11e9-8c2b-2f6c01a76f61.png)

**Comment by richardbarad** [comment]
@KaylaKremer and @csphang. 

This is looking great! One small comment, can we zoom to the shape after it is created?

Richard

**Comment by richardbarad** [comment]
One more comment. I also see that we changed the style on the edit button to make it more apparent to users. I think this looks much better. Can we make sure the Delete button is aligned with analysis dropdown and thin grey line? See screenshot below. 

![2019-08-21 13_53_12-GFW Mapbuilder](https://user-images.githubusercontent.com/40440743/63455936-cb91c580-c41b-11e9-9d48-a89a13ed899a.png)

**Comment by KaylaKremer** [comment]
@richardbarad , I had thought it would be a good idea to zoom to the shape as well! I've already asked Lucas about how to implement it, so it's definitely doable!

And I have made note of adjusting the styling a bit

**Comment by richardbarad** [comment]
@KaylaKremer. A small comment here. The text for the draw cordinate for reads "Degrees, Decimal, Minutes". It should be Degrees, Minutes, Seconds (DMS)?

![image](https://user-images.githubusercontent.com/40440743/64199492-72cd1e80-ce58-11e9-9053-a08914103144.png)

**Comment by csphang** [comment]
@KaylaKremer for the styling, see the satellite imagery tooltip

![image](https://user-images.githubusercontent.com/13664037/64205386-d14cc980-ce65-11e9-8dab-7f17d9416ac3.png)

**Comment by richardbarad** [comment]
Comments on pop-up from 9/3/2019:

- Make Decimal Degree text smaller and below coordinate values
- Make text smaller in general
- When you click on the x box in the coordinate values, close the pop-up but the user will still need to click save to save the the shape

**Comment by KaylaKremer** [comment]
@richardbarad ,

Sorry for the long wait in getting this ticket complete, but here is a build for you to test out: http://alpha.blueraster.io/gfw-mapbuilder/new-edit-coordinates-functionality/

The modal window appears when you hover over the vertex points. It will disappear if the user clicks on the `x` or clicks on the `save` buttons. The modal is also draggable in case a user wants to manually move it on the screen to wherever they want.

I also fixed the issue of the save/edit button in the info window and analysis not matching up with each other when a user is editing.

**Comment by richardbarad** [comment]
Looks good @KaylaKremer. Please make **(Decimal Degrees)** not bold. You can use the same font and the text which shows the latitude and longitude. Once this update is made this is approved.

**Comment by KaylaKremer** [comment]
@richardbarad Great, will do!

**Comment by KaylaKremer** [comment]
@richardbarad The build has been updated once more at the same URL. Lucas and I reviewed and merged it in. I think this ticket should be good to move over as complete!

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good!
