### ISSUE TITLE
Add translations for parts of app

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#457]
Word doc with translations coming soon

**Comment by richardbarad** [comment]
@csphang. I have attached word documents with the translations.

Note that some of the translations are handled through the API, widgets, 
layer configurations, and analysis module so this information should all already be translated. I believe the components which need to be translated on your side are:

- Measurement tools
- Subscription tools
- Recent Imagery tools
- Some of the analysis tools text, which is not handled through the configuration

**Spanish:** [Translations_ES-LA_AM.docx](https://github.com/wri/gfw-mapbuilder/files/3473159/Translations_ES-LA_AM.docx)

**Indonesian:** [Translations_ID-IC.docx](https://github.com/wri/gfw-mapbuilder/files/3473160/Translations_ID-IC.docx)

**Georgian:**
[Translations_KA_KN.docx](https://github.com/wri/gfw-mapbuilder/files/3473161/Translations_KA_KN.docx)

**Portuguese:**
[Translations_PT-BR_MM.docx](https://github.com/wri/gfw-mapbuilder/files/3473167/Translations_PT-BR_MM.docx)

**Chinese:**
[Translations_ZH-CN_bl.docx](https://github.com/wri/gfw-mapbuilder/files/3473170/Translations_ZH-CN_bl.docx)

**French:**
[Translations_FR.docx](https://github.com/wri/gfw-mapbuilder/files/3473174/Translations_FR.docx)

**Comment by KaylaKremer** [comment]
@richardbarad ,

I've encountered a few things that haven't been translated.

For the `subscription tools`:

- Next
- You must have an alert subscription, valid email, and area name

For the `imagery module`:

- No results match the selected criteria
- Error loading recent imagery

**Comment by richardbarad** [comment]
@KaylaKremer. The text which was translated was based on a file provided by @csphang and Jennifer, but maybe we overlooked some components of the app which still need translating. I'll go through the code latter and find the code which still need translating and send it out for translation. 

In the meantime, here are some translations for the drawing coordinates feature! Note that I am still missing Spanish but hope to have that soon.

[Draw-Coordinates_ID.docx](https://github.com/wri/gfw-mapbuilder/files/3618451/Draw-Coordinates_ID.docx)
[Draw-Coordinates_KA.docx](https://github.com/wri/gfw-mapbuilder/files/3618444/Draw-Coordinates_KA.docx)
[Draw-Coordinates_PT.docx](https://github.com/wri/gfw-mapbuilder/files/3618445/Draw-Coordinates_PT.docx)
[Draw-Coordinates_ZH.docx](https://github.com/wri/gfw-mapbuilder/files/3618446/Draw-Coordinates_ZH.docx)
[Draw-Coordinates_FR.docx](https://github.com/wri/gfw-mapbuilder/files/3618447/Draw-Coordinates_FR.docx)


Best,

Richard

**Comment by KaylaKremer** [comment]
@richardbarad 

Thanks for the drawing coordinates translations!

And the translations are handled in `languages.js` as well as in our `resources.js` file for a few labels/titles.

**Comment by KaylaKremer** [comment]
@richardbarad 

I've gone ahead and updated the translations with the files you provided for the coordinates. Thanks for putting the words in order btw, it made it a lot easier to copy and paste over!

One note, the only thing that was missing from the translated coordinate section was `Coordinate Values`

To make things easier, I'm attaching the updated `languages.js` and `resources.js` file. It should be easy to tell what's still missing a translation!

[javascript files.zip](https://github.com/wri/gfw-mapbuilder/files/3627844/javascript.files.zip)

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! I will go through these next week and find the text which needs translations.

**Comment by richardbarad** [comment]
@KaylaKremer. This is approved, and we can merge in the translations we have. I'll review the `language.js` at a future phase and make sure everything get translated in the next batch of translations we send out.

**Comment by richardbarad** [comment]
@KaylaKremer. I just received translations for the draw coordinates tool in Spanish, which was the last language we needed translations for. Would you be able to add these as part of this phase?

[Draw-Coordinates_SP.docx](https://github.com/wri/gfw-mapbuilder/files/3697756/Draw-Coordinates_SP.docx)

**Comment by KaylaKremer** [comment]
@richardbarad , sure I can add them!

**Comment by richardbarad** [comment]
Thanks! Looks good!
