### ISSUE TITLE
Support custom color theming

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#460]
Ensure this is configurable through the ArcGIS Online template as well!

**Comment by richardbarad** [comment]
@richardbarad, to prepare list of what needs to be when you change the custom color theme in a MapBuilder application.

**Comment by richardbarad** [comment]
@csphang. Below is the list of what we should customize:

**Layer Panel:**
- Metadata info icon
- Download data button when you click on metadata
- The color of the date and density filters on the TCL layer
- The color of the date filters on the alert layers (GLAD, Terra-I, VIIRS, MODIS)
- Color of the Landsat toggle

**Recent Imagery Modal:**
- The color of the acquisition date filter
- Cloud cover filter 
- Natural color / vegetation health settings in

**Analysis tools:**
- Color of start drawing button
![image](https://user-images.githubusercontent.com/40440743/64275300-40ccc280-cf13-11e9-912b-f0f834ebf77e.png)
- Color of enter values button
![image](https://user-images.githubusercontent.com/40440743/64275322-4e824800-cf13-11e9-9101-6fd81ce92c40.png)
- Color of this icon (if is an svg)
![image](https://user-images.githubusercontent.com/40440743/64275459-92754d00-cf13-11e9-81a1-e11db2a03a82.png)
- Color of this icon (if is an svg)
![image](https://user-images.githubusercontent.com/40440743/64275478-9ef9a580-cf13-11e9-925c-3376fd4cd6a8.png)
- Color of orange divider lines
![image](https://user-images.githubusercontent.com/40440743/64275506-af118500-cf13-11e9-9910-5454deb11f3f.png)
- Color of the year range, tree cover density selector & date range selectors in analysis panel 

**Documents tab**
- Color of the documents icon
![image](https://user-images.githubusercontent.com/40440743/64275410-7671ab80-cf13-11e9-881c-878a66779ef9.png)

**Search tools**
- Color of the search button
![image](https://user-images.githubusercontent.com/40440743/64275556-cfd9da80-cf13-11e9-8b1c-8c44af82a394.png)

**Report**
- Color of the toggle to turn an analysis on/off
- Color of the year range, tree cover density selector & date range selectors in analysis panel

**Comment by KaylaKremer** [comment]
@richardbarad 
Test build for this ticket: http://alpha.blueraster.io/gfw-mapbuilder/460-custom-color-theme/

**Comment by SwampGuzzler** [comment]
<img width="611" alt="Screen Shot 2019-09-13 at 10 26 37 AM" src="https://user-images.githubusercontent.com/5713523/64870382-2a102500-d611-11e9-82d4-829501225bd3.png">
On Coordinates Modal

**Comment by SwampGuzzler** [comment]
<img width="823" alt="Screen Shot 2019-09-13 at 10 28 33 AM" src="https://user-images.githubusercontent.com/5713523/64870513-6cd1fd00-d611-11e9-8544-1d13d9f71999.png">
Report Analysis Options

**Comment by KaylaKremer** [comment]
@richardbarad Please ignore checking the test build until I fix the issues Lucas pointed out above!

**Comment by KaylaKremer** [comment]
@richardbarad Build should now be good to test again!

http://alpha.blueraster.io/gfw-mapbuilder/460-custom-color-theme/

**Comment by richardbarad** [comment]
@KaylaKremer.

It looks there might have been some unintentional changes in the styling of the layer panel. Please see screenshots below:

http://alpha.blueraster.io/gfw-mapbuilder/460-custom-color-theme/
![image](https://user-images.githubusercontent.com/40440743/64998018-880e6800-d8b0-11e9-8c22-18e3ba11169d.png)

https://my.gfw-mapbuilder.org/v1.4.0/
![image](https://user-images.githubusercontent.com/40440743/64998030-978db100-d8b0-11e9-9d17-a10e8e811da5.png)

**Comment by richardbarad** [comment]
@KaylaKremer & @SwampGuzzler . Please also update the configuration panels! 

https://github.com/wri/gfw-mapbuilder/tree/develop/config-panels

It would be cool to add a color picker to the standard configuration panel if ESRI supports that! If not, we can just add free text in the general settings and the user will have to add a hex code. We should use the current orange color as the default so please keep that orange color in our base resources.js configuration. Thanks!

**Comment by KaylaKremer** [comment]
@richardbarad  Thanks for pointing out the alignment issue! I'll make sure to fix that.

I'll also update the config panels too.

As for a color picker, Lucas and I discussed this the other day. We would definitely like to add it in, but it would require some time to build out. I'll bring it up with him again today and see about a time estimate. 

And I've already taken care of using a default color! There will be two new properties in our resources, `customColorTheme` and `defaultColorTheme`. If `customColorTheme` isn't specified, then everything will default to the current orange color.

**Comment by richardbarad** [comment]
@KaylaKremer. Sounds like a good plan! I am curious to know why we need to include two fields `customColorTheme` and `defaultColorTheme.`? Why can't we just have one color field? Normally, I think we just include one field in the configuration and then are able to overwrite it using an `appid`.

**Comment by KaylaKremer** [comment]
@richardbarad I can go ahead and refactor this so that it just uses one field, `customColorTheme`. That actually might be better anyways since as it currently is set up, if the user were to forget to include the `defaultColorTheme` and `customColorTheme` fields, then everything wouldn't have a color applied to it. I'll comment again with a new build after I refactor everything!

**Comment by KaylaKremer** [comment]
@richardbarad New build with the refactor (now uses only `customColorTheme field!):
http://alpha.blueraster.io/gfw-mapbuilder/custom-color-theme-refactor/

**Comment by richardbarad** [comment]
@KaylaKremer. Just tested this in an app and it looks good to merge!

http://alpha.blueraster.io/gfw-mapbuilder/custom-color-theme-refactor/?appid=061f208553fc4315b660876ba882a2b9
