### ISSUE TITLE
Support multiple radio button groups

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#462]
Ability to have multiple radio button groups in the same layer panel menu and turn on layers from BOTH groups at same time.

Currently, you can only turn on layers from one group at a time.

**Comment by richardbarad** [comment]
As an example, please see the Ethiopia MapBuilder application: http://eth.restorationatlas.org/atlas

In this application if I turn on layers in the RESTORATION POTENTIAL group, I can not also turn on layers in the REFERENCE LAYERS group. 

Users should be able to turn on only 1 layer at a time within the radio group, **BUT** should be able to turn on multiple radio layers if they are in different groups.

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a test build for this ticket: http://alpha.blueraster.io/gfw-mapbuilder/462-support-multiple-radio-button-groups/

**Comment by KaylaKremer** [comment]
@richardbarad , Besides Ethiopia, do you know of any other countries we could test with that use the radio button groups?

**Comment by richardbarad** [comment]
Georgia uses radio groups but they only have one group: https://atlas.mepa.gov.ge/maps/map?l=en. Ethiopia is the only atlas with multiple radio groups.

**Comment by KaylaKremer** [comment]
@richardbarad Ok, thanks for confirming. We noticed that too, that Georgia has them, but can't really test since they only have one radio group. I will let Lucas know!

**Comment by KaylaKremer** [comment]
@richardbarad Lucas and I went ahead and merged the code in for this, so can we mark this as approved?

**Comment by richardbarad** [comment]
@KaylaKremer. This is approved. Thanks!
