### ISSUE TITLE
Stabilize share feature functionality

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#463]
**Apps to test (particularly Georgia)**:

1.    https://cod.forest-atlas.org/map
2.    https://cmr.forest-atlas.org/map
3.    https://gab.forest-atlas.org/map
4.    https://mdg.forest-atlas.org/map
5.    https://cog.forest-atlas.org/map
6.    https://india.restorationatlas.org/atlas
7.    http://forum-florestal.doesntexist.org/Mapa2
8.    https://lbr.forest-atlas.org/map
9.    http://cog.registreredd.org/PP-redd/map
10.    https://atlas.mepa.gov.ge/maps/map
11.    https://www.tierrasindigenas.org/Mapa
12.    http://eth.restorationatlas.org/atlas
13.    https://vp.restorationatlas.org/map

**Comment by richardbarad** [comment]
@csphang. I am breaking this up into separate tickets for each of the identified issues!
