### ISSUE TITLE
The turn on/off function is no longer working

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#468]
The turn on/off function is no longer working in this build: http://alpha.blueraster.io/gfw-mapbuilder/452-update-resources-to-distinguish-chart-types/

There is a blank white space after turning off a layer: 

![image](https://user-images.githubusercontent.com/40440743/62316104-c8329c00-b464-11e9-9b07-a13a3ea0399a.png)

**Comment by csphang** [comment]
Verified this is resolved in consolidated build
http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/
