### ISSUE TITLE
Extra white space under analysis after updating analysis settings.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#469]
In this build http://alpha.blueraster.io/gfw-mapbuilder/452-update-resources-to-distinguish-chart-types/

**If I:**

1.	Draw a custom area
2.	Run a report
3.	Click the settings button on the Total Tree Cover Loss/Gain analysis
4.	Adjust the TCL or annual time period
5.	Click run analysis

Extra white space shows up under the widget while you are waiting for the results to loading. I am attaching a video of this workflow and a screenshot is also shown below. 

[Analysisbug.zip](https://github.com/wri/gfw-mapbuilder/files/3458291/Analysisbug.zip)

**Comment by csphang** [comment]
Verified on consolidated builds and the coordinates build. http://alpha.blueraster.io/gfw-mapbuilder/454-coordinates/

![2019-08-20_15-35-12](https://user-images.githubusercontent.com/13664037/63378421-2c5bc800-c360-11e9-86aa-e7f9dd1f5a5d.png)
