### ISSUE TITLE
When we run an analysis, an the analysis fails can we show the title of analysis.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#471]
When we run an analysis, an the analysis fails can we show the title of analysis. That way the user knows which analysis failed. See what happens in the screenshot below. 

![error creating analysis](https://user-images.githubusercontent.com/40440743/62321637-19e12380-b471-11e9-9634-0d8c0a30de75.png)

**Comment by csphang** [comment]
Verified on http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/ethiopia/ using the Rainfall analysis.

![2019-08-20_15-32-38](https://user-images.githubusercontent.com/13664037/63378236-ce2ee500-c35f-11e9-8496-d01e1d599561.png)
