### ISSUE TITLE
Fix our tests! Our Jest unit tests aren't up-to-date with our new analysisModule objects

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#474]
The new `chart` and `chartType` properties that our advanced modules need aren't reflected in the tests, and I want those to appear as `required`

**Comment by KaylaKremer** [comment]
@SwampGuzzler I did this in my PR! https://github.com/wri/gfw-mapbuilder/pull/472 
Not sure if I updated everything correctly

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
