### ISSUE TITLE
Update our wiki documentation to the new Analysis Module standards

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#475]
This might be an ongoing process, but let's start it near the end of this sprint!

**Comment by KaylaKremer** [comment]
@richardbarad @SwampGuzzler 

I updated the Wiki for the Analysis Module configuration: https://github.com/wri/gfw-mapbuilder/wiki/Analysis-Module-Configuration 

Let me know if there's anything I should change or add!

**Comment by csphang** [comment]
Verified

**Comment by richardbarad** [comment]
I think we need to work on this documentation a bit more. @KaylaKremer. Can you please add documentation for the max-width used for each chart type in MapBuilder. Please also indicate the signals passed from MapBuilder to the vega (i.e: `"autosize": "fit"`).

**Comment by KaylaKremer** [comment]
@richardbarad ,

I updated the wiki: https://github.com/wri/gfw-mapbuilder/wiki/Analysis-Module:-Chart-Types
