### ISSUE TITLE
Determine if we can remove some of the parameters from our Report's URL hash

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#478]
We already have a pretty long report url - if we could remove some of the no-longer-used parameters, that could make our  stand-alone Report applications more understandable!

**Comment by KaylaKremer** [comment]
@SwampGuzzler The only parameter I think we could remove is `customFeatureTitle`. After we merge in my current PRs, this will only be used in one place in `report.js`, which I've taken a screenshot of. I'm not sure if the `geojsonToArcGIS` utility function really needs this title (or even a title at all). We should discuss!

![Screen Shot 2019-08-05 at 10 43 19 AM](https://user-images.githubusercontent.com/22095244/62473268-675dd900-b76e-11e9-846e-294c26c60fbe.png)

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
