### ISSUE TITLE
New Report does not load in Edge Browser

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#480]
New Report does not load in Edge Browser

**Comment by richardbarad** [comment]
Error in console:

![image](https://user-images.githubusercontent.com/40440743/62398883-09e84300-b548-11e9-8c7a-8dd02577a22f.png)

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

This was a good catch! I debugged it this morning and I think I got it working. Please check out this build: http://alpha.blueraster.io/gfw-mapbuilder/480-error-in-edge/

One of the issues was a trailing comma in our `resources` that I found. IE/Edge have issues with these. So we should make note of it and be careful not to add any in the future!

**Comment by richardbarad** [comment]
@KaylaKremer. Tested and confirmed that this is working now! Thanks!
