### ISSUE TITLE
Reverse Lat. Long. in calls to Satellite Imagery API

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#483]
It looks like our recent satellite imagery is no longer loading in the correct location in MapBuilder. This was likely due to some recent changes made to the underlying service in the API!

To replicate:

1. Load https://my.gfw-mapbuilder.org/v1.4.0/, or any other MapBuilder application

2. Turn on recent imagery layer over DRC

3. The returned imagery will show desert imagery. If you pan out it will become apparent that the imagery loaded is over the Sahara dessert in Northwestern Africa.

From looking at our calls to the API, it looks like the lat. long. coordinates are swapped. See screenshots below. Hoping this is quick fix which we can add to `v1.4.1`, but let me know if you need me to follow with VIzzuality to get any additional information. 

![Lat_Long_Cordinates_Swap](https://user-images.githubusercontent.com/40440743/62474824-ce30c180-b771-11e9-8299-0e60cadc6860.png)

**Comment by richardbarad** [comment]
I noticed that this is working correctly in Fries and Flagship. Please check-in with Vizzuality if there are questions. 

I noticed a recent commit on GFW where there lat & long were swapped so hopefully doing the same in MapBuilder should fix this: https://github.com/Vizzuality/gfw/commit/752c6fc80b7441ee340dce9fb66ba97c139d7da1

**Comment by SwampGuzzler** [comment]
Addressed in #492 !! --> Can be tested here: http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-imagery-update/

**Comment by richardbarad** [comment]
@SwampGuzzler.

Did something change in the formatting of the image modal? The height does not look right as the entire thumbnail is not visible. See screenshoots below showing what it looks like in the link above and in `https://my.gfw-mapbuilder.org/v1.4.0/`.

**Image Modal in link above:**
![image](https://user-images.githubusercontent.com/40440743/62728816-b1eb8980-b9ea-11e9-83f8-c2306f2253af.png)

**Image Modal in v1.4.0:**
![image](https://user-images.githubusercontent.com/40440743/62728845-bdd74b80-b9ea-11e9-9c53-2741e295fe86.png)

**Comment by SwampGuzzler** [comment]
@richardbarad I just updated that same [link](http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-imagery-update/) with both of those comments!

**Comment by csphang** [comment]
@richardbarad in [Lucas' link above](http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-imagery-update/) we have the tooltip set so it doesn't show up if you are zoomed out. You have to be zoomed in to level 12 or closer. Let us know if we interpreted this right!

**Comment by richardbarad** [comment]
@csphang and @SwampGuzzler. It should be set such that the tooltip does not show up if you are zoomed in to a high zoom level. Apologies for the confusion! 

Can we also change the cut off point to zoom level 10? Thus, the tooltip should not show up if you are zoomed in to level 10 or closer.  Let me know if you need additional information!

**Comment by SwampGuzzler** [comment]
@richardbarad Updated with both of those: the cutoff is now `10` and we see the tooltip when you are zoomed **Out** !!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good! 

However, I am now noticing a different issue. If I)

1. Turn on the recent imagery
2) The modal opens but the first image no longer loads automatically and I have to click on an image to get it to load.

In the past, the first image loaded automatically. It looks like the tooltip loads but the actual image does not. The same thing happens if I pan around the map to load a new image. Please see attached video.

[Imagery_bug.zip](https://github.com/wri/gfw-mapbuilder/files/3531461/Imagery_bug.zip)

**Comment by richardbarad** [comment]
- Try to look into a fix for this, but if a quick fix is not possible add logic to indicate that if cursor is not above imagery shown in the map do not show the tooltip.

**Comment by SwampGuzzler** [comment]
@richardbarad This quick-fix can be tested here - http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-mouseover/

**Comment by richardbarad** [comment]
@SwampGuzzler & @csphang . This is looking good! From the user perspective, I could still see this being confusing though as it now seems like the imagery does not load even though it does! I wonder if we should consider the following small updates:

1) Opening up the recent imagery window on pan every time new recent imagery is loaded

2) Adding a prompt in the modal to tell the user to select an image once imagery is available

Note that I do not want to add more scope here, but just thinking about how we can make it clearer to users that the imagery is available even though it does not consistently load in the actual map! The imagery API also seems to be pretty stable right now so I am not sure if it might be possible to address the underlying issues?

Best,

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad Agreed about the user perspective.

1. This is an easy win - we now show the Recent Imagery window each time the loader hides and the calls for the imagery thumbnails have completed.
2. I added a little instruction text above the images that **only** shows when the image has not loaded properly on the Map.

http://alpha.blueraster.io/gfw-mapbuilder/483-satellite-user-perspective/

Let me know what you think!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good! Thanks for making these small changes.

**Comment by richardbarad** [comment]
@SwampGuzzler. I do not think the small changes you made above are included in `v1.4.1`. Can you please make sure thoose are merged in. When testing using this link: I noticed an instance when the imagery did not load in the map but I do not see a prompt telling me to click on an image. See screenshot below: https://my.gfw-mapbuilder.org/v1.4.1/?appid=277b92455c6c49059a95c9129be7baf9

![image](https://user-images.githubusercontent.com/40440743/65356475-94513880-dbc2-11e9-8ff8-0c0d5a7b3beb.png)

**Comment by SwampGuzzler** [comment]
@richardbarad These are now on production!
