### ISSUE TITLE
Sharing MODIS and VIIRS layers does not filter by date correctly.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#487]
If you share an application which has the VIIRS or MODIS fires layer turned on the app makes a call to this layer: https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global_VIIRS_1yr/MapServer and always shows the past 24 hours even when I change the filter to be past 48 hours, past 72 hours, etc.

See steps below to replicate:

1) Load the DRC forest atlas: https://cod.forest-atlas.org/map?l=en

2) Turn on the VIIRS fire layer, and can filter to past 48 hours.
![VIIRS_24hours](https://user-images.githubusercontent.com/40440743/62495331-90e52780-b7a3-11e9-9707-6b667c827686.png)

3) Click the share button, and copy url into a new tab. The share url makes a call to this service https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global_VIIRS_1yr/MapServer regardless of the filter applied and the app also reverts to showing fires in the past 24 hours.

![Fires_points2](https://user-images.githubusercontent.com/40440743/62495604-63e54480-b7a4-11e9-9702-4ddc48bbeaf3.png)

In our share url I see the followingappended to the url: MODIS_ACTIVE_FIRES&o=1,1,1,1,1,1,1,1,1,1,1&ms=8-4-2019 17:6:26&me=8-5-2019 17:6:26 and the past 24 hours is always appended for the ms property. I think our share settings to be updated to account for the new fires layers.

**Comment by KaylaKremer** [comment]
@richardbarad ,

I checked out this ticket and it looks like we never update the start/end dates to be anything else other than the past 24 hours in our URL parameters. So you definitely are right! Once the fires bug ticket gets resolved, I think this will be easy to fix! I'm hoping to complete this with Lucas tomorrow.

**Comment by richardbarad** [comment]
@KaylaKremer. Per our discussion on slack this looks great!

Please update the UI to still allow the user to click on the active fires, when they switch to a custom range but keep active fires grayed out.

**Comment by KaylaKremer** [comment]
@richardbarad @csphang 
Test build here! http://alpha.blueraster.io/gfw-mapbuilder/406-fires-sharing/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks like this does not work for the 1 year / custom range layer. Is this an easy fix?

Richard

**Comment by csphang** [comment]
Thanks @richardbarad we documented this workflow in ticket #608
