### ISSUE TITLE
Layers from biodiversity group do not load in Georgia atlas in language=ka.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#488]
**Workflow to replicate:**

1) Open Georgia app in Georgian: https://atlas.mepa.gov.ge/maps/map

2) Clear all layers:

3) Turn on all the layers in the biodiversity group, which is the 4th group called: "ბიომრავალფეროვნება" in Georgian.

![Biodiversity_Layers](https://user-images.githubusercontent.com/40440743/62497060-d48e6000-b7a8-11e9-86b9-5018b8cc3920.png)

4) Click the share button and copy the url into a new tab:

5) In the resulting map, none of the biodiversity layers are turned on, but they do show up in the legend and are turned on in the layer panel:

![2019-08-05 17_47_19-ტყისა და მიწათსარგებლობის ატლასი](https://user-images.githubusercontent.com/40440743/62497162-23d49080-b7a9-11e9-91b0-090aa36c05b2.png)

**Comment by SwampGuzzler** [comment]
@richardbarad Check out this build on [alpha](http://alpha.blueraster.io/gfw-mapbuilder/488-georgia-group-load/) to see the `share` functionality in action!

**Comment by SwampGuzzler** [comment]
(and don't mind the `loader` in the upper left, we were just playing around with some options)

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good and ready to merge!
