### ISSUE TITLE
When you have a layer set to true it always shows up when sharing.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#489]
When you have a layer set to true it allways shows up when sharing.

1) To replicate, load the georgia app: https://atlas.mepa.gov.ge/maps/map?l=en

2) Turn off all layers

3) Copy the share url into a new browser.

The protected areas layer, and tree cover loss layers will be turned on because they are set to `visible:true` in the configuration file.

**Comment by SwampGuzzler** [comment]
Let's test here for sharing @csphang http://alpha.blueraster.io/gfw-mapbuilder/489-share-layer-visibility/

**Comment by SwampGuzzler** [comment]
Since I haven't heard anything from @csphang I guess its good for you to test @richardbarad !

**Comment by csphang** [comment]
Yep - looked good when testing English & Georgian in the App. I noticed the map flashes several times when loading the share URL, but the layer visibility shows up correctly.

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good! Is there a quick fix to address the flashing issue? I noticed it in the build you posted here as well: https://github.com/wri/gfw-mapbuilder/issues/348

**Comment by SwampGuzzler** [comment]
@richardbarad @csphang Updated to no more _flashes_ ! Same URL!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good!
