### ISSUE TITLE
Share functionality is not working in new build.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#493]
In this build http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/

if I 

1. Turn on some layers
2. Click share

The share box does not include a link. See screenshot below:

![image](https://user-images.githubusercontent.com/40440743/62807646-d6fffb00-bac3-11e9-909b-f71eda2fe7ed.png)

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

I couldn't replicate this issue. I tried in both Chrome as well as Edge. See screen recordings (Sorry for the lag in the Edge example as I was doing it via BrowserStack):

http://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/493-screen-recordings/Screen%20Recording%202019-08-12%20at%2011.43.27%20AM.mov

http://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/493-screen-recordings/Screen%20Recording%202019-08-12%20at%2011.45.34%20AM.mov

Although, I did notice the positioning of the social media buttons was off in Edge as you'll see in the screen recording, so I fixed that with this new build:

http://alpha.blueraster.io/gfw-mapbuilder/493-share-functionality/

@csphang , could you also test this out with the above build and see if you can replicate the issue of the link not showing up?

**Comment by KaylaKremer** [comment]
@richardbarad , Actually I was able to replicate the issue, so please ignore my earlier comment. I will be taking a look at this tomorrow.

**Comment by KaylaKremer** [comment]
@richardbarad 

Build with the fix for the share modal: http://alpha.blueraster.io/gfw-mapbuilder/493-share-modal/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good! Thanks!
