### ISSUE TITLE
The download buttons in report are not opening in correct location.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#494]

**Comment by richardbarad** [comment]
In the new report, If I click the download button for a widget the download dropdown opens up on the far right hand side of the page instead of opening directly below the download icon in the report. 

![image](https://user-images.githubusercontent.com/40440743/62807863-889f2c00-bac4-11e9-86e1-41b3c0bdf602.png)

**Comment by KaylaKremer** [comment]
@richardbarad , I forgot a `max-width` for the download options, sorry about that! PR is up that fixes this, and I'll try to get you new consolidated builds here soon posted on Slack with other fixes for you to review when you're back next week!

**Comment by richardbarad** [comment]
@KaylaKremer. This looks good! Thanks!
