### ISSUE TITLE
Add tree cover density svg

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#500]
![2019-08-19_17-31-10](https://user-images.githubusercontent.com/13664037/63300863-2d7cee80-c2a7-11e9-94e1-176dd7388ff9.png)
![2019-08-19_17-30-26](https://user-images.githubusercontent.com/13664037/63300864-2d7cee80-c2a7-11e9-80c9-486838232ae5.png)

**Comment by KaylaKremer** [comment]
@csphang @richardbarad 

Test build: http://alpha.blueraster.io/gfw-mapbuilder/500-add-tree-cover-density-svg/

**Comment by csphang** [comment]
@KaylaKremer Verified across browsers

![2019-08-20_14-28-45](https://user-images.githubusercontent.com/13664037/63374026-f9610680-c356-11e9-980e-694755bd627c.png)
