### ISSUE TITLE
Investigate Liberia missing attribute table

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#501]
### Steps to reproduce
1. Load http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/liberia-forest-atlas/

2. **Select any poly** on the map.

3. Select **analysis**, and **run report**

The name of the area shows up, but the attribute table is missing. This is the only country consolidated build I saw this behavior.

![2019-08-19_17-34-56](https://user-images.githubusercontent.com/13664037/63301096-b7c55280-c2a7-11e9-9106-356fec3b8a5f.png)
![2019-08-19_17-34-30](https://user-images.githubusercontent.com/13664037/63301097-b7c55280-c2a7-11e9-8f04-8868f658931d.png)

**Comment by KaylaKremer** [comment]
@csphang 

Looks like the `query` fails for some reason with this one, which is why it never gets the report table. 

@SwampGuzzler , I took a screenshot of where it's failing in `ReportTable.js`

![Screen Shot 2019-08-20 at 3 47 36 PM](https://user-images.githubusercontent.com/22095244/63379330-1949f780-c362-11e9-833e-8035cb6138d1.png)

**Comment by csphang** [comment]
@SwampGuzzler @KaylaKremer It looks like the query call that's failing is missing the name of the layer in the URL?

Query URL: https://gis.forest-atlas.org/server/rest/services/lbr/forest_atlas/MapServer/dynamicLayer/query?f=json&where=objectid%20%3D%20124&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*

![2019-08-21_11-34-35](https://user-images.githubusercontent.com/13664037/63446294-f40fc480-c407-11e9-9c5b-8a9889a9413c.png)

**Comment by KaylaKremer** [comment]
@csphang Good catch! Yes, I think it should be. @SwampGuzzler , can you confirm?

**Comment by richardbarad** [comment]
@KaylaKremer. This was addressed by the Liberia forest atlas manager! The map no longer uses dynamic layers!
