### ISSUE TITLE
Display only selected AOI name in the report

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#508]
![2019-08-20_14-46-57](https://user-images.githubusercontent.com/13664037/63445718-e0179300-c406-11e9-942c-5bea72f6eed7.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a test build for this ticket: http://alpha.blueraster.io/gfw-mapbuilder/508-display-only-selected-AOI/

**Comment by richardbarad** [comment]
@KaylaKremer. This feature is working fine, but it looks like the report is showing the wrong analysis modules! We see the deafualt analysis modules instead of the custom Ethiopia ones.

**Comment by csphang** [comment]
@richardbarad The analysis modules work in the consolidated Ethiopia build, so if possible, we'd love to wait to retest the analysis modules once all the branches are merged. We've flagged this as an important item to test for the updated consolidated build.
