### ISSUE TITLE
Merge all features and create consolidated builds

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#509]
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/tierras-indigenas/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/liberia-forest-atlas/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/fluids-georgia/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/ethiopia/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/atlas-forestier-rdc/
- http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/atlas-forestier-cameroun/

**Comment by richardbarad** [comment]
Reviewed using this appid and bugs/issues noted on github: http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/?appid=277b92455c6c49059a95c9129be7baf9&l=en

**Comment by KaylaKremer** [comment]
@richardbarad ,

I've updated all the builds. It should contain all the tickets minus the satellite imagery and fires bug since those issues are outside of the new report build design.

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! I'll go through the testing workflow this week and make sure we are all set to go!
