### ISSUE TITLE
Improved UI for measurement tool

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#510]
![2019-08-20_16-35-44](https://user-images.githubusercontent.com/13664037/63382554-f4a54e00-c368-11e9-9ffb-5cc5c04d18ec.png)

![2019-08-20_16-36-47](https://user-images.githubusercontent.com/13664037/63382553-f4a54e00-c368-11e9-922d-4d4a7af5bdec.png)

**Comment by KaylaKremer** [comment]
@richardbarad 
Test build: http://alpha.blueraster.io/gfw-mapbuilder/510-measure-playground/

**Comment by KaylaKremer** [comment]
@richardbarad ,

Please check out the build in #458 since it combines this as well as the new measurement tool redesign!

**Comment by KaylaKremer** [comment]
@richardbarad I guess this ticket can be closed out as well since it's been absorbed by #458 ?

**Comment by richardbarad** [comment]
@KaylaKremer. Yes, we can close!
