### ISSUE TITLE
ESRI World Database Search functionality not working in 1.4.1

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#517]
The Search functionality using ESRI World database is not working in builds using 1.4.1.

If I:

1) Open this build: http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/?appid=277b92455c6c49059a95c9129be7baf9&l=en

2) Click on the search button

3) Type Washington, DC, USA or Rome, Italy I do not zoom to the point of interest.

4) Instead, MapBuilder seems to try to select a feature and opens the data tab.

I tested across a few different builds here: https://github.com/wri/gfw-mapbuilder/issues/509

Attaching a video of the workflow as well. 

[Search_Bug.zip](https://github.com/wri/gfw-mapbuilder/files/3556190/Search_Bug.zip)

**Comment by KaylaKremer** [comment]
@richardbarad 

Here's a build for you test: http://alpha.blueraster.io/gfw-mapbuilder/517-search-functionality-not-working/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good. thanks!
