### ISSUE TITLE
Filtering by Custom Date range for fires is not working.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#519]
In this build: http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/?appid=277b92455c6c49059a95c9129be7baf9&l=en

if I:

1) Turn on VIIRS or MODIS

2) Click custom range

3) Modify the start and end date to a custom range using the calendar

The map does not update and still shows fires from the past 24 hours. This was working in 1.4.0 so maybe related to updates made on: https://github.com/wri/gfw-mapbuilder/issues/406

**Comment by KaylaKremer** [comment]
@richardbarad I do think this is related to #406. Lucas and I think we've narrowed down the issue with #406. I'll be continuing working on both of these tickets today.

**Comment by SwampGuzzler** [comment]
@richardbarad  This is is test-able at http://alpha.blueraster.io/gfw-mapbuilder/519-fires-custom-range/ !

**Comment by richardbarad** [comment]
Tested! Looks good!
