### ISSUE TITLE
Adjust height of TCD Slider in report.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#520]
Can we adjust the height of the TCD Slider slightly so that the user does not need to use the scroll bar to see and adjust the TCD values? See screenshot below!

**Comment by richardbarad** [comment]
![image](https://user-images.githubusercontent.com/40440743/63958034-8e4eb880-ca57-11e9-8881-02ed163ccd5b.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a build for this ticket! http://alpha.blueraster.io/gfw-mapbuilder/520-adjust-height-tcd-slider/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good!
