### ISSUE TITLE
Recent Imagery does not automatically load.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#527]
If I:

1. Turn on the recent imagery

2. The modal opens but the first image no longer loads automatically and I have to click on an image to get it to load.

Note that this bug does not happen consistently, and only seems to occur about 50% of time. We implemented a temporary workaround on ticket https://github.com/wri/gfw-mapbuilder/issues/483 which was to 

1. Show the Recent Imagery window each time the loader hides and the calls for the imagery thumbnails have completed.

2. Added a little instruction text above the images that only shows when the image has not loaded properly on the Map.

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
