### ISSUE TITLE
Investigate why MapBuilder is not loading in the CMS

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#532]
I added v1.4.1 to the CMS on staging and the maps which use that version are not loading! 

http://blueraster.teaches-yoga.com/CMR?l=en & http://richard.teaches-yoga.com/map. There is an error in the console which is shown below and it looks like it originates in the MapBuilder code. Could you please investiage?

![Mapbuilder_error](https://user-images.githubusercontent.com/40440743/64823928-aad60f00-d586-11e9-9ecf-202bc0609d3b.png)

**Comment by SwampGuzzler** [comment]
@richardbarad Updated! Check those builds out again to see the fix.

I do have a question for the CMS folks however - how is their html being created? The issue arises from trying to add the **Loader** to the `body` of the `html` page, which apparently doesn't exist! I might pursue this flow soon if we don't have any HTML to append things to.

**Comment by SwampGuzzler** [comment]
@SwampGuzzler Should we be using `root.nextSibling` or `root.nextElementSibling` per @KaylaKremer 's Demands?!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks like it is still failing. 

I can send a message to CMS folks with your question above and sharing the failing links if that is useful.

Best,

Richard

**Comment by richardbarad** [comment]
@SwampGuzzler & @KaylaKremer,

Looks like the map is loading now, but we are seeing some unsual issues:

1. The header of the CMS is flashing
2. When you turn a layer on, or off, or pan in the map it flickers.

I am attaching a video of what I see on my side.

[Map_flickering.zip](https://github.com/wri/gfw-mapbuilder/files/3610630/Map_flickering.zip)

**Comment by SwampGuzzler** [comment]
This has been addressed in production!
