### ISSUE TITLE
MapBuilder new report is not loading in CMS in version 1.4.1

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#533]
The report does not load here: http://blueraster.teaches-yoga.com/CMR/report.html?title=Blue%20Raster%20Site&subtitle=Minist%C3%A8re%20des%20For%C3%AAts%20et%20de%20la%20Faune&logoUrl=https%3A%2F%2Fcmr.forest-atlas.org%2Fsystem%2Fsite_settings%2Fimages%2F000%2F000%2F094%2Foriginal%2FCAMEROON.png%3F1487267590&logoLinkUrl=http%3A%2F%2Fwww.minfof.cm%2F&activeSlopeClass=undefined&webmap=6142e76453354c0b83633370e6a6f006%20&idvalue=f35e4c2322d0f2d53b4f1af95261e0cc&tcd=30&lang=fr&activeLayers=USER_FEATURES%2Catlas_forestier_fr_3504_73%2Catlas_forestier_fr_3504_70%2Catlas_forestier_fr_3504_69%2Catlas_forestier_fr_3504_68%2Catlas_forestier_fr_3504_65%2Catlas_forestier_fr_3504_67%2Catlas_forestier_fr_3504_66%2Catlas_forestier_fr_3504_61&tcLossFrom=0&tcLossTo=17&gladFrom=2015-01-01T05%3A00%3A00.000Z&gladTo=2019-09-13T15%3A38%3A47.188Z&terraIFrom=2004-01-01&terraITo=2016-07-12&viirsStartDate=2019-09-12%2011%3A38%3A47&viirsEndDate=2019-09-13%2011%3A38%3A47&modisStartDate=2019-09-12%2011%3A38%3A47&modisEndDate=2019-09-13%2011%3A38%3A47&customFeatureTitle=Custom%20Feature%20%231&selectedFeatureTitles=&sharinghost=https%3A%2F%2Fwww.arcgis.com&activeFilters=&activeVersions=&IFL=16&atlas_forestier_fr_3504=63%2C59%2C61%2C66%2C67%2C65%2C68%2C69%2C70%2C71%2C73%2C74&MODIS_ACTIVE_FIRES=21&VIIRS_ACTIVE_FIRES=21&cache=1.4.1&origin=http%3A%2F%2Fblueraster.teaches-yoga.com

**Comment by SwampGuzzler** [comment]
@richardbarad This has been addressed at that url! Per our discussion, the two `<div>` elements with unique `id` attributes have been **Removed** in the CMS Report page! There is currently a code fix in there to figure out where in the DOM to attach all of our Report components, but we want those two `<div>`'s back in there - the `id`'s that we care about are `report` and `share-modal`
