### ISSUE TITLE
The share button does not work in v1.4.1 when using base configuration.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#542]

**Comment by richardbarad** [comment]
The share button does not work in `v1.4.1`. It is not working at the link below both with & without and appid:

https://my.gfw-mapbuilder.org/v1.4.1/?appid=277b92455c6c49059a95c9129be7baf9
https://my.gfw-mapbuilder.org/v1.4.1/

However, it is working in the CMS in a build which uses` v1.4.1`

http://blueraster.teaches-yoga.com/CMR?l=en

**Comment by SwampGuzzler** [comment]
@csphang just told me nope, we do not. We'll remember the cache anytime we update `production`

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good! I'll ask Thomas to give you and @csphang permissions to clear the cache on production to make testing production updates easier. We have to caches, one for `my.gfw-mapbuilder.org` and one for `https://library.gfw-mapbuilder.org/`.

Richard
