### ISSUE TITLE
The option to download GLAD alerts as .csv is showing up on month chart.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#548]
The option to download GLAD alerts as a .csv is showing up on the monthly chart here: https://my.gfw-mapbuilder.org/v1.4.1/?appid=277b92455c6c49059a95c9129be7baf9 It should only be visible on the badge chart.

![image](https://user-images.githubusercontent.com/40440743/65359676-3ffe8680-dbcb-11e9-98bf-f84bd1d6dc7c.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a build for this ticket! http://alpha.blueraster.io/gfw-mapbuilder/548-remove-csv-download-glad/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good, and ready to be merged into v1.4.1 production!
