### ISSUE TITLE
In the CMS, custom country analysis are not showing up in report when using v1.4.1.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#551]
When using `v1.4.1` in the CMS the analysis report loads the global analysis, instead of loading country analysis. 

For example, the Georgia and Liberia builds both include custom country analysis:
1. http://blueraster.teaches-yoga.com/LBR?l=en
2. http://blueraster.teaches-yoga.com/GEO?l=en

In both cases, the custom country analysis is missing from the report. For Liberia, we have a land cover analysis which uses local Land Cover data instead of the global data. For Georgia, we have several additional analysis (Slope, Elevation, Aspect, and hazard risk) which are not showing up in the report. I assume the same issue would also be present for Ethiopia but was unable to test due to issue: https://github.com/wri/gfw-mapbuilder/issues/550.

**Comment by SwampGuzzler** [comment]
@richardbarad You can test this now at Both of those `BR-teaches-yoga` URL's *right now*!!

**Comment by SwampGuzzler** [comment]
https://github.com/wri/gfw-mapbuilder/pull/558 @KaylaKremer

**Comment by richardbarad** [comment]
@SwampGuzzler. Tested and this looks good. Seems like the update was already merged into `v1.3.4`?
