### ISSUE TITLE
Formatting issue in CMS with the new draw shape by entering coordinate tool.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#552]
http://blueraster.teaches-yoga.com/CMR?l=fr

![2019-09-23 14_39_39-Blue Raster Site](https://user-images.githubusercontent.com/40440743/65453139-94467800-de10-11e9-88a8-b80c88304cbc.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

For this ticket, I found what is causing the issue and can easily fix it, but I was curious as to why the CSS styling rules seem to be different in the CMS and is overwriting ours? (See screenshots)

<img width="1435" alt="Screen Shot 2019-09-23 at 7 25 28 PM" src="https://user-images.githubusercontent.com/22095244/65470198-1c8c4380-de38-11e9-961a-679e6bd8429d.png">

<img width="1427" alt="Screen Shot 2019-09-23 at 7 25 43 PM" src="https://user-images.githubusercontent.com/22095244/65470199-1c8c4380-de38-11e9-9a0e-1c7300d3b437.png">

I'm worried that even if I edit the styles, there still going to be overwritten by the CMS.

**Comment by richardbarad** [comment]
@KaylaKremer. Good question! I'll try to answer it as best as I can.

The CMS allows the user to add custom map HTML directly in the CMS, which overwrites the styling from MapBuilder. The custom HTML is added in Admin section of the CMS, which @csphang has access to on staging and is accessible at this url: http://blueraster.teaches-yoga.com/admin/map_versions/. When you click the edit button for a map version you are able to specify HTML and also the default configuration for that MapBuilder version. For the default configuration, we use our base configuration from `http://my.gfw-mapbuilder.org/v1.4.1/`, but in a JSON syntax.

The HTML field in the CMS was left over from before we centrally managed all of the MapBuilder CSS/HTML via the javascript file as we used to load some of the CSS/HTML directly in HTML map page. However, we ran into issue with the metadata pop-up window in MapBuilder in the CMS and my colleague who used to work on MapBuilder wrote some custom HTML to address the formatting issues with the metadata popup window in the CMS. I am attaching the HTML which he prepared for your reference, and I believe this HTML is overwriting the styles from MapBuilder. 

So that you can see this in action, I created a new version of the `1.4.1` code and called it `1.4.1.0` and added it on S3 and in the CMS as a new version. In this version, I did not overwrite the HTML/CSS which comes from MapBuilder. This map: http://blueraster.teaches-yoga.com/CMR?l=fr is pointing to `1.4.1.0 `. We can see that the draw coordinate tool is styled correctly and the modal width matches what we have in our standard MapBuilder. However, we have an issue with the metadata formatting as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/40440743/65477819-794a2700-de55-11e9-93c6-54bde6b7a3b6.png)

Thus, I think we have a few options:

1) **Fix** the styling issue on the metadata pop-up in the CMS and `STOP` overwriting the CSS/HTML in the CMS.

2) Continue overwriting the CSS/HTML rules to address the issue with the metadata pop-up, and implement a fix MapBuilder side to address the issue identified in this task.

I think I would actually prefer option 1 if it is an easier fix! I believe we looked into this a bit in a previous phase here and discussed this in this ticket which is now in the backlog: https://github.com/wri/gfw-mapbuilder/issues/338

Open to suggestions or recommendations, since you are much more familiar with the MapBuilder HTML/CSS than I am. Let me know if you have any questions or need additional information! The Vizzuality team also seems willing to answer any questions we might have about the interactions between the CMS & MapBuilder.

[MapBuilder_HTML.zip](https://github.com/wri/gfw-mapbuilder/files/3645045/MapBuilder_HTML.zip)



Best,

Richard

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks there is probably a 3rd option which would be to update the HTML/CSS in the CMS. However, I agree that option 1 is probably best.

**Comment by KaylaKremer** [comment]
@richardbarad ,

I created a new CMS build using version `1.3.5` that I just made since trying to use your `1.4.1.0` wasn't working for me when I tried to make a build (I think the extra number was causing issues).

Please check it out now and let me know what you think! http://blueraster.teaches-yoga.com/CMR?l=en

**Comment by richardbarad** [comment]
@KaylaKremer. I tested in the CMS using `1.3.5` and this bug looks good! 

Note that I copied in the HTML we had in the CMS previous to address the metadata pop-up window. However, it looks like the cms is no longer overwriting the HTML from MapBuilder when I use `1.3.5` which is resulting in issues with the metadata pop-up window as shown below. Did you change something on your side? I also tried deleting your Map version and recreating it. 

![image](https://user-images.githubusercontent.com/40440743/65637693-a6601c00-dfb2-11e9-94e5-b1ae52ba4555.png)

**Comment by KaylaKremer** [comment]
@richardbarad , I didn't copy over the HTML from `1.4.1.0` for `1.3.5` so maybe that is why?

If the only thing the HTML addresses is fixing this particular meta pop-up modal window, then I can go ahead and fix it on my side so that it only makes this modal wider, but leaves the other modals as is.

**Comment by richardbarad** [comment]
@KaylaKremer. I went ahead and copied over the HTML from `1.4.1` to `1.3.5`, but it looks like the HTML styles in `1.3.5` are still coming from MapBuilder instead of using what is in the CMS. I can try to investigate further tomorrow, but just wanted to make sure nothing changed in `1.3.5` which would prevent the CMS from overwriting the HTML from MapBuilder. 

Yes, the HTML we add in the CMS is fixing the metadata pop-up window. If it is an easy fix the ideal situation would be to fix it on your side so that we do not need to overwrite the HTML in the CMS.

**Comment by richardbarad** [comment]
@KaylaKremer. I investigated a little further and think I see the issue, in `1.3.5` there is some additional CSS coming from MapBuilder which is marked as `!important` as thus the CMS can not overwrite it. See screenshoots below:

I see two options:

1) Remove the `!important` from the CSS which comes from MapBuilder unless you think this might result in issues in other places

2) Implement a fix for the metadata modal in MapBuilder so that we do not have to overwrite the CSS.

Long-term, number 2 would be preferable but fine with number as a quick fix for purposes of this release.

Version 1.3.5:
http://blueraster.teaches-yoga.com/CAR?l=en
![1 3 5](https://user-images.githubusercontent.com/40440743/65645836-0e206200-dfc7-11e9-855e-930983ee6d14.PNG)

Version 1.4.1
http://blueraster.teaches-yoga.com/CAR?l=en
![1 3 4](https://user-images.githubusercontent.com/40440743/65645827-082a8100-dfc7-11e9-83b3-8ebc06e27260.PNG)

**Comment by KaylaKremer** [comment]
@richardbarad 

Nothing changed in `1.3.5` that would prevent the CMS from overwriting.

I went ahead and went with option #2 to fix the modal size only for the meta window. The `!important` in the CSS was added due to the CMS overriding the styles. Adding `!important` is the only way I can override if we are to leave in this extra CMS styles in.

If you go ahead and remove it, then everything should be fixed and worked just fine. I went ahead and updated the build: http://blueraster.teaches-yoga.com/CMR?l=en .

**Comment by richardbarad** [comment]
@KaylaKremer. I just removed the extra HTML from the CMS in version `1.3.5`. However, it looks like there is still a small formatting issue in the metadata pop-up window as the text extends beyond the modal. Please see screenshot below showing what this looks like for metadata coming from GFW & metadata coming from ArcGIS Server. Screenshoots taken using this link:

http://blueraster.teaches-yoga.com/CMR?l=fr

ArcGIS Server:

![image](https://user-images.githubusercontent.com/40440743/65698961-57b29080-e04b-11e9-80a3-6a2369e907ad.png)

GFW:

![image](https://user-images.githubusercontent.com/40440743/65699059-8597d500-e04b-11e9-9e05-d80a507038d8.png)

**Comment by KaylaKremer** [comment]
@richardbarad Thanks for removing!

I just updated it again. Hopefully this is the last change needed to fix this modal! http://blueraster.teaches-yoga.com/CMR?l=fr

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good! Can you please merge into `1.4.1` and then delete the `1.3.5` from S3?

**Comment by KaylaKremer** [comment]
@richardbarad Great! And sure thing!

**Comment by KaylaKremer** [comment]
@richardbarad `1.3.5` has been removed and I've merged everything into `1.4.1` and updated it on WRI's server.
