### ISSUE TITLE
Minor formatting issues with imagery modal.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#553]
Minor formatting issues with imagery modal in the CMS. The space allocated to the thumbnails and the scroll bar extends beyond the space allocated to the modal.

This bug is only visible when the **"select an image once imager is available" text is visible in the CMS**.

![Imagery_Modal](https://user-images.githubusercontent.com/40440743/65454887-16846b80-de14-11e9-8793-d778c83d5e1d.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Build for you to test: http://alpha.blueraster.io/gfw-mapbuilder/553-imagery-modal-adjustment/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good and ready to be merged into v1.4.1 production.
