### ISSUE TITLE
After toggling language, coordinates in the lower right corner stop changing when panning.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#564]
If you go through the following workflow:

1) Open this app: https://my.gfw-mapbuilder.org/v1.latest/?appid=277b92455c6c49059a95c9129be7baf9

2) Change the language to French.

3) The coordinates in the lower left hand corner stop changing when you pan around the map.

I am attaching a video of this.

[cordinate_bug.zip](https://github.com/wri/gfw-mapbuilder/files/3686745/cordinate_bug.zip)

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
