### ISSUE TITLE
If you turn a layer off, print, then turn a widget back it does not load in report

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#565]
**If I:**

1) Load a report using: https://my.gfw-mapbuilder.org/v1.latest/?appid=277b92455c6c49059a95c9129be7baf9

2) Toggle a widget off using the toggle function

3) Click print to print the report

4) Turn on the widget which was turned off, the widget is no longer visible

Attached is a video of this workflow.
[print_bug.zip](https://github.com/wri/gfw-mapbuilder/files/3686989/print_bug.zip)

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
