### ISSUE TITLE
Styling issues with edit buttons in French apps

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#576]
There are some styling issues when viewing an application in French. 

For example, this app: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-redesign/

If you go through the following workflow:

1) Draw a shape

2) Go to the data tab

The edit/delete buttons extends beyond the layer panel as shown below, and a grey scroll bar is visible.

![image](https://user-images.githubusercontent.com/40440743/66348375-668b2400-e924-11e9-9d86-a4ccf02b95aa.png)

The same issue is present on the analysis tab, except the scroll bar is not visible.

![image](https://user-images.githubusercontent.com/40440743/66348401-76a30380-e924-11e9-9d4f-d24b41021204.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a build for you to review: http://alpha.blueraster.io/gfw-mapbuilder/576-fix-styling-issues-for-french-apps/

The issue btw is that text inside the buttons caused it to extend. I now have it set up to wrap to the next line if it's too long and center align it. Hope this is ok for you!

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good. Thanks!
