### ISSUE TITLE
Document new basemap logic in wiki. Let's document it in the configuration section of wiki.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#584]
Please doucment:

- ESRI Basemaps we support

- WRI Basemaps we support

- Workflow for using your own custom basemap.

I will also add documentation to the page on how to make a WRI Basemap the default

**Comment by csphang** [comment]
@richardbarad let me know your thoughts on this first draft of documentation!

## Basemaps
### Esri Basemaps
GFW MapBuilder supports a variety of Esri Basemap choices. Currently supported basemaps include: 

1. Topographic
2. Imagery
3. Imagery with labels
4. Streets
5. Dark gray canvas
6. Light gray canvas
7. National Geographic
8. Terrain with labels
9. Oceans
10. OpenStreetMap
11. USGS national map
12. USA topo maps

### WRI Basemaps
GFW MapBuilder supports two WRI Basemaps:

1. WRI Mono basemap
2. WRI Contextual basemap

### Using Your Own Basemap
In addition to the Esri and WRI basemaps, you can also use your own custom basemap.

Workflow
1. Create an ArcGIS Online Web Map that uses your desired basemap.
2. In the GFW MapBuilder resources file, update the property `useWebmapBasemap: true`

**Comment by csphang** [comment]
Documented in wiki at: https://github.com/wri/gfw-mapbuilder/wiki/Basemap

**Comment by richardbarad** [comment]
![basemap](https://user-images.githubusercontent.com/40440743/67237475-53df1780-f419-11e9-8f4d-e9fa12cb16a2.png)
