### ISSUE TITLE
Update size limit for shapefile upload service.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#585]
The recomended size limit on flagship is 1MB. We list the recommended size as 5MB. Please update to 1MB in all languages!

![image](https://user-images.githubusercontent.com/40440743/66661970-eca1b600-ec15-11e9-8173-35cbf8369594.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Test build: http://alpha.blueraster.io/gfw-mapbuilder/585-update-shapefile-text/

**Comment by richardbarad** [comment]
@KaylaKremer. Based on your commit https://github.com/wri/gfw-mapbuilder/pull/589/commits/90a34edd0214c40fec342ebfa61fc2be99d37429
it looks like the Georgian text is not updated. Could you please make sure this is updated? 
Thanks!

**Comment by KaylaKremer** [comment]
@richardbarad , good catch! Georgian was the only language that doesn't have 'MB' in it, so my find and replace missed it!

I just resubmitted a PR to fix it.
