### ISSUE TITLE
In spanish draw shape text is not visible

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#586]
In Spanish, draw shape is not visible due to length of text.

![image](https://user-images.githubusercontent.com/40440743/66666352-69389280-ec1e-11e9-91b9-29a3468eedab.png)

http://forum-florestal.doesntexist.org/Mapa2

**Comment by KaylaKremer** [comment]
@richardbarad 

Test build: http://alpha.blueraster.io/gfw-mapbuilder/586-fix-spanish-text-in-button/
