### ISSUE TITLE
Check to see if Vector Basemaps will work with new custom Basemap feature.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#590]

**Comment by csphang** [comment]
@richardbarad I tested using Vector Tiles as a basemap, as well as a layer. In both instances, there is poor performance. There is a delay of ~1-2 minutes before the vector tiles load in. I've setup an example build here: http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/vector-basemap/

**Comment by richardbarad** [comment]
@csphang. Let's document this in the documentation on basemaps and note that ESRI vector basemaps are currently not supported.
