### ISSUE TITLE
[Measurement Tool]: Appears twice in popup after switching languages

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#599]
1. Load http://blueraster.teaches-yoga.com/CMR?l=en
2. Switch language
3. Click on measurement tool

**Comment by SwampGuzzler** [comment]
@csphang Great find - test here and once confirmed, we'll get it into the CMS asap
http://alpha.blueraster.io/gfw-mapbuilder/measurement-multi-lang-fix/?l=en

**Comment by csphang** [comment]
@SwampGuzzler Confirmed the issue is resolved!

**Comment by SwampGuzzler** [comment]
@csphang This looks good in the CMS as well now
