### ISSUE TITLE
[Language Toggle]: Country mask not retained

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#600]
1. Load http://blueraster.teaches-yoga.com/CAR?l=en
2. Switch language 
3. Note that the map loads, but the mask is not present.
4. Refresh browser, and you'll see the mask loads

**Comment by SwampGuzzler** [comment]
@csphang I can't reproduce this `issue`!

**Comment by csphang** [comment]
Tested and confirmed that the mask is working appropriately! marking as resolved.
