### ISSUE TITLE
[Info window]: Indexing off

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#601]
1. Load http://blueraster.teaches-yoga.com/gab?l=en
2. Select one of the pink polygons (ensure you have 2+features returned from the hit test)
3. Click through all features through to the end. Then click previous button to go all the way. Then Click all the way through.
4. Indexing will be off by 1. For ex: 6/1

**Comment by KaylaKremer** [comment]
@csphang Test Build: http://alpha.blueraster.io/gfw-mapbuilder/info-window-debugging/

**Comment by csphang** [comment]
@KaylaKremer The indexing issue is totally resolved! But I noticed the attribute table height is super tiny in this test build: http://alpha.blueraster.io/gfw-mapbuilder/info-window-debugging/

Let me know if I should close this and open a separate ticket for that? Or if we address the height as part of this ticket

![2019-10-18_13-54-16](https://user-images.githubusercontent.com/13664037/67116701-fcd60a00-f1ae-11e9-9090-8129121b69b3.png)

**Comment by KaylaKremer** [comment]
@csphang Lucas actually pointed out this issue to me this morning and we fixed it already!

**Comment by csphang** [comment]
Ok great! I will mark this as reviewer approved then
