### ISSUE TITLE
[Radio button group]: radio button fill color missing

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#602]
1. Load http://blueraster.teaches-yoga.com/GEO?l=en
2. In `Hazards` category, select any of the radio button layers
3. The layer turns on, but the radio button doesn't fill color to indicate the layer is active

**Comment by KaylaKremer** [comment]
@csphang 
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/602-radio-button-fill-color-missing/

**Comment by csphang** [comment]
@KaylaKremer does the radio button group data load for you in the test build? The radio buttons do turn on yellow now, but the data doesn't load for me. http://alpha.blueraster.io/gfw-mapbuilder/602-radio-button-fill-color-missing/
