### ISSUE TITLE
[Measurement Tool]: double check that language translation is propagating

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#605]
@KaylaKremer can you double check that the measurement tool's language translations are coming through? 

Test Build: http://alpha.blueraster.io/gfw-mapbuilder/measurement-multi-lang-fix/?l=fr

Seeing `Measurement` when it should display `Mesure`

![2019-10-18_11-21-40](https://user-images.githubusercontent.com/13664037/67107156-e4a7c000-f199-11e9-9ddc-9e93eac037e2.png)

**Comment by richardbarad** [comment]
@csphang. Just going through the backlog, and I am moving this to v1.4.2 since it is related to the measurement tool which part of current phase. 

Let me know if there are issues with adding measurement translations as part of current phase.

**Comment by csphang** [comment]
Hi @richardbarad, since we are using the Esri Measurement widget, the location language will be picked up from the browser settings. I moved this to backlog after talking with Lucas and Kayla about this!

**Comment by richardbarad** [comment]
@csphang. Thanks for the clarification. Moving back to backlog.

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
