### ISSUE TITLE
Fire Layer Creation Breaks on language-toggle

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#608]
### Subject of the issue
In countries that support multiple languages, switching languages breaks in the `layerFactory`'s creation of multiple `fires` layers

### Steps to reproduce
http://blueraster.teaches-yoga.com/CMR?l=fr (including the `language` specification, switch us over to English, and see the **JSON.parse** fail in the console. See the lack of Fires Layers in the map!

### Expected behaviour
Normal JSON parses! This is failing due to the `esriLayer` property from the last map (in French)

### Actual behaviour
We fail to parse that `loco` esriLayer property!

**Comment by SwampGuzzler** [comment]
@KaylaKremer See the last couple commits from [this branch!](https://github.com/wri/gfw-mapbuilder/tree/fires-layers-creation-lang-toggle)

**Comment by KaylaKremer** [comment]
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/fires-layers-creation-lang-toggle/

**Comment by csphang** [comment]
@KaylaKremer switching languages works, BUT! If I custom select a date range and then toggle languages, the fires default back to past 24hrs but the layer panel shows my custom date range still.

### Steps to reproduce
1. Load http://alpha.blueraster.io/gfw-mapbuilder/fires-layers-creation-lang-toggle/
2. Turn on MODIS, select custom date range (ex: Oct. 1 - 18)
3. Switch language

**Comment by SwampGuzzler** [comment]
@csphang http://alpha.blueraster.io/gfw-mapbuilder/fires-layers-creation-lang-toggle-fix/ Has an update on the language-change issues!
