### ISSUE TITLE
[Search and Upload Shape]: InfoWindow breaks when using geocoder

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#612]
![image](https://user-images.githubusercontent.com/13664037/67125820-9c9d9300-f1c3-11e9-80bc-f767bc0ea189.png)

### Root cause
We can't assume that all of the features within the infowindow **have** a `_layer` property! We need more check's in that component.

### Use Case 1 [Geocoder]
1. Load http://my.gfw-mapbuilder.org/v1.4.2/?appid=277b92455c6c49059a95c9129be7baf9?l=en
2. Open search, select dropdown for Esri Geocoder, type any address
3. Note that the app freezes and you can't close out of the search box

### Use Case 2 [Upload Shapefile]
1. Go to http://blueraster.teaches-yoga.com/CMR?l=en
2. Click draw > upload this SDR shapefile
3. Notice the analysis panel loads blank white with same error message as use case 1

[sdr_subnational_boundaries_2019-10-18.zip](https://github.com/wri/gfw-mapbuilder/files/3745554/sdr_subnational_boundaries_2019-10-18.zip)

**Comment by SwampGuzzler** [comment]
@csphang I am working on this now - I'll get you a build asap

**Comment by SwampGuzzler** [comment]
@csphang Both workflows are test-able on `alpha!` http://alpha.blueraster.io/gfw-mapbuilder/612-search-info-window/

**Comment by csphang** [comment]
@SwampGuzzler The geocode search is working successfully now!

**Comment by richardbarad** [comment]
@csphang . Noticing that the MapService search based on the display field is not working as well here: http://blueraster.teaches-yoga.com/DRC?l=en

Please make sure that works as well!

**Comment by KaylaKremer** [comment]
@SwampGuzzler I just updated your branch with the changes I had made for #624 and added in additional checks for `._layer`!

https://github.com/wri/gfw-mapbuilder/tree/612-geocoder-search-freeze

**Comment by KaylaKremer** [comment]
@csphang @SwampGuzzler 
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/612-geocoder-search-freeze/

**Comment by csphang** [comment]
@KaylaKremer Let's check in with this -- I'm noticing some items with the build

**Comment by KaylaKremer** [comment]
New build: http://alpha.blueraster.io/gfw-mapbuilder/612-search-info-window/

**Comment by richardbarad** [comment]
@csphang @KaylaKremer.

The following seem to be working in this build:

1) Shapefile upload
2) Search based on ESRI locations and display field (in primary language)

However, I am encountering some issues with the search functionality after translating into the 2nd language. If you:

1) Translate the app
2) Then search for an area (either based on the display field or ESRI geocoder)

The search does not work and an error is returned in the console

![2019-10-24 11_41_28-Window](https://user-images.githubusercontent.com/40440743/67502036-4614d680-f653-11e9-97da-197fb957386c.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a new build for you to test out the language toggle fix: http://alpha.blueraster.io/gfw-mapbuilder/612-search-info-window/

**Comment by richardbarad** [comment]
@KaylaKremer. I am noticing that after you search for an area using the ESRI geocoder or search for a shape based on the display field you see an empty dropdown & the next and previous buttons even though nothing is selected. See screenshots below. Can we hide these since the user has not actually clicked on a shape? 

ESRI Search:

![Yaounde](https://user-images.githubusercontent.com/40440743/67528374-534bb880-f687-11e9-984b-58f6ff9b91c2.png)

Area Search:

![ARea_search](https://user-images.githubusercontent.com/40440743/67528468-88f0a180-f687-11e9-9514-0cb0b50a23fe.png)

When you search for a point using the esri geocoder we may want to hide the print / subscribe buttons as well since you can not run an analysis / subscribe to a point.

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

I've hidden the dropdown and prev/next buttons as well as the footer containing the print and subscribe buttons. The additional text for the area search should still remain as is.

Test Build: http://alpha.blueraster.io/gfw-mapbuilder/612-search-info-window/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good!
