### ISSUE TITLE
Share does not work when only 1 layer of MapService is turned on.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#621]
Testing here: http://blueraster.teaches-yoga.com/CMR?l=fr

1.	Load app in French
2.	Clear all
3.	Turn on VIIRS and Tree Cover Loss and Forest de production layer (from the MapService in the webmap)
4.	Zoom in 1 or two zoom levels.
5.	Copy the share url into a new tab

The result shows all the layers from the MapService instead of just the layers which are turned on. The tree cover loss, fires, and legend are also not visible. I also can not turn on or off the layers. 

Issue happens in both French and English but only occurs when you have layers from webmap group & another group turned on.

![Share_Issue](https://user-images.githubusercontent.com/40440743/67311760-230cea00-f4ce-11e9-985b-e54689c79935.png)

**Comment by SwampGuzzler** [comment]
@csphang Test-able here! http://alpha.blueraster.io/gfw-mapbuilder/621-share-layer/

**Comment by csphang** [comment]
Tested with use case detailed in ticket description - confirmed share functionality works for both French and English. @richardbarad 

Test URL: http://alpha.blueraster.io/gfw-mapbuilder/621-share-layer/

![2019-10-30_14-00-23](https://user-images.githubusercontent.com/13664037/67885435-fab06b80-fb1d-11e9-990e-73b4d8b4bed9.png)

**Comment by richardbarad** [comment]
@csphang. Tested and confirmed this works. However, we now seem to have a bug with the lost layer which I am opening a new ticket for.
