### ISSUE TITLE
Layers set to visible:true are not visible by default.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#622]
The layers which are set to visible true do not load in the map by default. 

This is visible here:

http://blueraster.teaches-yoga.com/Ind?l=en (the Forest and Landscape Restoration Opportunities layer should be visible in the configuration).

![layers_visible](https://user-images.githubusercontent.com/40440743/67314480-b21c0100-f4d2-11e9-8804-f25702450a70.png)

Also visible here: http://blueraster.teaches-yoga.com/GEO?l=en

The tree cover loss, tree cover gain, and protected area layers are all set to visible true in the configuration.

Please compare to production sites as well:

- https://india.restorationatlas.org/atlas
- https://atlas.mepa.gov.ge/maps/map

**Comment by SwampGuzzler** [comment]
@richardbarad This has been updated in the CMS! @csphang Feel free to confirm!

**Comment by richardbarad** [comment]
Still seeing the issue here on my side: http://blueraster.teaches-yoga.com/Ind?l=en

**Comment by richardbarad** [comment]
Working now!
