### ISSUE TITLE
Bug when you click on the next button when multiple layers are selected.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#624]
Follow the workflow below in this app: http://blueraster.teaches-yoga.com/CMR?l=en

1) Click on a point in the map at which multiple features from the same layer come together such as the one show in the screenshot below.
![2019-10-22 14_46_33-Window](https://user-images.githubusercontent.com/40440743/67319339-c82dbf80-f4da-11e9-8b7b-44f3a74dff95.png)

2) Click on the next button in layer panel

The application does not toggle to the next feature and stays on feature 1/2 or 1/3

This was working here when we tested this feature as standalone: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-redesign, so must have been introduced during consolidation of code.

**Comment by KaylaKremer** [comment]
@richardbarad ,

Here's a build for you to test! http://alpha.blueraster.io/gfw-mapbuilder/624-next-button-bug/

**Comment by richardbarad** [comment]
Looks good!
