### ISSUE TITLE
PDF icons are black instead of Orange.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#626]
PDF Icons are black in the staging build on the CMS! Can we make sure it these show up as orange and also gets overwritten when user specifies a custom color theme?

http://blueraster.teaches-yoga.com/CMR?l=fr

![Black_PDF](https://user-images.githubusercontent.com/40440743/67323669-cbc44500-f4e0-11e9-9d55-953e10f7622f.png)

https://cmr.forest-atlas.org/map?l=en

![cmr_PDF](https://user-images.githubusercontent.com/40440743/67323722-dda5e800-f4e0-11e9-8cfd-f8cfa70fb521.png)

**Comment by SwampGuzzler** [comment]
@richardbarad You can test this back on the CMS - @csphang You too!

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good!

**Comment by richardbarad** [comment]
@SwampGuzzler and @csphang. Looks like this is no longer in production. Please make sure this updated is included in 1.4.2.

**Comment by csphang** [comment]
Tested and confirmed this is now in 1.4.2

![2019-11-04_13-55-50](https://user-images.githubusercontent.com/13664037/68148887-dcc27c80-ff0a-11e9-8e8f-6d14801b3af8.png)
