### ISSUE TITLE
Report does not show attribute table when using Cameroon build.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#628]
When using the Cameroon build: http://blueraster.teaches-yoga.com/CMR?l=en

1) Click on a shape in the map
2) Click print report

The resulting report does not show the attribute table. Here is an example report below:

http://blueraster.teaches-yoga.com/CMR/report.html?title=Forest%20Atlas%20of%20Cameroon&subtitle=Ministry%20of%20Forest%20and%20Wildlife&logoUrl=https%3A%2F%2Fcmr.forest-atlas.org%2Fsystem%2Fsite_settings%2Fimages%2F000%2F000%2F094%2Foriginal%2FCAMEROON.png%3F1487267590&logoLinkUrl=http%3A%2F%2Fwww.minfof.cm%2F&activeSlopeClass=undefined&webmap=6142e76453354c0b83633370e6a6f006%20&idvalue=529a2d156d0eae9657b3fe53d2878921&tcd=30&lang=en&activeLayers=USER_FEATURES%2Catlas_forestier_en_9979_0%2Catlas_forestier_en_9979_35%2Catlas_forestier_en_9979_36%2Catlas_forestier_en_9979_37%2Catlas_forestier_en_9979_38%2Catlas_forestier_en_9979_7%2Catlas_forestier_en_9979_33%2Catlas_forestier_en_9979_13&tcLossFrom=0&tcLossTo=17&gladFrom=2015-01-01T05%3A00%3A00.000Z&gladTo=2019-10-22T19%3A43%3A12.666Z&terraIFrom=2004-01-01&terraITo=2016-07-12&viirsStartDate=2019-10-21%2015%3A43%3A12&viirsEndDate=2019-10-22%2015%3A43%3A12&modisStartDate=2019-10-21%2015%3A43%3A12&modisEndDate=2019-10-22%2015%3A43%3A12&customFeatureTitle=Feature%20Analysis&selectedFeatureTitles=Production%20forests%3A%20UFA&sharinghost=https%3A%2F%2Fwww.arcgis.com&activeFilters=&activeVersions=&layerId=https%3A%2F%2Fgis.forest-atlas.org%2Fserver%2Frest%2Fservices%2Fcmr%2Fatlas_forestier_en%2FMapServer%2F13--atlas_forestier_en_9979_13&OBJECTID=898&OBJECTID_Field=forets_production.objectid&IFL=16&atlas_forestier_fr_3504=61%2C66%2C67%2C65%2C68%2C69%2C70%2C71&MODIS_ACTIVE_FIRES=21&VIIRS_ACTIVE_FIRES=21&atlas_forestier_en_9979=30%2C15%2C13%2C33%2C7%2C38%2C37%2C36%2C35%2C34%2C0%2C45&cache=1.4.2&origin=http%3A%2F%2Fblueraster.teaches-yoga.com

**Comment by KaylaKremer** [comment]
@richardbarad 

Test Build: http://alpha.blueraster.io/gfw-mapbuilder/no-attribute-table-cameroon/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good, but the settings to turn the widget on/off is loading in the off position by default.

![Analysis_off](https://user-images.githubusercontent.com/40440743/67499600-63e03c80-f64f-11e9-841f-b5d2c3e7f9f0.png)

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good!

**Comment by richardbarad** [comment]
@KaylaKremer and @csphang . Please check to make sure this update is included in 1.4.2 on production. I am not seeing the update here in the report in the CMS. 

http://blueraster.teaches-yoga.com/CMR/report.html?title=Forest%20Atlas%20of%20Cameroon&subtitle=Ministry%20of%20Forest%20and%20Wildlife&logoUrl=https%3A%2F%2Fcmr.forest-atlas.org%2Fsystem%2Fsite_settings%2Fimages%2F000%2F000%2F094%2Foriginal%2FCAMEROON.png%3F1487267590&logoLinkUrl=http%3A%2F%2Fwww.minfof.cm%2F&activeSlopeClass=undefined&webmap=6142e76453354c0b83633370e6a6f006%20&idvalue=b2b6c11b2d6dfe51d94503032adb7028&tcd=30&lang=en&activeLayers=USER_FEATURES%2Catlas_forestier_en_9979_0%2Catlas_forestier_en_9979_35%2Catlas_forestier_en_9979_36%2CTREE_COVER_GAIN%2CGLAD_ALERTS%2CVIIRS_ACTIVE_FIRES&tcLossFrom=0&tcLossTo=17&gladFrom=2015-01-01T05%3A00%3A00.000Z&gladTo=2019-11-04T16%3A33%3A43.088Z&terraIFrom=2004-01-01&terraITo=2016-07-12&viirsStartDate=2019-11-03%2011%3A33%3A43&viirsEndDate=2019-11-04%2011%3A33%3A43&modisStartDate=2019-11-03%2011%3A33%3A43&modisEndDate=2019-11-04%2011%3A33%3A43&customFeatureTitle=Feature%20Analysis&selectedFeatureTitles=Hunting%20zone%3A%20Zone%20d%27int%C3%A9r%C3%AAt%20cyn%C3%A9g%C3%A9tique&sharinghost=https%3A%2F%2Fwww.arcgis.com&activeFilters=&activeVersions=&layerId=https%3A%2F%2Fgis.forest-atlas.org%2Fserver%2Frest%2Fservices%2Fcmr%2Fatlas_forestier_en%2FMapServer%2F35--atlas_forestier_en_9979_35&OBJECTID=29&OBJECTID_Field=objectid&IFL=16&atlas_forestier_fr_3504=61%2C66%2C67%2C65%2C68%2C69%2C70%2C71&MODIS_ACTIVE_FIRES=21&VIIRS_ACTIVE_FIRES=21&atlas_forestier_en_9979=30%2C15%2C36%2C35%2C34%2C0%2C45&cache=1.4.2&origin=http%3A%2F%2Fblueraster.teaches-yoga.com

**Comment by richardbarad** [comment]
@csphang, @KaylaKremer, @SwampGuzzler. I know work has gone into this already, but if it causing issues on your side there is no need to prioritize it! I can ask my colleague in Cameroon to update the url used for the Map Service so that it does not use a `dynamiclayer`.

Richard

**Comment by KaylaKremer** [comment]
@richardbarad , I was able to fix the `dynamicLayer` and get Cameroon to work. However, I noticed that Georgia does not display the table as well and this is where I'm currently stuck. Hoping to work on this with Lucas tomorrow!

**Comment by richardbarad** [comment]
@KaylaKremer. I am doing testing again and what I see is:

1) In the Cameroon app, the report does not show the attribute table in French. I think we can fix this on our side if it breaks other apps, so would not spend to much time on it unless it is an easy fix.

2) However, I am seeing a larger issue which is that the report does not load the attribute table when the application is in the secondary language. This seems to always be true, regardless of whether a dynamic layer is used. You can test here at the links below. I checked and it looks like all these maps do not use dynamic layers.

http://blueraster.teaches-yoga.com/CMR?l=en
http://blueraster.teaches-yoga.com/DRC?l=en
http://blueraster.teaches-yoga.com/GEO?l=en

**Comment by KaylaKremer** [comment]
@richardbarad ,

1. I see. In that case, I think it's best to fix on your end and test it out. It's probably best to remove the `dyanmicLayer` entirely.

2. Thanks for pointing this out! I will look into it.

**Comment by richardbarad** [comment]
@KaylaKremer. I just updated the French Cameroon webmap and it is now loading the attribute table correctly! Please focus on issue number two here.

**Comment by KaylaKremer** [comment]
@richardbarad , awesome glad it works! And will do!

**Comment by SwampGuzzler** [comment]
Georgia fix here -- http://alpha.blueraster.io/gfw-mapbuilder/628-report-table-grg/

**Comment by csphang** [comment]
@richardbarad we have pushed our updates to the staging CMS. This is ready for you to test at:
http://blueraster.teaches-yoga.com/CMR?l=en
http://blueraster.teaches-yoga.com/DRC?l=en
http://blueraster.teaches-yoga.com/GEO?l=en
