### ISSUE TITLE
Edit and Delete are not vertical algined.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#629]
Make sure the _edit_ and _delete_ text are vertically aligned!

![Center_allign](https://user-images.githubusercontent.com/40440743/67325648-7a698500-f4e3-11e9-8efc-2608c4dbe8b9.png)

**Comment by csphang** [comment]
@richardbarad this fix is viewable at: http://alpha.blueraster.io/gfw-mapbuilder/subscribe-button-fix/

![image](https://user-images.githubusercontent.com/13664037/67335659-14d0c500-f4f2-11e9-9be9-91bb354dffe4.png)

**Comment by richardbarad** [comment]
@csphang & @KaylaKremer. Looks good and ready to be merged into 1.4.2.
