### ISSUE TITLE
Subscribe button formatting.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#630]
There are several issues with the formatting on the subscribe button:

1) The outline around the button does not have a consistent / standard color. The line is darker grey on the bottom

![subscribe](https://user-images.githubusercontent.com/40440743/67325959-ecda6500-f4e3-11e9-9ffd-c11cbe015242.png)

2. When you hover over the bottom of the button, the button starts to flash. See attached video. 
[subscribe_flash.zip](https://github.com/wri/gfw-mapbuilder/files/3758191/subscribe_flash.zip)

**Comment by KaylaKremer** [comment]
@richardbarad @csphang 
http://alpha.blueraster.io/gfw-mapbuilder/subscribe-button-fix/

**Comment by csphang** [comment]
Tested and confirmed. @richardbarad once you have a chance to review and confirm, you can move this to the Reviewer Approved column

![2019-10-22_17-26-44](https://user-images.githubusercontent.com/13664037/67335122-3bdac700-f4f1-11e9-8ed0-d2b37c681212.png)

**Comment by richardbarad** [comment]
@csphang. Looks good and ready to be merged in to production!
