### ISSUE TITLE
In the report. Land Cover Layers show up on top webmap layers

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#635]
### Subject of the issue
In the report, the land cover layers show up on top of the webmap layers. See screenshoot below:
![Layers_printreport](https://user-images.githubusercontent.com/40440743/67400613-e1d31380-f57b-11e9-8504-f62e86f4a8f6.png)

### Your environment
* version of app
* browser/ operation system/ dependencies

### Steps to reproduce
Use this app in the CMS: https://cmr.forest-atlas.org/map

1. Turn on a land cover layer (i.e: Primary Forest)
2. Click on a shape from the webmap group
3. Run an analysis report

### Expected behaviour
The layer rendering order should match the layer order specified in the configuration. Webmap layers on top of landcover layers!

### Actual behaviour
In the report, the land cover layers show up on top of the webmap layers. See screenshoot below:
![Layers_printreport](https://user-images.githubusercontent.com/40440743/67400613-e1d31380-f57b-11e9-8504-f62e86f4a8f6.png)

**Comment by richardbarad** [comment]
@csphang. Please fix this in 1.4.2 if it is quick. If not, it can wait till next phase.

**Comment by csphang** [comment]
Hi @richardbarad - we investigated and tried multiple fixes. Each of our updates have had consequences on other parts of the app. We've determined this is more complex and will need to move to next phase.

**Comment by richardbarad** [comment]
@csphang. Thanks! Moving this to backlog.

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
