### ISSUE TITLE
Issues with data stored in non webmercator projection

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#636]
@csphang I did a bit more investigating on the issue we are having with projections, which we discussed here: https://github.com/wri/gfw-mapbuilder/issues/567. I found a similar issue in the Congo Forest Atlas.

Right now, I am simply creating this ticket to document this behavior and request that the team investigate it and see if we can understand what is going on. We should be supporting data stored in different projections so this seems like a bug. If it will require high LOE to address we can wait till the next phase to work on a fix. However, I would like to request that the team investigate the cause (once other bug fixes are complete) to see if we can at least figure out what is going on. If there are questions about the behavior of the geostore endpoint we should discuss those with Thomas. 

Below is the workflow to test this issue on the COG atlas on our staging CMS site. Note that the bug is only present when using the app in English (reason described below). http://blueraster.teaches-yoga.com/COG?l=en

Here is the workflow to follow in the CMS app linked above.

1) Click on a shape in the forest concession layer as shown below:
![image](https://user-images.githubusercontent.com/40440743/67405184-69bc1c00-f582-11e9-92df-0273c2b85fd1.png)

2) Click print report
In the resulting report, the shape is not correct as shown below. It seems that we are running an analysis on a triangle shape instead of the original geometry from the webmap: 
![image](https://user-images.githubusercontent.com/40440743/67405815-45147400-f583-11e9-8c0b-1a4ac4d7f019.png)

I tried out a similar workflow on another shape as shown below and for this one all the analysis fails in the report completely.
![image](https://user-images.githubusercontent.com/40440743/67406109-a8060b00-f583-11e9-9be6-e47206de0f64.png)

I believe the issue is with the post request being made to MapBuilder. When I look at the post requests made the geostore endpoint for the shapes in the English maps it looks like the coordinates are not correct as there are only three coordinates showing up in the geometry! It also looks like the coordinates are not in lat. / long as there are no decimal places in the numbers. See screenshot below:
![image](https://user-images.githubusercontent.com/40440743/67406683-675ac180-f584-11e9-90ba-f5f62c97e7d5.png)

Oddly, I noticed that this issue was only present in the English. After additional investigation of the underlying services:

- **French service** is published in Web Mercator (102100): https://gis.forest-atlas.org/server/rest/services/cog/Affectation_terre_fr/MapServer
- **English service** is published in WGS (4326): https://gis.forest-atlas.org/server/rest/services/cog/Affectation_terre_fr/MapServer

Thus, it looks like the issue might be caused by the service being published in a projection which is not webmercator, and thus related to the issue we have here: https://github.com/wri/gfw-mapbuilder/issues/567. I am not sure why the Congo team published the data in a projection which is not webmercator (must be a mistake). 

However, we should support services in non webmercator projections so this is still worth investigating! Please let me know if it would help to have a call on this to discuss.

**Comment by richardbarad** [comment]
Another example here: http://richard.teaches-yoga.com/map/?l=fr

The data here is stored in the local projection of Madagascar (and data was published as feature services from ArcGIS Pro).

**Comment by csphang** [comment]
Hi @richardbarad - The issue is coming from the geometry registration with the geostore. We were previously not using exact geometries in an effort to reduce errors with the geostore registrations (it would sometimes crash when using complex geometries). Lucas has pushed the update so we use the feature's exact geometry.

**Comment by richardbarad** [comment]
@csphang and @SwampGuzzler,

Thanks for fixing in this phase! 

Are there specific questions you have with geostore endpoint and how we should be using it in MapBuilder? I know there is a geostore limit on the geometry complexity but do not know what it is. Should we be simplifying geometries if they are very complex? 

Maybe it is worth having a discussion about this with Thomas before the next phase?

Richard
