### ISSUE TITLE
Do we still need the maskservice in the configuration?

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#640]
Do we still need the mask service in our resources? I think this was deprecated a while ago since the mask is now part of the extra layers? If yes, please remove this setting from the resources.js https://github.com/wri/gfw-mapbuilder/blob/sprint-6-base/src/resources.js

`  maskServiceUrl: '', // e.g. http://gis-forest-atlas.wri.org/arcgis/rest/services/CMR/CMR_00_Africa/MapServer`

**Comment by KaylaKremer** [comment]
@SwampGuzzler @csphang @richardbarad 

This has been removed from `resources.js` here: https://github.com/wri/gfw-mapbuilder/pull/543

When other tickets are complete, this branch will be merged in with our new default resources.js.

**Comment by richardbarad** [comment]
@KaylaKremer and @SwampGuzzler. Please make sure FORMA is removed when everything is merged as I noticed it is still included in the `resources.js` in this branch: https://github.com/wri/gfw-mapbuilder/blob/new-default-resources-and-externals/src/resources.js
