### ISSUE TITLE
When sharing, the loss tiles do not load at the correct zoom level.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#651]
Workflow to replicate: http://my.gfw-mapbuilder.org/v1.4.2/

1) Click clear all call on the app
2) Zoom in 2 zoom levels
3) Turn on annual TCL
4) Copy the share url
5) Paste in a new browser

The app loads the TCL tiles at the wrong zoom level. Please see attached video and screenshot and video below. This is also replicable in the CMS, but only in primary language. It is not replicable in the secondary language due the other bug https://github.com/wri/gfw-mapbuilder/issues/652 I noticed.
![Loss_data](https://user-images.githubusercontent.com/40440743/67894547-212ad280-fb2f-11e9-842e-ec15984f8c76.png)
[TCL_loss_bug.zip](https://github.com/wri/gfw-mapbuilder/files/3790932/TCL_loss_bug.zip)

 below.

**Comment by SwampGuzzler** [comment]
@csphang http://alpha.blueraster.io/gfw-mapbuilder/651-tcl-sharing/

**Comment by richardbarad** [comment]
@SwampGuzzler & @csphang. The bug seems to be fixed, but I am noticing another issue now where when I first turn on Tree Cover Loss the tiles are not visible and I have to pan in on order to load the tiles.

[TCl_Loss.zip](https://github.com/wri/gfw-mapbuilder/files/3809311/TCl_Loss.zip)

**Comment by csphang** [comment]
Tested and verified the fix on http://alpha.blueraster.io/gfw-mapbuilder/651-tcl-sharing/
