### ISSUE TITLE
In CMS, 1.4.2 apps are not loading at correct zoom level when loaded in 2nd language.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#652]
If I go through this workflow here: http://blueraster.teaches-yoga.com/CMR?l=en

1) Load the app in the secondary language (English)
2) Click clear all
3) Turn on land cover dynamics TCL Layer and a few web map layers
4) Copy the share url into a new tab

The map loads at the zoom level from the ArcGIS Online webmap instead of inheriting the zoom level from the url. This only happens in the secondary language.

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/652-correct-zoom/?l=en @csphang

**Comment by csphang** [comment]
Tested on http://alpha.blueraster.io/gfw-mapbuilder/652-correct-zoom/?l=en.

@richardbarad this is ready for your review.

**Comment by richardbarad** [comment]
@csphang. Looks good and ready to be merged in to `v1.4.2`.
