### ISSUE TITLE
When sharing after adjusting TCL year filter the app does not correctly filter the TCL Layer by year

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#655]
### Subject of the issue
When sharing the app after adjusting the time slider for tree cover loss, the resulting application from the share url shows the full time period for loss intead of filtering to just show data for the desired range. 

### Your environment
* 1.4.2

### Steps to reproduce
1. Load the app: http://blueraster.teaches-yoga.com/CMR?l=fr
2. Clear all layers
3. Turn on tree cover loss
4. Adjust the time slider to show less than the full loss time period (i.e: 2011 - 2018)
5. Create a share url and copy it into a new tab

### Expected behaviour
The share url should show a TCL in which the layer is correctly filtered by date. 

### Actual behaviour

The loss years are correctly present in the share url as shown below, but the map returned by this url shows the full loss time series (2001 - 2018), instead of just showing just the date ranges indicated by the url.

_http://blueraster.teaches-yoga.com/CMR?x=13.68&y=4.27&z=8&l=fr&b=wri_contextual&t=LAYERS&a=TREE_COVER_LOSS&o=1&ls=13&le=17_

![TCL_filter](https://user-images.githubusercontent.com/40440743/68046860-4d6f5c00-fcb3-11e9-8bef-ab735c13d5f9.png)

**Comment by richardbarad** [comment]
@csphang. Tagging this as low priority. Please fix if an easy fix can be applied.

**Comment by SwampGuzzler** [comment]
@SwampGuzzler We need these! 
https://github.com/wri/gfw-mapbuilder/blob/c06724169125d72f9d9bb3a360994b01aa0c6230/src/js/components/LayerPanel/LossControls.js#L71

-- minus the updates the unnecessary internal component updates that come with deriving localState from props and back again

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
