### ISSUE TITLE
Layer Panel shows attributes of shapes when using the measurement tool

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#656]
### Subject of the issue

When drawing a shape using the measurement tool, the layer panel jumps to show the shape attributes when you click in a location which overlaps with a shape in the map. 

### Your environment
* 1.4.2
* Google Chrome
http://blueraster.teaches-yoga.com/CMR?l=fr

### Steps to reproduce

1. Open this app: http://blueraster.teaches-yoga.com/CMR?l=fr
2. Click on the measurement tool
3. Click on the area draw tool
4. Start drawing a shape, and click in an area which overlaps with the polygons from the webmap.

### Expected behaviour
5. When drawing a shape using the measurement tool, the layer panel should not show attributes of a shape when you click on a point which overlaps with a polygon in the webmap.

### Actual behaviour

Currently, the layer panel shows the attributes of shapes in the layer panel when using the 
measurement tool and "jumps" to show attributes when you click on a location which overlaps with a shape in the map.

**Comment by csphang** [comment]
@richardbarad I followed the steps above, but am not seeing the attributes panel appear? 

![MapBuilder-measurement](https://user-images.githubusercontent.com/13664037/68147762-cd423400-ff08-11e9-84a7-3c16c80fb85e.gif)

**Comment by richardbarad** [comment]
@csphang. Just tested again, and unfortunately I can not replicate any more. Guessing there must have been a preceding step in my testing which caused the bug. I'll close this out for now.
