### ISSUE TITLE
In the report, after changing the date filter to the GLAD download CSV the url for the download file should change. 

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#658]
### Subject of the issue
In the report, after changing the date filter to the GLAD download CSV the url for the download file should change. 

### Your environment
* 1.4.2
* Google Chrome

### Steps to reproduce
1. Click on a shape in the map
2. Click print report
3. Adjust the date range for the TOTAL GLAD ALERTS alerts widget.
4. Click run analysis to update the widget
5. Click the download csv button. 

### Expected behaviour

Currently, the download url stays as _https://production-api.globalforestwatch.org/glad-alerts/download/?period=2018-01-01,2019-11-04&gladConfirmOnly=False&aggregate_values=false&aggregate_by=False&geostore=83063be836f73a3da26bdf8ece6899c4&format=csv_. 

The period range will always be period=2018-01-01,2019-11-04 regardless of the date range selected by the user. The download url period range does not change depending on the range selected by the user.

### Actual behaviour
The download url should change based on the date range selected by the user in the filter.

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
