### ISSUE TITLE
If pop-up is configured through layer panel, clicking on shape returns layer name in wrong language when app is in secondary language. 

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#660]
**Describe the bug**

If a pop-up is configured for a layer through layer panel, clicking on shape returns  the layer name in wrong language when app is in secondary language. 

**To Reproduce**
1. Go to http://blueraster.teaches-yoga.com/GEO?l=en (make sure app is in English)

2. Click on a shape from the protected area layer (i.e: the polygon shown in the screenshot below)

![2019-11-04 12_46_00-Window](https://user-images.githubusercontent.com/40440743/68144196-1d1cfd00-ff01-11e9-9cad-c33cdbccac76.png)

**Expected behavior**

The layer name in the layer drop-down should show in English since the application language is currently set to English. Currently, it shows the name of the layer in Georgian as shown in the screenshot below. 

**Screenshots**

![Language_BUg](https://user-images.githubusercontent.com/40440743/68144296-5bb2b780-ff01-11e9-9664-76db598a0b0b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by csphang** [comment]
@richardbarad Can you clarify what `popup configuration through the layer panel` means? We noticed this pop-up behavior doesn't occur with Cameroon's secondary language.

**Comment by richardbarad** [comment]
@csphang. We support adding a pop-up for a layer configured through the Layer Panel in a non webmap group and our Georgia application makes heavy use of this since it contains multiple groups with custom layers. The Cameroon layers seem to not be impacted because all the layers with pop-ups come from the webmap group instead of the layers in the configuration panel.

For example, the code below shows the configuration for our Protected Areas layer in the Georgia Atlas. When I click on a protected area I see the Georgian label text instead of the English text even through the language is set to English.

Let me know if you need additional information.

```
      {
        "order": 5,
        "id": "PA",
        "type": "dynamic",
        "visible": true,
        "url": "https://gis.mepa.gov.ge/server/rest/services/atlas/protected_areas/MapServer",
        "layerIds": [
          4
        ],
        "label": {
          "en": "Protected Areas",
          "ka": "დაცული ტერიტორიები"
        },
        "filterField": {
          "en": "Category_EN",
          "ka": "Category_KA"
        },
        "filterLabel": {
          "en": "Filter by Category",
          "ka": "ფილტრი კატეგორიების მიხედვით"
        },
        "popup": {
          "title": {
            **"en": "Protected Areas",
            "ka": "კატეგორიები"**
          },
          "content": {
            "ka": [
              {
                "label": "დაცული ტერიტორია",
                "fieldExpression": "Protected_Areas_KA"
              },
              {
                "label": "დაარსების წელი",
                "fieldExpression": "Year_of_Establishment_KA"
              },
              {
                "label": "ადმინისტრაცია",
                "fieldExpression": "Administration_KA"
              },
              {
                "label": "კატეგორია",
                "fieldExpression": "Category_KA"
              },
              {
                "label": "ფართობი ჰა",
                "fieldExpression": "PA_Area_ha_KA"
              }
            ],
            "en": [
              {
                "label": "Protected Area Name",
                "fieldExpression": "Protected_Areas_EN"
              },
              {
                "label": "Year of Establishment",
                "fieldExpression": "Year_of_Establishment_KA"
              },
              {
                "label": "Administration",
                "fieldExpression": "Administration_EN"
              },
              {
                "label": "Category",
                "fieldExpression": "Category_EN"
              },
              {
                "label": "Area (ha)",
                "fieldExpression": "PA_Area_ha_KA"
              }
            ]
          }
        }
      }
```

**Comment by SwampGuzzler** [comment]
@csphang Can we talk about `features in InfoWindow getting cleared out on language-toggle`?

**Comment by csphang** [comment]
@SwampGuzzler we can proceed with closing the infowindow when a user switches languages

**Comment by SwampGuzzler** [comment]
@csphang Check this out here: http://alpha.blueraster.io/gfw-mapbuilder/660-language-toggle-update/

**Comment by csphang** [comment]
@richardbarad I reviewed the updated build and believe it's ready for your review. This url encompasses updates to the attribute info window: http://alpha.blueraster.io/gfw-mapbuilder/660-language-toggle-update/

**Comment by richardbarad** [comment]
@csphang. It looks like the update is not working for point layers. It works for polygon and line.

To see this:

1) Set the language to English
2) Clear all layers
3) Turn on the following two layers:

a) Protected Areas - Infrastructure of Protected Areas
b) Biodiversity - EUNIS Habitats (first layer in Biodiversity group)

4) Click on a point. The text will be in Georgian instead of English as shown in the screenshoot below.

![Infrastructure_ProtectedAreas](https://user-images.githubusercontent.com/40440743/68714808-9b674800-056e-11ea-9d52-b6a0dac8f655.png)
![EUNIS_Habitat](https://user-images.githubusercontent.com/40440743/68714815-a326ec80-056e-11ea-80e5-dde78921d342.png)

Interestingly, it is working correctly for Fires though in which the pop-up is also configured through the configuration.

**Comment by csphang** [comment]
Hi @richardbarad - We discovered this issue was occurring with layers containing a layerId of 0. We've updated the code and this is ready for your testing. You can use the same URL as before! http://alpha.blueraster.io/gfw-mapbuilder/660-language-toggle-update/

**Comment by richardbarad** [comment]
@csphang. Looks good!
