### ISSUE TITLE
Featureservice layers in map are generalized after clicking on them

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#662]
### Subject of the issue

After clicking on a geometry for a layer which comes from a feature service hosted on ArcGIS Online the geometry gets generalized and the original geometry is no longer rendered in the map. 
This issue only occurs with feature services and does not occur with graphic or dynamic layers. 

### Your environment

* 1.4.2
* Google Chrome

### Steps to reproduce

1. Use the app: https://kenya.restorationatlas.org/maps/makuli
2. Click on an orange/brown polygon in the population layer
3. Click on another polygon in the same layer
4. Zoom in on the map
5. Gaps will be visible between the geometries in the map, and the shape of the original geometry has changed. This behavior does not happen the shape selected is from a dynamic service or a graphic. 

### Expected behaviour

The shape of the geometry should not change after the user clicks on it. The geostore shape with the blue outline could be simplified slightly. It is ok if the shape which is used for analysis is generalized slightly. 

However, the original geometry which is rendered in the map should not change after selection. This behavior does not happen when selecting graphic (shapefiles uploaded in webmap) or shapes from Map Services so it is unclear why the behavior is different for feature services. If there is an intentional reason, it should be discussed further.

### Actual behaviour

Gaps appear between the geometry and the shape of the geometry in the map has changed as shown in the screenshoot below.
 
![Geometry_gaps](https://user-images.githubusercontent.com/40440743/68225224-1acca880-ffbe-11e9-9af1-8ec22f578d2b.png)

**Comment by vaidotasp** [comment]
I think this is solved in rewrite
test link: https://alpha.blueraster.io/gfw-mapbuilder/test/662-feature-generalization/
