### ISSUE TITLE
Vega Legends are not loading correctly in 1.4.2 build.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#667]
In 1.4.2 the Vega legends, seem to load differently that in 1.4.1. This impacts both widgets loading the report and widgets loading in the layer panel.

To replicate:

1) Go the staging Ethiopia map: https://eth.restorationatlas.org/atlas (currently pointing to v1.4.1)
2) Draw a shape, you may want to turn on the land cover layer and make sure the shape covers multiple land cover classes
3) Select land cover analysis
4) Click run analysis
5) In the returned legend there are two columns:

![legend](https://user-images.githubusercontent.com/40440743/68413729-d1ff2600-015c-11ea-9452-48f39a080a31.png)

If I repeat the same workflow on http://blueraster.teaches-yoga.com/ETH?l=en I get a legend which contains 1 column only instead of 2 even though both configurations use the same widget. This happens in the report as well. The configuration specifies `"columns": 2` in the legend configuration so am not sure why we are getting 1 column in the legend when using 1.4.2.

![1 4 1_Legend](https://user-images.githubusercontent.com/40440743/68413838-0f63b380-015d-11ea-833e-d7fdd552b9b3.png)

You can also test using the Land Cover Composition analysis on our base configurations either in the layer panel or in the report.
http://my.gfw-mapbuilder.org/v1.4.1/
http://my.gfw-mapbuilder.org/v1.4.2/

Screenshoots shown below:

Version 1.4.1
![Landcover_1 4 1](https://user-images.githubusercontent.com/40440743/68414164-a6307000-015d-11ea-86e2-a960a7cd1505.png)

Version 1.4.2
![Landcover_1 4 2](https://user-images.githubusercontent.com/40440743/68414139-99138100-015d-11ea-8d18-bd69d7a6bcf6.png)

**Comment by richardbarad** [comment]
@csphang. I had put this in backlog, but curious if we can take a quick look to see if a fix is apparent since this seems to have been introduced in 1.4.2.

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

I quickly took a look at this. I got just one vertical column with both links:

![Screen Shot 2019-11-13 at 10 21 54 AM](https://user-images.githubusercontent.com/22095244/68777486-bafa8100-05ff-11ea-8b6b-40e958bc2793.png)

![Screen Shot 2019-11-13 at 10 22 12 AM](https://user-images.githubusercontent.com/22095244/68777487-bafa8100-05ff-11ea-807c-d87c90b362aa.png)

 I remember we last updated the widget config for #495 , so I wonder if that has anything to do with it? This is what I get when I log out the config for the legend:

<img width="205" alt="Screen Shot 2019-11-13 at 10 32 30 AM" src="https://user-images.githubusercontent.com/22095244/68778317-02354180-0601-11ea-9aa4-d54fd7a51c17.png">

**Comment by csphang** [comment]
@richardbarad I propose we backlog this for now!

**Comment by richardbarad** [comment]
@KaylaKremer. Yes, that looks correct. For some reason, the widgets seem to be rendering with just 1 column in v1.4.2 even though the columns setting is set to `"columns": 2`. @csphang. I'll move this back to backlog.
