### ISSUE TITLE
Print Report does not work when in 2nd language

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#670]
**Describe the bug**

Print button does not work when printing in the secondary language

**To Reproduce**

**Open the application** 

1) https://cmr.forest-atlas.org/map?l=en or https://cod.forest-atlas.org/map?l=en
2) Click on the print button
3) PDF report will be blank and not show the layers from the webmap

**Expected behavior**
The printed PDF should show the layers which are turned on in the webmap. Attached is a blank PDF showing the issue in the current printout. 

**Screenshots**
[blankPDF.pdf](https://github.com/wri/gfw-mapbuilder/files/3833180/blankPDF.pdf)

**Desktop (please complete the following information):**
Version 1.4.2
Google Chrome

**Additional context**

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
