### ISSUE TITLE
When sharing MapBuilder after adjusting TCD Layer, the app does not load

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#673]
**Describe the bug**
When sharing MapBuilder after adjusting TCD for the loss, biomass, or Tree Cover data layers the app does not load.

**To Reproduce**
1. Go to http://my.gfw-mapbuilder.org/v1.4.2/
2. Turn on the Tree Cover Loss layer
3. Change the tree cover density threshold to 50 instead of 30
4. Click the share button, and copy the share url into a new tab
5. The application will not load, and an error is returned in the console as shown below:

![Console_Error](https://user-images.githubusercontent.com/40440743/68624227-5e368380-04a4-11ea-93e4-c08451d3e45e.png)

**Expected behavior**
After copying the share url, the MapBuilder application should filter to the tree cover density threshold used in the original application. Note that the TCD filter should apply to the `Above ground biomass`, `Tree Cover`, and `Tree Cover Loss` data layers. 

**Screenshots**

**Desktop (please complete the following information):**
Version: 1.4.2
Google Chrome

**Additional context**
This was working correctly here: http://my.gfw-mapbuilder.org/v1.4.1/. Thus, it seems to have been caused by our work on the share functionality.

**Comment by richardbarad** [comment]
@csphang. This bug seems to have been caused by our updates to the share functionality in `v1.4.2`. Could you take a look and see if this a quick fix to address in this phase.

**Comment by SwampGuzzler** [comment]
http://alpha.blueraster.io/gfw-mapbuilder/673-tcl-density-share/?x=20.49&y=-2.75&z=5&l=en&b=wri_contextual&t=LAYERS&a=TREE_COVER_LOSS&o=1&c=50&ls=0&le=17

**Comment by richardbarad** [comment]
@SwampGuzzler. Please check to make sure the TCD filter also applies to the Tree Cover Layer. In this link, it looks like it applies to the Loss and Biomass layers but not Tree Cover. The Tree Cover Layer renders based on a 30% threshold even though the tcd setting is set to 75.

http://alpha.blueraster.io/gfw-mapbuilder/673-tcl-density-share/?x=23.72&y=-0.47&z=6&l=en&b=wri_contextual&t=LAYERS&a=AG_BIOMASS%2CTREE_COVER%2CTREE_COVER_LOSS&o=1%2C0.8%2C1&c=75&ls=0&le=17

**Comment by csphang** [comment]
@richardbarad we're taking a look!

**Comment by SwampGuzzler** [comment]
@richardbarad @csphang Updated! This accounts for all of those layers on-share: http://alpha.blueraster.io/gfw-mapbuilder/573-everything-density-share/?x=23.72&y=-0.47&z=6&l=en&b=wri_contextual&t=LAYERS&a=AG_BIOMASS%2CTREE_COVER%2CTREE_COVER_LOSS&o=1%2C0.8%2C1&c=75&ls=0&le=17

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good now! Thanks!

**Comment by richardbarad** [comment]
@SwampGuzzler & @csphang. Please check to make sure this update is included in 1.4.2.

Go through the following workflow here: http://blueraster.teaches-yoga.com/CMR?l=fr

1) Clear all layers
2) Turn on Tree Cover Loss, Tree Cover, and Biomass Density
3) Adjust the treshold to 75 
4) Copy the share url
5) The Tree Cover Loss and biomass layers load at 75% but tree cover does not!

**Comment by SwampGuzzler** [comment]
@richardbarad You can test this out in the CMS for 1.4.2

**Comment by richardbarad** [comment]
@SwampGuzzler. Please check the 2nd workflow as well as we need to make sure this works in both languages. Currently, it only works when your language is set to French.

**Comment by csphang** [comment]
@richardbarad an update on this. We pushed some changes to the staging CMS. After testing this morning, we've found the update worked for Woody Biomass and Tree Cover. But still not quite for TCL always. TCL tiles look good after zooming in or out one level. We're continuing to investigate options for getting the tiles to consistently work on default load.

**Comment by richardbarad** [comment]
@csphang. I see what you mean! Just to add to this, it looks like the issue with TCL tiles is present in both English and French.

**Comment by csphang** [comment]
@richardbarad We pushed an additional update for this. We're continuing to test on our end, but the update is pushed to the staging CMS in case you want to do an early review.

**Comment by richardbarad** [comment]
@csphang Thanks for update! I did some quick testing and think I see two issues:

1) When I first use the slider, and switch from 30% to 75% the layer does not actually update in the map and I have to play with the slider or zoom in order for the layer to update. This should be apparent by looking at the area above my mouse pointer in the attached video.

[Bug1.zip](https://github.com/wri/gfw-mapbuilder/files/3881301/Bug1.zip)

2) The fix you applied appears to work in the primary language but not in the secondary language. When in the secondary language I have to pan or zoom in/zoom out one level .

**Comment by csphang** [comment]
@richardbarad we identified today that the app is overlaying multiple tiles on top of one another after sharing which is causing the saturation difference we see. As soon as you tweak the density slider or zoom in/out, the app reduces to one instance of forest loss (down from 4). We're working on updating this tomorrow so it'll be ready for when you're back in office.

![image (3)](https://user-images.githubusercontent.com/13664037/69678529-d344b400-1073-11ea-9f03-dc28c05f81c0.png)

**Comment by SwampGuzzler** [comment]
@csphang This is updated on the CMS!

**Comment by richardbarad** [comment]
@SwampGuzzler and @csphang. Looks good!
