### ISSUE TITLE
Fires share does not work when English is the secondary language.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#676]
@csphang. Noticing that the share functionality for fires does not work when you are in the secondary language! it works correctly in the primary language.

To replicate:

1) Load this map http://blueraster.teaches-yoga.com/CMR?l=en
2) Turn on MODIS and VIIRS and change the time period to 48 hours 
3) Copy the share url into a new tab

The returned map shows the fires for the past 24 hours instead of fires for the past 48 hours. Is this possible to fix, seems related to our recent updates?

Update this issue only seems to replicable in the CMS when the language is set through the url.

**Comment by KaylaKremer** [comment]
@richardbarad 

I'm still working on this ticket, but just wanted to note here that from my testing in the CMS, it also appears that 48 hrs does not work for VIIRS when turning on this alone, even without sharing. Also the language does not seem to matter, it won't display regardless in either French or English.

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! Could this be a server side issue? @csphang. Looks like fires for VIIRS 48 hours does not load on GFW Fires as well.

The bug on this ticket should also be replicable using another workflow in which you set the date toggle to 72 hours instead of 24 hours.

1. Load this map http://blueraster.teaches-yoga.com/CMR?l=en
2. Turn on MODIS and VIIRS and change the time period to 72 hours
3. Copy the share url into a new tab
4. The layers show the past 24 hours even though the url is set to 72 hours. 

If the language issue is complicated to address we can deploy without it. However, we should make sure VIIRS loads for 48 hrs. I am not sure if it is a MapBuilder or server side issue.

![Fires_share_bug](https://user-images.githubusercontent.com/40440743/69246855-7b8be180-0b77-11ea-9099-25f399939dfd.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

It seems there is an issue with the 48 hrs service at the moment, but still waiting for confirmation on that.

Just to verify, it seems the issue with this ticket only has to do with the dropdown not retaining the displayed selection? I checked to make sure the VIIRS/MODIS dots are using the correct service and they seem to be displaying the right information (from 72 hrs):

<img width="1012" alt="Screen Shot 2019-11-20 at 9 55 56 AM" src="https://user-images.githubusercontent.com/22095244/69257253-c4986180-0b88-11ea-9e20-196890a0b3f3.png">

<img width="1015" alt="Screen Shot 2019-11-20 at 9 56 47 AM" src="https://user-images.githubusercontent.com/22095244/69257255-c4986180-0b88-11ea-8ad6-01900f572877.png">

**Comment by richardbarad** [comment]
@KaylaKremer. Yes, I just tested it and you are correct! It looks like the issue is that the dropdown is not retaining the displayed selection. However, the correct points do load in the map.

**Comment by KaylaKremer** [comment]
@richardbarad Thanks for confirming that!

**Comment by richardbarad** [comment]
This was moved to the backlog and tagged as a low priority. Given that the Fires layers are being refactored / updated to use Vector Tile Layers it may make sense to leave this issue alone due to other higher priority bugs.

**Comment by vaidotasp** [comment]
not relevant due to 1.5 rewrite.
