### ISSUE TITLE
[StandardConfig]: add in "useWebmapBasemap" into the config

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#683]
@richardbarad we'll also need to add in `"useWebmapBasemap": false`  into the standard config panel for AGOL apps

**Comment by richardbarad** [comment]
@csphang. Thanks! I added this here and you can also see the other updates I made! 

https://github.com/wri/gfw-mapbuilder/commit/d83d0b93f0c04a779a8c4f72c02a4e484cb85afa
