### ISSUE TITLE
Make sure configuration settings are up to date.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#687]
Make sure configuration settings in 1.4.2 release match what is on our master branch: https://github.com/wri/gfw-mapbuilder/tree/master/config-panels

Both the `simplePanel.json` and `standardConfigurationPanel.json` were updated.

**Comment by SwampGuzzler** [comment]
Done! https://github.com/wri/gfw-mapbuilder/pull/685
