### ISSUE TITLE
Modal Sizing

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#713]
Modal size should be controlled by the modal-card-container class and can be overwritten by Modal-specific classNames unique to a certain modal

**Comment by SwampGuzzler** [comment]
Modal **size** should be controlled by the `modal-card-container` class and can be overwritten by Modal-specific classNames unique to a certain modal

**Comment by eyosef** [comment]
Just wanted to add that I've been asked to hoist className specifications to the reusable class `.modal-class-container`
