### ISSUE TITLE
Basemaps Panel

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#761]
Re-create old basemap section of the Left Panel:

- [x] Generic ESRI basemaps #845 
- [x] Custom layer type for our Landsat Imagery basemap!
- [ ] Custom WRI static Basemaps

**Comment by eyosef** [comment]
Looks like we can't load custom basemaps (vector tiles) to a 4x app so we're holding on any logic for this until @vaidotasp gets clarification from ESRI

**Comment by vaidotasp** [comment]
Landsat is able to be loaded as WebTiled layer. Other ones need to be fixed as Vectors at API level.

**Comment by vaidotasp** [comment]
With landsat done, closing issue per current status on WRI basemaps. Will re-open once we know more how to consume new types.
