### ISSUE TITLE
Print widget - custom legends in GFW_Landscape

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#779]
Custom legends/layers do not render in the legend of the PDF with the `..._Landscape` type. We may need to dig into the print service URL to see if previous configurations are preventing this. Also will need to look into ESRI's `PrintTask` to see if we need to update the legend as needed

It's possible we'll need to leverage `legendLayers` property of the `PrintTemplate` ESRI widget

-- Currently layers such as Loss, Gain, GLAD do showup on printed map but do not show up in the legend.

**Comment by SwampGuzzler** [comment]
@csphang Per your comment - does AGOL's print even render these layer's legend? 
The Print Task service is currently here: https://gis.forest-atlas.org/server/rest/services/print/ExportWebMap/GPServer
