### ISSUE TITLE
Measure widget - Redux

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#787]
Measure widget logic for `SET_MEASURE_RESULTS` should be in the mapview state reducer, not app state reducer

**Comment by vaidotasp** [comment]
@eyosef please review and close if this is solved.

**Comment by eyosef** [comment]
@vaidotasp Not resolved yet, but I can dig into this ASAP

**Comment by vaidotasp** [comment]
nah, not a priority, just making  sure  we close issues  as they are fixed. I had quite a few opened even though I addressed  them :)
