### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#793]
![Screen Shot 2020-02-14 at 2 40 08 PM](https://user-images.githubusercontent.com/9040867/74562039-e7dc6e00-4f37-11ea-9e32-84465646fcb2.png)

Do we need to configure `@arcgis/webpack-plugin` to account for `promiseUtils`?

- https://github.com/esri/arcgis-webpack-plugin#additional-features
- https://community.esri.com/thread/219307-web-worker-and-js-api-modules

**Comment by vaidotasp** [comment]
Opened issue with the official arcgis plugin repo: 
https://github.com/Esri/arcgis-webpack-plugin/issues/80
