### ISSUE TITLE
Displaying legends from layers served from a separate geoserver

### ISSUE THREAD

**Issue by jequihua** [wri/gfw-mapbuilder#797]
We are developing a visualizer where we include layers served from a geoserver. We get an error from the legends display:

Legend Not Available: there was an error retrieving legend info. Expected type: 'image/png', got 'text/xml'

It's clear that we need the legend to be sent as a png instead of an xml but we have no been able to do so. Is there any experience on this which could help?

**Comment by SwampGuzzler** [comment]
Hey @jequihua - this sounds very possible --> can you send an example that replicates this issue or a `resources` that I can reproduce it with?

**Comment by jequihua** [comment]
Hey, 

We are using Map Builder 1.3 and Geoserver 2.13.0. 

We send our layers to Map Builder by [WMS](https://monitoreo.conabio.gob.mx/geoserver/semarnat/wms).

For example:

`{
        "order": 2,
        "id": "lcc20174",
        "type": "wms",
        "url": "https://monitoreo.conabio.gob.mx/geoserver/semarnat/wms",
        "layerName": "semarnat%3Achanges_selva_lacandona_2017.4",
        "visible": true,
                "opacity":1.0,
        "label": {
          "es": "Lacandona 2017 Trim 4",
                  "en": "Lacandona 2017 Q4"
        }`

We also tried generating a PNG file and assigning it to a layer in Geoserver itself. Finally we tried using Map Builder's LegendConfig as can be seen in line 510 of our complete html, which can me located [here](https://monitoreo.conabio.gob.mx/wri_chiapas.html) and where you will also be able to notice the legend errors.

**Comment by SwampGuzzler** [comment]
Hey @jequihua - I added a quick parse of a URL - everything on your `Geoserver` was set up correctly! I see the fix live!

**Comment by jequihua** [comment]
That's amazing! Thanks so much.
