### ISSUE TITLE
coordinateform.tsx - DD UI

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#802]
<img width="368" alt="Screen Shot 2020-02-18 at 4 45 20 PM" src="https://user-images.githubusercontent.com/9040867/74780679-188d1200-526e-11ea-9d78-1f1bd61db75c.png">
DD dropdown should render content matching comps. User should be able to add/remove sections.

**Comment by vaidotasp** [comment]
@eyosef please review and close if this is solved.
