### ISSUE TITLE
onShare, update URL to include X/Y/Z coordinates and visibleLayer IDs

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#818]
When user clicks the share button, shareable URL should include X/Y/Z coordinates and visibleLayerIDs

`mapbuilder?x=5&y=6&z=10&visibleLayers=firesID,loss`

Variables that need to be tracked and applied on map load:
- [x] basemap
- [x] VIIRS
- [x] MODIS
- [x] TERA
- [x] GLAD,  start/end dates and Toggle
- [x] latitude/longitude (@SwampGuzzler gave me the green light to set lat/long, instead of X/Y/Z)
- [x] language
- [x] active layers (fires include range as well? need to confirm)
- [x] active tab
- [x] layer Opacity
- [x] zoom level
- [x] canopy density

E.g: `http://blueraster.teaches-yoga.com/CMR?x=12.46&y=5.30&z=8&l=en&b=satellite&
t=INFO_WINDOW&a=atlas_forestier_en_9979_36%2Catlas_forestier_en_9979_37%2Catlas_forestier_en_9979_13%2Catlas_forestier_en_9979_38%2Catlas_forestier_en_9979_35%2Catlas_forestier_en_9979_47%2Catlas_forestier_en_9979_49%2CVIIRS_ACTIVE_FIRES_48HR%2CMODIS_ACTIVE_FIRES_1YR&o=1%2C1%2C1%2C1%2C1%2C1%2C1%2C1%2C1&vs=2-20-2020%208%3A57%3A37&ve=2-21-2020%208%3A57%3A37&ms=2-20-2020%208%3A57%3A37&me=2-20-2020%208%3A57%3A37`

**Comment by eyosef** [comment]
PR https://github.com/wri/gfw-mapbuilder/pull/822 updates the shareable URL to include latitude/longitude, zoom level and active layers

**Comment by vaidotasp** [comment]
this seems to be completed, may require more testing.
