### ISSUE TITLE
Data tab => remove button removes feature from data tab

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#831]
Part of #782 
Upon clicking "X" button, user should no longer see that feature in the data tab. If removed feature was the last one in the layer group of features, the whole layer should be removed from data tab.

**Comment by SwampGuzzler** [comment]
This looks awesome in #832 . Once the UI is in, let's close this. 

We also need to think about sublayers vs normal layers and if that will need us to come back to this one - ex: should sublayers get their own dropdown item? How can I differentiate which features came from which sublayer?

**Comment by vaidotasp** [comment]
Agreed with above questions, work will be tracked in #834
