### ISSUE TITLE
GFW header URL

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#843]
<img width="363" alt="Screen Shot 2020-02-25 at 9 49 11 AM" src="https://user-images.githubusercontent.com/9040867/75258447-73fe5900-57b4-11ea-9056-6e2eec0934e3.png">
Update the URL to a working URL. Is also broken on production.

@csphang can you confirm what URL we should use in this header?

**Comment by csphang** [comment]
@eyosef here is the URL to use! https://developers.globalforestwatch.org/map-builder/
