### ISSUE TITLE
GFW default basemaps

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#845]
<img width="300" alt="Screen Shot 2020-02-25 at 3 06 37 PM" src="https://user-images.githubusercontent.com/9040867/75284526-fef64800-57e2-11ea-99a7-0af6bda68dc9.png">

ESRI default basemaps should render in the left panel and should have corresponding logic to update the map's basemap

**Comment by vaidotasp** [comment]
done per #846
