### ISSUE TITLE
My GFW Integration

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#858]
Master issue tracker for all functionality related to MyGFW

- [x] MyGFW button shows avatar from Google
- [x] "My GFW" button and dropdown is appropriately styled.
- [x] myGFW dropdown should close when user clicks outside of the dropdown #941 
- [x] User is able to login using Google
- [x] User is able to login using Twitter
- [x] User is able to login using Facebook
- [x] User is able to retain logged in state if refresh window happens
- [x] Subscription modal is appropriately styled
- [x] User is informed if subscription needs email validation
- [x] User clicking on globe is taken to that location and zoomed to it
- [x] Subscription window displays data sets and which are subscribed and which are not
- [x] Subscription window displays data sets and user can subscribe/unsubscribe from the window
- [x] User is able to delete data set by clicking on trash icon

**Comment by vaidotasp** [comment]
@eyosef I've noticed that login dropdown does not hide away if user clicks away anywhere outside of it, meaning if I pop open login dropdown, but click on header/leftpanel/map it still keeps open. It should probably close.

**Comment by eyosef** [comment]
@vaidotasp I'll update this ticket to include this! It should be straightforward to implement. Thanks for catching.

**Comment by vaidotasp** [comment]
Closing this as this is done, the part about avatar image will be addressed with the work for CMS
