### ISSUE TITLE
Drawing a polygon - can we set a custom message?

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#880]
<img width="297" alt="Screen Shot 2020-03-06 at 3 07 33 PM" src="https://user-images.githubusercontent.com/9040867/76118934-543d1100-5fbc-11ea-98e0-58bc6eb4f4ab.png">

workflow: draw a polygon. Select 'edit' to edit the polygon. Custom message appears

**Comment by vaidotasp** [comment]
We draw polygon using COORDINATES option. When we edit such poly, we show coordinate values somehow.
