### ISSUE TITLE
memory leak in BaseAnalysis.tsx

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#937]
Looks like the `useEffect()` in `BaseAnalysis.tsx` might be the source of a memory leak. Workflow is to select a polygon on the map, and then select the analysis tab. Including a screenshot to support debugging;
![Screen Shot 2020-04-02 at 2 27 35 PM](https://user-images.githubusercontent.com/9040867/78284975-2a5d0880-74ee-11ea-8ca2-bd0604bc0b2f.png)

_Originally posted by @eyosef in https://github.com/wri/gfw-mapbuilder/pull/933#issuecomment-608029753_

**Comment by vaidotasp** [comment]
It does not seem to be happening anymore, closing for now.
