### ISSUE TITLE
fetch request `https://...check-logged` not working

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#939]
Fetch request for URL `https://...check-logged` is failing to authenticate user login. we're getting a `401`error `not authorized`. Weirdly enough, when we run the oauth URL in the browser it works perfectly! 

Below is a comparison of network requests (**left**: browser-run URL. **right**: `App.tsx` fetch request);

![Screen Shot 2020-04-03 at 10 51 59 AM](https://user-images.githubusercontent.com/9040867/78376564-83837580-759c-11ea-8635-9afa7fe02854.png)

It looks like the browser is able to access a cross-site cookie that's generated from the user login, while `App.tsx` is not able to access this. As of now, it doesn't look like there are any modules or out of the box approaches that enable cross-site cookie access (i.e, the[ `Fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)). I believe this is to prevent security issues.

Potential next steps could include additional oauth configuration in `myGFWContent.tsx` . I.e, using additional logic to authenticate/generate a user session token that can then be leveraged in `App.tsx` to grab the user session info.

**Comment by eyosef** [comment]
Placing a HOLD on this because @csphang mentioned the WRI team is updating their oauth endpoints/API. They should have an update implemented by mid-summer, around June.

@csphang also recommended getting in touch with Tim. Thanks @csphang !

**Comment by vaidotasp** [comment]
This has been solved by GFW. Seems to be back to normal.
