### ISSUE TITLE
Print widget GFW_Mapbuilder_Landscape not working

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#942]
Print widget option 'GFW_Mapbuilder_Landscape'  returns this error;

![Screen Shot 2020-04-06 at 11 15 14 AM](https://user-images.githubusercontent.com/9040867/78574372-e7ee4100-77f7-11ea-85df-b9a50e559a86.png)

**Comment by vaidotasp** [comment]
@eyosef Is this still valid? I just ran clean slate and both options print out? Can you check? Close if it is no longer a bug 👍

**Comment by eyosef** [comment]
@vaidotasp Nope, looks like this bug is no longer an issue!
