### ISSUE TITLE
Respect extraLayers configs

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#956]
- [x] App applies MASK layer at top level which is ignored in the config, layer panel and query targets. 
- [x] USER_FEATURES can be ignored as we do not use it
- [x] MASK layer handles MapServiceLayer as works as expected
- [x] All other defined layers in the extraLayers object assume these properties: 1) they cannot be queried for features, they always appear on the map, they do not appear on the left panel and legend.
- [x] Update WIKI to include these extraLayers notes. @csphang 

WIKI Suggested Entry:
"
Layer group `extraLayers` accepts an array of layer objects that follow established config requirements. Any **dynamic** or **feature** layer is accepted in this group. Any layer added to this group will not be visible in left layer panel, legend or be queryable. 
To use a specific country mask, you have to use layer object config example below. ISO code for the country should be also specified in config (see **Plain Attributes** wiki section).
```
      {
        id: 'MASK',
        type: 'dynamic',
        order: 10000,
        url:
          'https://gis.forest-atlas.org/server/rest/services/country_masks/country_mask_global/MapServer',
        opacity: 0.35,
        layerIds: [0]
      },

```
"

**Comment by csphang** [comment]
Wiki layers section has been updated with content about extralayers

**Comment by vaidotasp** [comment]
Looks great! I will close the issue! Thanks
