### ISSUE TITLE
Adjust height/width of language dropdown & legend

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#999]
<img width="386" alt="Screen Shot 2020-04-27 at 4 16 45 PM" src="https://user-images.githubusercontent.com/9040867/80416805-bc182580-88a2-11ea-9dcd-a34977367333.png">
<img width="182" alt="Screen Shot 2020-04-27 at 4 16 58 PM" src="https://user-images.githubusercontent.com/9040867/80416806-bcb0bc00-88a2-11ea-8e71-29576b999c96.png">

* legend needs max-height and overflow-y scroll
* language dropdown width needs to be set ti 'fit-content' to work across content

**Comment by vaidotasp** [comment]
can you hold on language dropdown adjustments, I have a pr in the works that touches the header in some ways.
